### ISSUE TITLE
Replace `@serviceTitle` and `@serviceVersion` with `@service` 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1003]
As decided in design https://github.com/microsoft/cadl/issues/679 we should replace those decorators with a new one

- [x] Deprecate `@serviceTitle` and then remove
- [x] Deprecate `@serviceVersion` and then remove
- [x] New decorator `@service`, which would take an object with optional properties:
  - `title`: Service title
  - `version`: Service version. 

```ts
export interface ServiceData {
  title?: string;
  version?: string | EnumMember;
}
export function $service(context: DecoratorContext, target: NamespaceType, data: ServiceData) {
}

**Comment by markcowl** [comment]
pri: 1
estimate: 3
