### ISSUE TITLE
CI E2E investigate issue on node 16 windows 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1009]
This PR had to disable e2e on windows https://github.com/microsoft/cadl/pull/1001.

Original problem seems to be the version of `npm` bundled in node 16 is having issue with running `npx -g /local/foo.tgz` where it wouldn't install teh tgz file but try to resolve the package from `npm` which would fail in the prepare release publish as its not published yet.

`npm install -g npm` however seems to not update things correctly on windows. (Solve the issue on linux node 16.x but not windows)

**Comment by timotheeguerin** [comment]
One solution would be to just remove the updating of npm(which is quite slow on windows - 1min) and just skip the step for prepare publish PRs.

**Comment by markcowl** [comment]
- scope to skipping the npm update for prepare-publish

**Comment by markcowl** [comment]
pri: 0
est: 2
