### ISSUE TITLE
Implementation `@versioned` and `@service({version: }` coordination

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1010]
Design discussion https://github.com/microsoft/cadl/issues/982

### Service version when not using versioning

When not using versioning, we can just pass the version as it is.
```
@service({version: "1.0.0"});
namespace MyService;
```

### Service version when using versioning

When using versioning, the service version shouldn't be specified

```cadl
enum Versions{v1, v2, v3}

// Ok, version not explicitly provided
@versioned(Versions)
@service
namespace MyService;

// Bad
@versioned(Versions)
@service({version: Versions.v3});
namespace MyService;

// Bad: version not defined in versioned list
@versioned(Versions)
@service({version: "1.0.0"});
namespace MyService;

// Bad: not the latest versin
@versioned(Versions)
@service({version: Versions.v1});
namespace MyService;
```

In the versionning projection in turn it can set the service version on the fly.

**Comment by markcowl** [comment]
pri: 1
est: 3

**Comment by tjprescott** [comment]
Completed in #1519.
