### ISSUE TITLE
Poor error location for duplicate-response

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#1012]
The error is very far away from where I would expect it to be (in return location).

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0KDQp1c2luZyBDYWRsLkh0dHDFFG1vZGVsIEEgeyB4OiAxIH3IEkIgeyB5xxJ1bmlvbiBBb3JCIHsNCiAgYTogQTvECWI6IEI7DQp9xElvcCBmb28oKTrFKTs%3D)

That said, I wonder if this should even be an error. As an alternative, any return types with the same status code are unioned together, i.e. these two examples are equivalent when A or B have no status code or the same status code:

```
op foo(): A | B;
op foo(): { @body: A | B }
```

**Comment by markcowl** [comment]
pri: 0
