### ISSUE TITLE
Open API format flag for YAML 

### ISSUE THREAD

**Issue by claudiababescu** [microsoft/cadl#1020]
When emitting to Open API you don't get a choice between JSON and YAML. Is it possible to add a flag to support this ?

**Comment by timotheeguerin** [comment]
Believe we talked about this some time ago but got forgotten. I think we could also decide to emit yaml depending on the configured output file extension(`.json` or `.yml`/ `.yaml`) + maybe an explicit flag.

**Comment by claudiababescu** [comment]
That would be great

**Comment by markcowl** [comment]
est: 3
pri: 1

**Comment by markcowl** [comment]
@claudiababescu This is currently schedule for the early December release
