### ISSUE TITLE
Update default collectionFormat and add encoding string to header and query parameters

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1027]
Implementation issue for: https://github.com/Azure/cadl-azure/issues/1790

- Add optional parameters to query and header decorators for format
  - for query, format can be 'csv', 'multi', default should be multi
  - for header, only csv is allowed (and should be default)
  - target parameter/property must be a string array (or equivalent) type
- Add support in OpenAPI3 emitter for this additional data
  - for header, add `style: simple` to the parameter object (csv)
   - for query
     - add style: form for csv
     - add style: form and explode: true for multi
- Add support in cadl-autorest for this additional data (should emit collectionFormat: csv | multi in the schema)

**Comment by markcowl** [comment]
Note: to protect existing parameter for these decorators:
```
@header({format: "csv"}) foo: string[];
```

**Comment by markcowl** [comment]
pri: 0
est: 5

**Comment by lirenhe** [comment]
We are currently working on JS RLC for maps and it contains https://github.com/Azure/azure-rest-api-specs/blob/83d42b77e751deafcf46784877922ec1538f41c6/specification/maps/data-plane/Render/stable/2022-08-01/render.json#L670 
If we are going to ask them to move to CADL, we need to support this feature.
