### ISSUE TITLE
How do we ensure that Cadl "builds" can be reproducible?

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#1028]
This came up in a discussion with the API Stewardship Board on August 17, 22 (Azure/cadl-azure#1906):
 
>Open question: What happens when you pin a specific version of the Cadl library?
>
> -  If I want to document behavior, do we need to specify an exact version of the azure-core library?
> -  Use case: Reproduce-able builds. The API specs repo should be a monument of what the API looked like and behaved at a specific point in time.
> -  The API definition is a contract, and we must be able to reproduce and adhere to that contract.

If we wanted to ensure that the emitted output of a particular Cadl spec could be reproduced perfectly, how could we do that?

Some thoughts:

- Generate a `package-lock.json` file on demand at emit time so that it can be used to reinstall the same versions of all packages and dependencies
- Make sure that the spec itself is `versioned`
- Make sure that the spec uses specific Cadl library versions with `versionedDependency`

Problems we would like to avoid:

- Getting a different output the next time you run Cadl on a spec in CI as part of tooling automation
- Changes to decorators in minor/patch releases causing noticeable output changes for the same Cadl library version

Guidance:

- When developing a Cadl spec, produce and check in a `package-lock.json` file (or whatever the equivalent would be for another package manager)
- When running automated tooling in CI or otherwise, make sure to run `npm ci` or equivalent command to ensure that `package-lock.json` is adhered to
- Cadl specs **must** be verisoned and use versioned Cadl libraries (this is enforced by default)

New Cadl Features:

- It may be possible that decorators that have major behavior changes across Cadl library versions must be switched out per library version used, i.e. the same decorator `@something` could exist in both `1.0` and `2.0` versions of `cadl-azure-core` and there might be two different JS functions behind it, one for each version (this feature does not exist yet!)
- Alternatively, we need to have a namespacing convention for multi-version Cadl libraries such that decorators that have changed significantly must be pulled in from a different namespace (though, this could make things more complicated for spec authors).

### Conclusions

- Provide a CLI command to bundle up the collateral needed to reproduce a particular output
- Document how to make builds reproducible (`npm ci`, `package-lock.json`, etc)
- We will not worry about actual dependency version updates but guard against breaking backwards compatibility using baseline spec validation

**Comment by markcowl** [comment]
pri: 0

**Comment by tjprescott** [comment]
@markcowl I think this needs an implementation issue
