### ISSUE TITLE
OpenAPI extension not applied if used on model `is` intrinsic type

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1033]
```cadl
import "@cadl-lang/openapi";

op test(): Foo;

@OpenAPI.extension("x-foo", "bar")
model Foo is string;
```
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL29wZW5hcGkiOwoKb3AgdGVzdCgpOiBGb287CgpAT3BlbkFQSS5leHRlbnNpb24oIngtZm9vIiwgImJhciIpCm1vZGVsxC8gaXMgc3RyaW5nOw%3D%3D)

```json
{
 "schemas": {
      "Foo": {
        "type": "string"
      }
    }
}
```
Fix in:
- [ ] openapi3
- [ ] cadl-autorest

**Comment by markcowl** [comment]
pri: 0
est: 3
