### ISSUE TITLE
Add Uri type to http library

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1038]
Implementation issue for #654

- Add Uri type to the http library
- Update samples to use 'Uri' type in server decorators
- Update cadl-autorest and OpenAPI3 to skip url encoding for parameters marked as 'Uri'

**Comment by timotheeguerin** [comment]
is this a type that we only see being used in http library? does having a url not something more general than http?

**Comment by timotheeguerin** [comment]
Fixed in #1055
