### ISSUE TITLE
Resolve usage(input, output or both) of various types in the given set of operations

### ISSUE THREAD

**Issue by chunyu3** [microsoft/cadl#1046]
.Net DPG will support to generate convenience methods for selected operations and the models used in those selected operations only. 
We define convenience decorator (`@OpenAPI.extension("x-ms-convenient-api", true)`) to identify which operation will generate convenience method. e.g.
```
 @route("transactions")
  @summary("Writes a ledger entry.")
  @doc("A collection id may optionally be specified.")
  @post
  @OpenAPI.extension("x-ms-convenient-api", true)
  op createLedgerEntry is Azure.Core.ResourceCreateWithServiceProvidedName<
    LedgerEntry,
    {
      parameters: CollectionIdParameter;
    }
  >; 
```

And we only generate models which are used in those selected operation.

So we need to resolve usages for types in the given set of operations.
 
cadl compiler has already provided an API `
export function resolveUsages(type: NamespaceType | InterfaceType | OperationType): `  which will resolve the usages in a special namespace, or interface or operation.
 
Can cadl compiler provide another API which will resolve usage in the given set of operations?
`export function resolveUsages(ops: Operation[])`

**Comment by markcowl** [comment]
pri: 1
est: 2
