### ISSUE TITLE
Multiple `@service` per cadl file/project

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1052]
Implementation issue for design #679.

Allow multiple `@service` decorator to be defined in the same project. Behavior of emitter for now should just be to emit every service independently. The output file could use the service title as a filename or default to `openapi.json` if only one.

Update `outputFile` to be able to interpolate `{serviceTitle}` (and maybe version to be consistent)

**Comment by markcowl** [comment]
pri: 1
est: 5

**Comment by markcowl** [comment]
Complete

**Comment by timotheeguerin** [comment]
@markcowl I don't think this was completed
