### ISSUE TITLE
Incorrect error about the global namespace referencing types from a versioned namespace

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#1054]
Another weird one for you @timotheeguerin:

I found a particular combination of factors that causes this interesting error:

```
error @cadl-lang/versioning/using-versioned-library: Namespace '' is referencing types from versioned namespace 'Contoso.WidgetManager' but didn't specify which versions with @versionedDependency.
```

Here is a [playground sanple](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmfMIGF6dXJlLXRvb2xzL8UsxhFjb3JlIjsKCnVzaW5nIENhZGwuSHR0cDvMEVJlc3TNEVbJYsgXQcRNLkNvcmU7CgpuYW1lc3BhY2XLFyB7CiAgQHJlc291cmNlKCJvcGVyYXRpb25zIinEGnBhcmVudFLIIFTICsQdbW9kZWwgyBJPyDpTdGF0dXM8ySs%2BxWQgIEBrZXnFCclkSWQ6IHN0cuUAsMUaLy8gUkVQUk86IENvbW1lbnQgdGhpcyBvdXQgYW5kIHRoZSBwcm9ibGVtIGdvZXMgYXdhxlPKOU1ha2XGNmFueSBvdGhlciB0eXBl30FyZXN1bHQ%2FOiDpALc7CiAgfeQAlyNzdXBwcmVzc%2FQBrnByb3ZpZGVyaHViL25vLWlubGluZS3lARoiICJU5ACI5ACLY2NlcHRhYmxlIGlu6wF%2BLiIKICBhbGlhc%2FgBR1Jlc3BvbnNl7AFPPdgtzCUm5QDXRm91bmTFInMuSXRlbUtleXNPZssoOwp9CgpAc2VydmljZVRpdGxlKCJDb250b3NvIFdpZGdldCBNYW5hZ2VyIikKQOcCw2VkKMckLsYkxyPoAoFzzCtEZXBlbmRlbmN5KAogIFtb3joudjIwMjJfMDhfMzEs7AEqyiExXzBfUHJldmlld18xXV0KKesC2dVdIHsgICAKICBlbnVtIMhI5wKVy286ICLEDS0wOC0zMSIs6AH%2FQGRvYygiQSB3xVMu5gMX6gMxxhfmAy7mAxHGfOsC9cglTmFtZSIp5gCMICDkALXqAv%2FHbWludGVyZuQAysZG6ACn5gCFU2NoZWR1bGUgYecAjiBmb3IgcmVwYWlyc%2BYAmiAgc8clUsYX5AJ%2F6AHuQWPkAgo8xScgx2LkAOjEAXt9yAryA4XkA4DkAztB5QLHZWToApX%2FA1Qg7AHA%2FwLgPOYAjj4gJuoE7S7QcMVWPuYBLX0%3D) that reproduces the issue.

The problem goes away if you do one of two things:

- Change the type of `result?: TResource` to not use `TResource` (or remove the property entirely)
- Remove the `& Cadl.Http.AcceptedResponse` on line 49

I'm not sure how this combination causes the global namespace to be affected by versioning checks!

**Comment by timotheeguerin** [comment]
Smaller repro without azure core https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5IdHRwO8wRUmVzdM0RVsk7OwoKQMdJZWQoxxhzKQpuYW1lc3BhY2UgTXlMaWIgewogIGVudW0gyCPFEiAgdjEsxggyxAh9CiAgbW9kZWwgUmVzb3VyY2VPcGVyYXRpb25TdGF0dXM8VMgZPsdBLy8gUkVQUk86IENvbW1lbnQgdGhpcyBvdXQgYW5kIHRoZSBwcm9ibGVtIGdvZXMgYXdhec85TWFrZcY2YW55IG90aGVyIHR5cGXfQXJlc3VsdD86IOkAlDvlAMN9CgpAc2VydmljZVRpdGxlKCJDb250b3NvIFdpZGdldCBNYW5hZ2VyIinsATvHJC7GJMcj6AFpc8wrRGVwZW5kZW5jeSgKICBbW946LnYyMDIyXzA4XzMxLOYBjcscMV1dCuwBrdVMIHsgICD4AcDKXjogIsQNLTA4LTMxIuYBz%2BkB0EZvbyB7xRBpbnRlcmbEbcZlyEp0ZXN0KCk65wCj%2BAIARm9vPiAm6gKoLkFjY2VwdGVkUmVzcG9uc%2BgBhA%3D%3D
