### ISSUE TITLE
Make `program.getNamespaceString` a top-level exported function for emitters

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1057]
In Cadl APIView, I ended up writing a function to get a fully qualified namespace string ("A.B.C"). @timotheeguerin pointed out that `program.checker` has a `getNamespaceString` function that does the same thing. This is useful, reusable logic for emitters, and it would be great if we exported this from the compiler library.

**Comment by timotheeguerin** [comment]
To be a bit more precise, I think this is an API that shouldn't be tied to the `checker`, always feels like going too much into the internals when accessing the checker which feels bad in an emitter

**Comment by tjprescott** [comment]
Yes, that's what I meant in the description, exposing a stand-alone `getNamespaceString` function not tied to the checker.

**Comment by markcowl** [comment]
- getNamespaceString
- getTypeName as well

**Comment by markcowl** [comment]
pri: 1
est: 3
