### ISSUE TITLE
Duplicate decorator validation

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1059]
There is many decorators where you shouldn't really be specifying it twice on the same node. A naive approach is to check when running the decorator that the value has already been set and fail if it has. The problem with this approach is when composing types with `is` or with decorators being called from other decorators you might end up in this scenario where something else set the value and you want to override it.

In that case we need to remove the original validation but I think it would still be good to be able to emit a warning if calling the same decorator twice on the same node. (Or even maybe cases where there is multiple decorators that could conflict) This would most likely be a per decorator rule.

```
// Bad

@get 
@get
op foo: string()


// Ok
@get
op Getter<T>(): T

@get // respecify get (noop
op foo is Getter<string>;
```

```
// Bad

@get 
@post
op foo: string()


// Ok
@get
op Getter<T>(): T

@post // override get with post
op foo is Getter<string>;
```

Other decorators where this would be good:
- `@service`
- `@route`

**Comment by markcowl** [comment]
- helper for decorators to opt in to this validation

**Comment by markcowl** [comment]
pri: 1
est: 5
