### ISSUE TITLE
Github.io docs should point to latest only

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1062]
The version of the website published to microsoft.github.io should always show the `latest` version by default but being able to see the docs for the `next` changes(current change in `main` branch) would also be valuable

**Comment by markcowl** [comment]
- publish 'latest' instead of 'next'
  - add a change to release process to release latest docs to website
- selector for versions on website
  - update next docs on website on each push to main

**Comment by markcowl** [comment]
fix

pri: 0 (this sprint)
est: 3

selector

est: 5
pri: 1 (December)
