### ISSUE TITLE
Get cadl type by reference.

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1065]
I think it would be good to have an api that would resolve a type using the fully qualified name.

```ts
getType(program: Program, fullyQualifiedName: string): Type;
```

This would be useful for resolving types declare in a library that might be used later.

## Proposal 

Add an helper that can resolve a Type reference  on the `Program`

```ts
export function getReference(fullyQualifiedName: string): Type;
```

Alternative names:
- `lookupReference`
- `lookupType`
- `findType`

Alternative location:
- as an helper function 

```cadl
namespace MyLib;

model Foo {
  name: string;
}

model Bar<T> {
  value: T;
}
```
Example usage

```ts

// Get a model(or any other type)
program.getReference("MyLib.Foo"); 

// Get a model property(Like you can reference a model property)
program.getReference("MyLib.Foo.name"); 

// Reference template 
program.getReference("MyLib.Bar"); 

// Should we allow referencing template instance. Maybe only if it is already instantiated?
program.getReference("MyLib.Foo<T>")
```

**Comment by markcowl** [comment]
pri: 1

**Comment by markcowl** [comment]
closing for implementation issue #1202
