### ISSUE TITLE
[Metadata] Check for versioning issues

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#1072]
What happens, for example, if you use `@added` and add a property that impacts visibility handling. Can you use this to sneak a breaking change through `@added`?

**Comment by markcowl** [comment]
pri: 0

**Comment by nguerrera** [comment]
I don't think there is a problem here. You can add new fields with `@added(newVersion)` and apply `@visibility` to them. The openapi emit for previous version will be completely unchanged. The new version may split out multiple schemas:

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKQMcPZWQoVsYKcykKQHNlcnZpY2Uoe3RpdGxlOiAiRGVtbyJ9KQpuYW1lc3BhY2UgxBJTxic7Cgp1c2luZyBDYWRsLkh0dHA7zBHHWGluZzsKCmVudW0gyGogeyJ2MSIsInYyIix9CgoKbW9kZWwgVXNlciB7CiAgxG06IHN0csU7ICAKICBAYWRk6wCrLnYyKcQWdmlzaWJpbGl0eSgiY3JlYXRlIinEL3Bhc3N3b3JkykbEZ0Byb3V0ZSgiL3VzZXJzIikKQHBvc3Qgb3AgxjwoLi4u5ACFKTrlAIw7

However, based on the premise underlying the metadata proposal that a Cadl->Code emitter can choose to reason about the logical type, the names introduced purely for OpenAPI emit should not be considered breaking.
