### ISSUE TITLE
OpenAPI3 emitter (Same with autorest) produce 204 for record used as response type

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1076]
```cadl
import "@cadl-lang/rest";

using Cadl.Http;

op test(): Record<int32>;
```

```json
"get": {
        "operationId": "Int32Value_get",
        "parameters": [],
        "responses": {
          "204": {
            "description": "There is no content to send for this request, but the headers may be useful. "
          }
        }
      }
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKb3AgdGVzdCgpOiBSZWNvcmQ8aW50MzI%2BOwo%3D)

Probably a bug with deciding that empty object should produce 204 and not checking for indexer #1015

**Comment by markcowl** [comment]
Tracking this as relkated to #1015
