### ISSUE TITLE
[OpenAPI 3] Need to emit docs and constraints for specialized intrinsics

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#108]
I should be able to declare a special string like

```
@doc("super special!")
@format("^x\w+x$")
model specialString is string;
```

and use this in place of string everywhere and see documentation and constraints reflected in the output openapi.

**Comment by timotheeguerin** [comment]
Details: 

Format is not allowed on extended model
![image](https://user-images.githubusercontent.com/1031227/148597715-de99a0f5-3058-489a-bb58-e6064ab55493.png)

**Comment by markcowl** [comment]
- fix constraints on format decorator (and go over others that require a specific type) to work with is as well as extends
