### ISSUE TITLE
[Metadata] Document end-to-end for emitters

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#1083]
There's enough in the REST layer for a different emitter to handle metadata as the openapi emitter does, but it would be nice to have a small walktrhough on that.

**Comment by markcowl** [comment]
pri: 1
est: 3

**Comment by nguerrera** [comment]
Also document getEffectiveType here.

**Comment by nguerrera** [comment]
I have written a sample that calls all of the API. I am still working on cleaning it up and writing doc text to go with it. Work in progress is here: https://gist.github.com/nguerrera/36df0c007be7d37e5e67fd769958030e

Also putting down some rough notes I have on things to cover in the doc text.

Key point: Put properties in models only if they logically belong there. The feature is about allowing a single logical model + visibility/metadata annotations.


API cheat sheet:

- `getRequestVisibility(HttpVerb): Visibility` - use this to determine the visibility implied for data in the request parameters or body.  (And note also that Visibility.Read is always applied for response data and therefore there is no corresponding response API.)

- createMetadataInfo(Program) - create this once for each projected program/service version, use it to reason about metadata and visibility implications

- metadataInfo.getEffectivePayloadType(Type, Visibility): Type - use this on every type that is referenced. if it is an anonymous model sourced entirely from named properties after metadata is moved elsewhere or invisible properties are removed, it will recover the named model that should be used. This handles `op foo(...Thing)` but also many other cases.

- metaddataInfo.isTransformed(Type, Visibility) - use this to check if a type undergoes any changes in shape. Can allow for simplifications in emit.

- metadataInfo.isPayloadProperty(Type, Visibility) - use this to check if a property is transmitted as an object property (in the payload) and not invisible or metadata sent elsewhere

- Visibility.Item - Add this when recursing into an array. It puts all metadata into payload. Useful in scenarios like batching API calls.
