### ISSUE TITLE
OpenAPI emitter croaks on `unknown` types

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#1096]
The openapi emitter complains about "couldn't get schema for intrinsic" when using `unknown` as the type.

```cadl
import "@cadl-lang/rest";

op stuff(): Something;

model Something {
  attributes: unknown;
}
```

=> error @cadl-lang/openapi3/invalid-schema Couldn't get schema for type Intrinsic

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKb3Agc3R1ZmYoKTogU29tZXRoaW5nOwoKbW9kZWzKEiB7CiAgYXR0cmlidXRlczogUmVjb3JkPHVua25vd24%2BOwp9Cg%3D%3D)

**Comment by timotheeguerin** [comment]
dup of #1075
