### ISSUE TITLE
Update OpenAPI3 (and openapi2) default status code for empty objects

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1101]
Implementation issue for: #1015 

- When no status code is provided, a 'void' return type should result in a 204 status code in emitted OpenAPI
- When no status code is provided, any empty object (object with no properties) should result in a 200 status code in emitted OpenAPI

**Comment by timotheeguerin** [comment]
Think this should be fixed in this sprint as this is blocking usage of Record and array as direct body.
