### ISSUE TITLE
namespace name cannot be the same as interface name

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#1110]
A namespace cannot have the same name as an interface at the same level.

[Playground Repro](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiV2lkZ2V0IFPGGyIsCn0pCm5hbWVzcGFjZSBEZW1vxxs7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdDxFZAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9CgpAZXJyb3LHVkXEDMVVY29kZctAbWVzc2FnZcpkfQrrALLmAI3nALQge30KCmludGVyZtMc5ACw5AC5bGlzdCgpOscfW10gfMZ9xG1Acm91dGUoInfFHHMve2lkfSIpxjhyZWFkKEBwYXRo6wDzyUjNRnBvc3QgY3JlYXRlKEBib2R5IMQFyCvWNMd6Y3VzdG9tR2V0yHfJEeoAtMo4fQo%3D)

I don't think we need to support this, but right now we don't document that this is not allowed so least it should be documented.

**Comment by timotheeguerin** [comment]
This is the same though as every other types. You have a name conflict between 2 types

**Comment by allenjzhang** [comment]
- [ ] Document naming rules: something like cannot have duplicate name at same level.
- [ ] Fix the bug not reporting as error with different order. [Repro](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiV2lkZ2V0IFPGGyIsCn0pCm5hbWVzcGFjZSBEZW1vxxs7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdDxFZAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9CgpAZXJyb3LHVkXEDMVVY29kZctAbWVzc2FnZcpkfQoKCmludGVyZuQAs%2BYAjucAtcVAQOQAnmxpc3QoKTrHH1tdIHzGYsRSQHJvdXRlKCJ3xRxzL3tpZH0iKcY4cmVhZChAcGF0aOsA2MlIzUZwb3N0IGNyZWF0ZShAYm9keSDEBcgr1jTHemN1c3RvbUdldMh3yRHqALTKOH0K6wGj7wDwfQo%3D)
