### ISSUE TITLE
IDE shouldn't require global `cadl` to be installed

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1116]
```
[Error - 11:31:11 AM] Cadl server exectuable was not found: 'cadl-server' is not found. Make sure either:
 - cadl is installed globally with `npm install -g @cadl-lang/compiler'.
 - cadl server path is configured with https://github.com/microsoft/cadl#installing-vs-code-extension.
```

it the compiler is accessible locally it should be able to auto resolve it.

**Comment by nguerrera** [comment]
I think we were tracking this in #1041 and I was supposed to fork off an issue for a nicer `init` without global install, but we can reverse that so this one tracks resolving local server without using global server and that one tracks the nicer init.

**Comment by timotheeguerin** [comment]
est: 5
