### ISSUE TITLE
OpenAPI emitter deduplicating parameters

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1118]
As part of this PR(#1115)  fixing various issue around parent and sourceProperty reference in projections the result was that parameters where always inlined when using `KeysOf`.

```cadl
import "@cadl-lang/rest";

using Cadl.Http;
using Cadl.Rest.Resource;

op test(...KeysOf<Pet>): void;

model Pet {
  @key("petId")
  id: string;
}
```

One option is to call `@friendlyName` in `KeysOf` but just doing that result in the shared parameter to be called `PetKeys` if there is a single key.

**Comment by johanste** [comment]
We do want to trace the lineage of the KeysOf to the original model type that it came from. For Python, an example of code we (want to be able to emit) is:

```python
class Cat:
    id: str
    name: str

class CatClient:
    def update_cat(self, cat: str | Cat, name: str | None) -> Cat: ...
```

In other words, take either the key properties of a resource *or* an instance of the resource as the argument to the method.

**Comment by nguerrera** [comment]
I've put together a proposal in the form of a PR that implements it:

https://github.com/microsoft/cadl/issues/1162#issuecomment-1396177456

We can review the PR description and small diff in the design meeting.

**Comment by markcowl** [comment]
closing in favor of the PR
