### ISSUE TITLE
[VS classic extension] Drop support for VS 2019

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#1130]
We should check with our partners, but at this point I don't think supporting VS 2019 is worthwhile. We could get back to a single VSIX with VS2022+ support only, which would simplify our build and our installation code. Also, .NET 6 requires VS 2022 and the last .NET Core 3.1 (last version of .NET Core / .NET 5+ supported by VS 2019) goes out of support in December.

**Comment by markcowl** [comment]
SHould discuss with vs team on customer usage

**Comment by markcowl** [comment]
@nguerrera Please lmk if you think this is urgent

**Comment by nguerrera** [comment]
Not urgent.
