### ISSUE TITLE
Release notes for deprecating @serviceTitle

### ISSUE THREAD

**Issue by abatishchev** [microsoft/cadl#1132]
I see the [release note for August 2022](https://github.com/Azure/cadl-azure/blob/main/docs/release/release-2022-08-10.md#resolve-by-adding-the-servicetitle-decorator) mentions `@serviceTitle` and the later release notes don't.

But now I'm getting a warning:

```
warning
deprecated
Deprecated: @serviceTitle decorator has been deprecated use @service({title: _}) instead.
```

I'd like to learn what I should to put into `@service()`, please update the docs/sample. Here's [what I searched for](https://github.com/search?q=%22%40service%22+repo%3AAzure%2Fcadl-azure+extension%3Amd&type=Code&ref=advsearch&l=&l=) but it didn't yield anything useful.

**Comment by timotheeguerin** [comment]
This change has not be released to `latest` yet
This is being described in this issue until released https://github.com/microsoft/cadl/issues/1011#issuecomment-1252478012
