### ISSUE TITLE
Allow overriding of intrinsic type property in derived types

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1137]
From design issue [#762](https://github.com/microsoft/cadl/issues/762)

Allow the following

```
model Parent {
  name: string;
}

model Child extends Parent {
  name: "abc"
}
```

Rule for allowing override:
- base type MUST be a intrinsic type
- derived type MUST be a subtype of the base type

**Comment by markcowl** [comment]
est: 8
pri: 1

**Comment by tjprescott** [comment]
@allenjzhang I don't seem to be able to add this the the CADL Project project?

**Comment by tjprescott** [comment]
> There is a pushpin label so it should have been added to the project.

Yeah, it was, but I couldn't see that here. I could see it on the project board though. Call it gremlins.
