### ISSUE TITLE
`@Cadl.Versioning.added` and friends can be applied to namespaces, but don't have any effect (I think)

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#1143]
Is @Cadl.Versioning.removed and friends supposed to work on namespaces? It doesn't complain, but it also doesn't seem to have any effect....

[playground](https://cadlplayground.z22.web.core.windows.net/prs/1138/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3ZlcnNpb25pbmciOwrTIHJlc3QiOwoKQENhZGwuVskuLsc5ZWQoQVNlcnZpY2XIHnMpCkBzxhMoeyB0aXRsZTogIkRhIMcVIn0pCm5hbWVzcGFjZSDIPjsKCmVudW0gyEUgewogIHYxLMQGMsUGMwp98wCIcmVtb3ZlZCjIOC52MsxfV29tcGFExAUgewoKICBtb2RlbCBGdW5recViICBoZWxsbzogc3RyaW5nOwogIH0KCgovL8Qb323EbTMp2izkAIZkRnJvbcwwLCAiZ29vIinFfMY1SHR0cC5yb3V0ZSgiL2dvb3NlMdIgcG9zdCBvcCBhYmFuZOQBeF9nb28oKTrmAMw79QEcYWRk8ACt5gEAU29tZXRoaW5nQ29tcGxldGVseURpZmZlcmVudOUBF2TFDjogdHJ1Zd9cylz4AM4yIs0c6ADK5wDA%2FACMOwoK)

**Comment by johanste** [comment]
(obviously, it could be an emitter problem as well - but openapi3 shows things that I wouldn't expect to get squirted out)

**Comment by bterlson** [comment]
It was intentional not to allow versioning of namespaces, at least directly, since the namespace is a cadl-local concept and not a service concept it didn't make sense. But I suppose you are using it as a shortcut for adding `@added` to everything underneath the namespace?

**Comment by johanste** [comment]
> But I suppose you are using it as a shortcut for adding @added to everything underneath the namespace?

Correct. It has come up in the "what's the worst that can happen to a service from a breaking change perspective and how do we recover" scenarios. Being able to just "remove" everything in a namespace and start from scratch can be a very powerful tool.

**Comment by markcowl** [comment]
- go through the set of decorators to see which others this behavior should apply to

**Comment by markcowl** [comment]
pri: 1

**Comment by markcowl** [comment]
- decorator application as part of documentation (does it apply to all members of the group, or just the decorated entity)
- is there a limited selector language we can use instead?

**Comment by markcowl** [comment]
- selectior language
- for custom decorators

**Comment by markcowl** [comment]
Closing as a design issue @bterlson can you file the work item(s) for emitter framework improvements for custom decorators that are meant to apply to multiple types inside a container?
