### ISSUE TITLE
If multiple, separate namespaces share the same versioning enum, should they version together?

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#1154]
Imagine a situation like:

```
enum Version { v1, v2 };

@versioned(Version)
namespace N1 { }

@versioned(Version)
namespace N2 { }
```

Since these two namespaces use the same version enum, should we treat these as if they were under a common versioned namespace? It seems very likely that is the user intent.

**Comment by nguerrera** [comment]
Note that #1520 is probably blocking this.

**Comment by markcowl** [comment]
Or, at least making it more difficult
