### ISSUE TITLE
Simplify 'extensible' enums in cadl

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1168]
Implementation issue for #1104   When [Azure issue](https://github.com/Azure/cadl-azure/issues/2134) is implemented.

~- deprecate `@knownValues` decorator~
- Update documentation and breaking change issue

**Comment by markcowl** [comment]
People were pretty adamant about hating it.

**Comment by timotheeguerin** [comment]
Yeah but the new alternative is not available for non azure. The openapi issue about this does have a lot of people intrested in representing extensible enums (which you do with oneOf(string, enum)) Maybe we can just that then
