### ISSUE TITLE
Model property delimiter confusion?

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1172]
```cadl
model Foo1 {
  a: string;
  b: int16;
}

model Foo2 {
  a: string,
  b: int16;
}

model Foo3 {
  a: string;
  b: int16
}
```

Why is it that you can mix and match between commas and semicolons when delimiting properties of a model? All of the above are valid, but kind of bizarre. Is this a Typescript convention we are replicating? 

Because operation signatures use a "hidden" model, it means you can delimit operation parameters using commas or semicolons, which again seems really weird.

I guess regardless of why, what do we actually want people to do?  This came up in an stewardship board review. I would assume:
- operation parameters should be comma-separated
- model parameters should be semicolon-separated
- anonymous models should be... ???

**Comment by tjprescott** [comment]
So anonymous models should also use semicolons?

**Comment by timotheeguerin** [comment]
yeah, though actually I think the rule should be(to be completely in line with typescript)
- model properties: use `;`
- operation parameters: use `,`

(only different with above is the single line model) This doesn't matter for the formatter as it always break properties into newlines

**Comment by tjprescott** [comment]
Got it. Thanks for the clarification. Closing.
