### ISSUE TITLE
Emitter Utils emitFile should automatically create the parent folder if not there

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1178]
It is a bit annoying to have to check the parent folder to the file you want to emit exists

**Comment by bterlson** [comment]
I think blindly creating the path you want to emit to (and not erroring when its present) is the more typical pattern?

**Comment by timotheeguerin** [comment]
Yeah, I think it's expected, we didn't notice this problem before because the cli was automatically creating the output-dir(which I think we should then remove that) and every emitter was just outputting at the root of that folder.
