### ISSUE TITLE
Add `scalar` and `unit` declarations

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#1187]
Cadl has a number of scalar types (ints, floats, etc.) and two common unit types (null. void) but the way these are presently implemented present some problems:

1) we assign special semantics to them via `@intrinsic` decorator, overloading the notion of intrinsic (we also have an intrinsic type kind)
2) scalars are created using `model`, running the risk that emitters treat these as objects without any properties
3) users are not able to declare their own scalars which seems likely to be a common request when modelling some APIs, e.g. we don't have scalars for decimal64/decimal128.

If we added scalar and unit declarations, all of these problems go away I think. A proposed syntax might be:

```
scalar decimal extends numeric;
scalar decimal64 extends decimal;
unit undefined;
```

For scalars, the extends clause is optional but allows you to create subtype relationships between your scalar values which seems very useful. Likewise, NumberLiteral, StringLiteral, and BooleanLiteral types can be subtypes of scalars that are numeric, string, and boolean respectively, which allows for nice ergonomics when creating subtypes with specific required values (and for passing actual values in the case of the #888 valueOf proposal).

Under this proposal, a common code pattern would likely be broken - it is super common to declare a string type with some constraints:

```
// should be an error
@maxLength(10)
model shortString is string;

// use this instead
@maxLength(10)
scalar shortString extends string;
```

It's not entirely clear that we should be using `is` rather than `extends` for scalars, I think either keyword could be argued (probably new scalars are subtypes not identical types, so extends seems appropriate, but then the copying-down of decorators seems important maybe, so `is` seems appropriate).

**Comment by markcowl** [comment]
- include some fix tools for spec authors
- update emitter handling of intrinsic types
- update libraries

**Comment by markcowl** [comment]
- schedule with 'code fixes' support

**Comment by bterlson** [comment]
`unit` is perhaps badly named because `unit type` is somewhat a term of art, whereas `unit of measure` is quite common and might(?) make sense in the context of API design as well.

**Comment by markcowl** [comment]
## Notes from design meeting
- investigate whether we cna avoid the breaking change in specs
- require scalars to extend existing scalars in the first implementation
  - this will require some custom treatment of the language-defined scalars
- model gRPC types using scalar
- Use 'extends' instead of 'is' for definiing new scalars
- Do not implement unit for now

**Comment by markcowl** [comment]
- date and time types as scalar?
  - datetime
  - zoneddatetime
  - url

**Comment by timotheeguerin** [comment]
This is all the models that have `@intrinsic` today

```cadl
model bytes {}
model numeric {}
model integer {}
model float {}
model int64 {}
model int32 {}
model int16 {}
model int8 {}
model uint64 {}
model uint32 {}
model uint16 {}
model uint8 {}
model safeint {}
model float32 {}
model float64 {}
model string {}
model plainDate {}
model plainTime {}
model zonedDateTime {}
model duration {}
model boolean {}
model null {}
```

I think all of them except `null` can be updated to be a `scalar`

**Comment by timotheeguerin** [comment]
Created implementation issue #1272
