### ISSUE TITLE
Remove `@intrinsic` decorator

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#1192]
The presence of this decorator I think causes some confusion with the `intrinsic` type kind. Also, the decorator is a bit overloaded, as it accomplishes a couple things:

1. makes `model` decls into scalar or unit types. E.g. when the checker instantiates a model type, it checks if it has an intrinsic name, and if so sets the model's indexer key to `never`.
2. enables the compiler to check whether a particular type is either a built-in scalar type or a model derived from it (e.g. a `shortString`). This works because we have you doing `model is` which copies the `@intrinsic` decorator down.
3. marks a type as "built-in" in some sense

For one, #1187 I think solves this usecase in a first-class way.
For two, an API that uses types looked up by identity and compared using subtype comparison would make a lot more sense. E.,g. `if (getIntrinsicModelName(program, type) === "Number") becomes `if (isSubtype(type, program.builtIns.Numeric)) { }`.
For three, I think we already have this - things under the Cadl namespace plus things with the `intrinsic` type are built-ins, but I'm not sure this distinction is super necessary anyway.

**Comment by timotheeguerin** [comment]
Another use case blocked on our dependency on `@intrinsic` is for decorator definition you cannot do that

```cadl
// Saying here that the target must be a string model
dec format(target: string, value);
```

```cadl
@format("uuid") <== would complain here that mystring is not a string
model mystring is string;
```
As by the type the `@format` decorator validation is run it the `@intrinsic`  decorator hasn't been run yet

**Comment by markcowl** [comment]
implement with #1187
