### ISSUE TITLE
operation returning `| null` seems to not impact openapi output at all now

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#1204]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2Uoe3RpdGxlOiAiV2lkZ2V0IFPGGCIsfSkKbmFtZXNwYWNlIERlbW%2FHGjsKCnVzaW5nIENhZGwuSHR0cDvMEVJlc3Q7Cgptb2RlbCDHVHsKICBpZDogc3RyaW5nOwp9CgpAcm91dGUoIi93xSMve2lkfSIpCm9wIGdldCjKLSk6yEV8IG51bGw7Cg%3D%3D)

**Comment by timotheeguerin** [comment]
Think that from this issue https://github.com/microsoft/cadl/issues/356

**Comment by nguerrera** [comment]
Duplicate of #356
