### ISSUE TITLE
The openapi3 emitter does not process the optional header/query parameter name

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#1209]
The `@header` and `@query` decorators accept an optional parameter which should be used as the actual header or query parameter name, but the openapi3 does not process this optional value.

Playground repro: [here](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiV2lkZ2V0IFPGGyIsCn0pCm5hbWVzcGFjZSBEZW1vxxs7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdDxFZAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9CgpAZXJyb3LHVkXEDMVVY29kZctAbWVzc2FnZcpkxDpyb3V0ZSgiL3flAIxzIikKaW50ZXJm5ADF5gCg5wDHxVJA5ACwbGlzdCgKICAgIEBwYXRo6wC3LMYWaGVhZGVyKCJ4LW1zLXJlcXVlc3QtaWQiKSDHDUnQMnF1ZXJ5KCIkc2VsZWN0IikgxgnIJgogICk66AEvfOYA4uQAvw%3D%3D)

**Comment by markcowl** [comment]
est: 2
