### ISSUE TITLE
`@cadl-lang/compiler.getServiceVersion` should not default to "0000-00-00" when none is found

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1218]
This seems like a bizarre default to have since it means logic has to search for this magic string. It should either return empty string or, more accurately, undefined.

![image](https://user-images.githubusercontent.com/5723682/197627409-78656cfb-e986-47fd-bc8f-aabfc3d3285d.png)

I encounter this in APIView when running against a library vs. a service spec.

```typescript
// current (bad)
let version = getServiceVersion(program);
if (version == "0000-00-00") {  // blarg! a magic string! ... and I have to use let instead of const
  version = "whatever default I want";
}

// better
const version = getServiceVersion(program) ?? "whatever default I want";
```

**Comment by markcowl** [comment]
implement as part of #1052
