### ISSUE TITLE
`@cadl-lang/compiler.getServiceNamespace` returns global namespace if not found

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1220]
![image](https://user-images.githubusercontent.com/5723682/197629756-c057b76d-a450-4521-8255-7ac2b74e501b.png)

I think this should return `undefined` instead of assuming that if someone calls for the _service_ namespace and one isn't found that it instead returns the global namespace instead. Rather than make this decision for emitter authors, it would be better for them to decide how to handle this.

```typescript
// current (bad) - this may be a service NS or the global NS!!! Buyer beware!
const serviceNs = getServiceNamespace(program);

// better - now the author explicitly asks for this...
const serviceNs = getServiceNamespace(program) ?? getGlobalNamespaceType(program);

// better - or they say, no I don't want your global NS! This is an error!
const serviceNs = getServiceNamespace(program);
if (seviceNs == undefined) {
  throw new Error("Ermagherd! You must have a service NS!");
}
```

**Comment by bterlson** [comment]
+1, this feels like something that might have made sense in a world of a single service per cadl compilation, but seems quite suspicious today. Letting consumers decide whether to substitute global or throw an ermagherd seems good to me.

**Comment by timotheeguerin** [comment]
I agree, it is a bit annoying that you also want a different logic if its the global namespace(only gets stuff at the root) so you do still have to be aware of it. Mostly for making easy repro but it is easily error prone. Being explicit would be great.

**Comment by markcowl** [comment]
implement as part of #1052
