### ISSUE TITLE
Versioning library does not work when multiple copies of it are loaded

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1232]
Whilst working on the `cadl-apiview` emitter, I wanted to ensure that the user can specify which version of a spec they want to see the Cadl for. I followed the guidance in the [README](https://github.com/microsoft/cadl/tree/main/packages/versioning#consuming-versioning-library-from-an-emitter), expecting that the projected program would remove references to things which are not supported in the given version. I was confused when the model in question did in fact still appear.

I tested my spec against OpenAPI3 and saw that yes, the generated Swagger omitted the model that was not supported. Debugging into OpenAPI3 (assuming my code was faulty) I found that even when the program is projected to the right version, the projected namespace *still* contains the unsupported model. 

![image](https://user-images.githubusercontent.com/5723682/197893227-00ba893b-6cef-4552-a3ed-469d81893848.png)

In this case, `AmazingNewModel` is not supported by `2022-05-23` and my expectation is that it would be removed from the projected namespace, but it is not. The OpenAPI3 emitter works, so it must be scrubbing the offending model out somehow, but it is neither clear not documented how that happens.

**Comment by nguerrera** [comment]
Hmm, I'm not able to repro this yet.

Here's what I tried:

1. Wrote this to main.cadl in packages/samples/scratch
```
import "@cadl-lang/rest";
import "@cadl-lang/versioning";

using Cadl.Rest;
using Cadl.Http;
using Cadl.Versioning;

@versioned(Versions)
@service({
  title: "Widget Service",
})
namespace DemoService;

enum Versions {
  v1,
  v2,
}

model AllVersions {}

@added(Versions.v2)
model OnlyInV2 {}
```

2. Instrumented openapi emitter to dump all models outside Cadl namespace, for each version
``` diff
--- a/packages/openapi3/src/openapi.ts
+++ b/packages/openapi3/src/openapi.ts
@@ -354,6 +354,15 @@ function createOAPIEmitter(program: Program, options: ResolvedOpenAPI3EmitterOpt
       }

       program = projectProgram(originalProgram, [...commonProjections, ...record.projections]);
+
+      console.log(record.version);
+      for (const namespace of program.getGlobalNamespaceType().namespaces.values()) {
+        if (namespace.name.startsWith("Cadl")) continue;
+        for (const model of namespace.models.values()) {
+          console.log(model.name);
+        }
+      }
+      console.log("---");
       const projectedServiceNs = getServiceNamespace(program);
```

3. In packages/samples/scratch, ran
``` bash
cadl compile . --emit @cadl-lang/openapi3
```

And got this output:

```
v1
AllVersions
---
v2
AllVersions
OnlyInV2
---
```

So, in this case at least, it does appear to me that the `OnlyInV2` model is removed from `v1` via that projectProgram call and not by some other undocumented means.

Do you get this result with my repro steps too? Are you able to similarly reduce your results down to runnable repro steps?

**Comment by tjprescott** [comment]
I set my break point just below `const projectedServiceNs = getServiceNamespace(program);` and inspected the projectedServiceNs in the debugger. The unwanted model was still present. I'll try instrumenting it the way you did and see if I get a different result. Is there some kind of special iterator logic that internally skips things that aren't support vice removing them?

**Comment by nguerrera** [comment]
I'm 99% sure these are just plain old `Map`s being iterated. I see the same thing that my instrumentation shows in debugger. I put the console.logs instead of breakpoints in my repro step purely to make it easier to share and reproduce what I am seeing.

**Comment by nguerrera** [comment]
I suspect at this point there's something different between my Cadl test program and yours.

**Comment by nguerrera** [comment]
Not sure what the deal is with that "atVersion" projection that's added after buildVersionProjections that isn't documented in https://github.com/microsoft/cadl/tree/main/packages/versioning#consuming-versioning-library-from-an-emitter, but commenting it out doesn't impact my repro.

**Comment by tjprescott** [comment]
I still am seeing this. 

I had to modify your logging because the models are in a subnamespace:
```typescript
    for (const record of versions) {
      if (record.version) {
        record.projections.push({
          projectionName: "atVersion",
          arguments: [record.version],
        });
      }

      function logNamespaceModels(ns: Namespace) {
        if (ns.name == "Core" || ns.name == "Foundations" || ns.name.startsWith("Cadl")) return;
        console.log(`\t${ns.name}`);
        for (const model of ns.models.values()) {
          console.log(`\t\t${model.name}`);
        }
        for (const namespace of ns.namespaces.values()) {
          logNamespaceModels(namespace);
        }
      }

      program = projectProgram(originalProgram, [...commonProjections, ...record.projections]);
      console.log(record.version);
      for (const namespace of program.getGlobalNamespaceType().namespaces.values()) {
        logNamespaceModels(namespace);
      }
      console.log("---")
      const projectedServiceNs = getServiceNamespace(program);
```

Here's the definition of `AmazingNewModel` in my ConfidentialLedger spec:
```
@Versioning.added(Versions.v2022_10_25)
@doc("a")
model AmazingNewModel {
  @doc("a")
  name: string;

  @doc("b")
  age: int16;
}
```

And here's the output logging using the modified OpenAPI3 code. You can see that AmazingNewModel appears in all three cases (and yes, it is also weird that 2022-05-25 is run twice but that's because the version enum has a "latest" alias to that...)
-------------
C:\Program Files\nodejs\node.exe .\node_modules\@cadl-lang\compiler\dist\core\cli.js compile E:\repos\azure-rest-api-specs\specification\confidentialledger\ConfidentialLedger --emit="E:\repos\cadl\packages\openapi3"
Cadl compiler v0.36.1
2022-05-23
	Azure
	ConfidentialLedger
		Constitution
		ConsortiumMember
		Enclaves
		EnclaveQuote
		Collection
		LedgerEntry
		CollectionIdParameter
		LedgerQueryResult
		ConfidentialLedgerQueryState
		TransactionReceipt
		ReceiptContents
		ReceiptLeafComponents
		ReceiptElement
		TransactionStatus
		TransactionState
		LedgerUser
		ConfidentialLedgerUserRoleName
		PagedLedgerEntries
		MerkleProofElement
		RoleAssignment
		**AmazingNewModel**
---
2022-10-25
	Azure
	ConfidentialLedger
		Constitution
		ConsortiumMember
		Enclaves
		EnclaveQuote
		Collection
		LedgerEntry
		CollectionIdParameter
		LedgerQueryResult
		ConfidentialLedgerQueryState
		TransactionReceipt
		ReceiptContents
		ReceiptLeafComponents
		ReceiptElement
		TransactionStatus
		TransactionState
		LedgerUser
		ConfidentialLedgerUserRoleName
		PagedLedgerEntries
		MerkleProofElement
		RoleAssignment
		**AmazingNewModel**
---
2022-10-25
	Azure
	ConfidentialLedger
		Constitution
		ConsortiumMember
		Enclaves
		EnclaveQuote
		Collection
		LedgerEntry
		CollectionIdParameter
		LedgerQueryResult
		ConfidentialLedgerQueryState
		TransactionReceipt
		ReceiptContents
		ReceiptLeafComponents
		ReceiptElement
		TransactionStatus
		TransactionState
		LedgerUser
		ConfidentialLedgerUserRoleName
		PagedLedgerEntries
		MerkleProofElement
		RoleAssignment
		**AmazingNewModel**
---
Compilation completed successfully, output files are in E:/repos/cadl/packages/openapi3/cadl-output.

**Comment by tjprescott** [comment]
And when I run it on your cadl with your exact logging, I still see the model on both:
![image](https://user-images.githubusercontent.com/5723682/198067208-7ec65127-d63a-48b7-b58a-5a165aa9c68d.png)

**Comment by tjprescott** [comment]
Troubleshooting with @nguerrera it seems this behavior (not working) happens depending on whether `--emit` is `--emit=@cadl-lang/openapi3` or `--emit={some path to openapi3}`.

**Comment by markcowl** [comment]
est: 5
