### ISSUE TITLE
What is atVersion projection?

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#1233]
These lines are mysterious to me:

https://github.com/microsoft/cadl/blob/aca567cadc9998b5e1fe257887e9a46553fbad14/packages/openapi3/src/openapi.ts#L349-L353

They aren't documented in https://github.com/microsoft/cadl/tree/main/packages/versioning#consuming-versioning-library-from-an-emitter, I can't find another reference to atVersion anywhere, and all tests pass when I comment them out.

**Comment by markcowl** [comment]
@nguerrera @bterlson Please decide on a  disposition for this issue, and either add an estimate, or remove your assignments so we can re-triage

**Comment by nguerrera** [comment]
Options:

1. Delete this code
2. Move the code into buildVersionProjections and add a test for it

**Comment by timotheeguerin** [comment]
Delete it and add back later if we get a use case.

**Comment by timotheeguerin** [comment]
est: 1
