### ISSUE TITLE
Lint-rule: prevent property has same name with the model name

### ISSUE THREAD

**Issue by chunyu3** [microsoft/cadl#1234]
.Net and python cannot support the property has the same name as the model name. see following example:

```
model Message {
  message: string;
}
```

Dotnet will generate as 
```C#
public partial class Message
{
    public string Message { get; set; }
}
```
This leads to error

> error CS0542: 'Message': member names cannot be the same as their enclosing type

Can we add a lint-rule for cadl that it is not allowed to define a property has the same name as the model name?

**Comment by markcowl** [comment]
@chunyu3 Can you please open shis in the cadl-azure repo?  https://github.com/Azure/cadl-azure/issues

**Comment by markcowl** [comment]
Closign as duplicate of: https://github.com/Azure/cadl-azure/issues/2185
