### ISSUE TITLE
consider adding an option for generating only latest version 

### ISSUE THREAD

**Issue by jianyexi** [microsoft/cadl#1235]
Generating the latest version may be useful for many cases, like doc generation team may only want to refresh the latest version

**Comment by markcowl** [comment]
@jianyexi Has there been an ask from the docs team about this?  Is there a reason why they can't simply use the latest version spec that is part of normal, versioned generation (is there some ambiguity about what is latest?)

**Comment by live1206** [comment]
@markcowl 
The main requirement from service team is to publish the latest version of swagger files to docs site.
Right now, a cadl file could define multiple versions, and cadl compile will generate all versions of swagger files.
There is no way for docs team to know what the latest version is.

**Comment by timotheeguerin** [comment]
> @markcowl The main requirement from service team is to publish the latest version of swagger files to docs site. In the future, the swagger files will not be included in the spec repo any more for Cadl. A cadl file could define multiple versions, and cadl compile will generate all versions of swagger files. There is no way for docs team to know what the latest version is.

Are you always planning to generate the docs from the swagger? When making your own emitter when listing the version they are in order.

**Comment by markcowl** [comment]
@live1206  If they are generating docs from swagger, then the emitted swagger will be in the same directory structure as it is now.   If they are generating from Cadl, then we will have a docs emitter from Cadl.  Either way, being able to emit a single version doesn't seem to be a blocker.

**Comment by markcowl** [comment]
This option was added to the cadl-autorest emitter.  Closing
