### ISSUE TITLE
Remove `findStatementsIn` API

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1239]
`findStatementsIn` works in this scenario:
```
namespace Foo {
  model Bar {};
  alias Cool = Bar;
}
```

But it does not work in this scenario:
```
namespace Foo;

model Bar {};

alias Cool = Bar;
```

This is problematic since the second scenario is what we showcase heavily, and this still leaves me unable to get to alias statements and, it seems, augment decorators.

It would work if I'm compile an entire cadl file and run it on the `CadlScriptNode`, but at that point, I'm rewriting all of APIView to use AST.

**Comment by markcowl** [comment]
- this is essentially by design for findStaementsIn
- should use other statement enumeration mechanisms
- remove findStatementsIn
- file an issue for changing tyhe api surface to make this easier

**Comment by markcowl** [comment]
- remove and document in breaking changes
