### ISSUE TITLE
`@Versioning.madeOptional` should validate that a model target property is indeed optional in the version it says it was made optional

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#1240]
In the following spec, I would expect an error on the madeOptional since the model property is not optional in the version (v2) it makes the bold statement it having been made optional in.

```cadl
import "@cadl-lang/versioning";

@Versioning.versioned(Versions)
namespace Something;

enum Versions {
  v1,
  v2
}

model X {
  @Versioning.madeOptional(Versions.v2)
  thisIsRequired: string;
}
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3ZlcnNpb25pbmciOwoKQFbJDy7HGmVkKMcVcykKbmFtZXNwYWNlIFNvbWV0aGluZzsKCmVudW0gyCUgewogIHYxLMQGMgp9Cgptb2RlbCBYxRjMYG1hZGVPcHRpb25hbMljLnYyKQogIHRoaXNJc1JlcXVpcmVkOiBzdHLFa30%3D)

**Comment by markcowl** [comment]
est: 3
