### ISSUE TITLE
`@renamedFrom` allows empty or no property name argument

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#1243]
https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5WyRk7CgpAxydlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERiJ2MSIsxQgyxDvtAJFIdHRwO8wRUmVzdDsKCm1vZGVsIMd4xEVAa2V5IGlkOiBzdHLlAL8gIHdlaWdodDogaW50MzLEEWNvbG9yzCJAcmXkAKdkRnJvbekA5C52Mikgc2hhZGXKK30KCkBlcnJvcsd5RcQMxXhjb8QoyWNtZXNzYWfOOmludGVyZuQBCuYAsOcBDCBleHRlbmRzIFJlc291cmNl5ADcxQlPcGVyYXTkAIw8xjIsxnE%2BxXJAYWRk6wGT5ACvxBZnZXTEB3JvdXRlKCJjdXN0b21HZXQixB3JDigpOucAheQAmg%3D%3D

**Comment by markcowl** [comment]
est: 2
