### ISSUE TITLE
Augmenting a versioned dependency with versioning decorators don't work

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#1247]
The augment (@@) decorator on line 37 should have removed the client request id from the emitted output. It doesn't. If I put the decorator explicitly on the requestId (line 18), it does work. The two should be equivalent.

```cadl
import "@cadl-lang/rest";
import "@cadl-lang/versioning";

using Cadl.Http;
@Cadl.Versioning.versioned(CoreVersions)
namespace Core {

  enum CoreVersions {
    always
  }

  model ServiceTraits {
    ... ClientRequestId;
    ... ConditionalRequests;
  };

  model ClientRequestId {
    @header("x-ms-client-request-id") requestId?: string;  // <- Line 18
  }

  model ConditionalRequests {
    @header("If-Match") ifMatch?: string;
  }
}

@Cadl.Versioning.versioned(ServiceApiVersions)
@Cadl.Versioning.versionedDependency([[ServiceApiVersions.v1, Core.CoreVersions.always]])
  @service({ title: "Goofing around" })
namespace Service {

  enum ServiceApiVersions {
    v1,
    v2,
    v3
  };

  @@Versioning.removed(Core.ClientRequestId.requestId, Core.CoreVersions.always) // <- Line 37

  op doStuff(... Core.ServiceTraits): string;
}
```
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5IdHRwOwpAxQxWySUuxzBlZChDb3JlxxlzKQpuYW1lc3BhY2UgxBggewoKICBlbnVtxQ%2FIJyB7CiAgICBhbHdheXMKICB9xCZtb2RlbCBTZXJ2aWNlVHJhaXTIKC4uLiBDbGllbnRSZXF1ZXN0SWQ7yhlvbmRpdGlvbmFsxx5zxB19O8pUzzzHVkBoZWFkZXIoIngtbXMtY8UkLXLGJS1pZCIpIMcNSWQ%2FOiBzdHJpbmfFWstZ0nzQXUlmLU1hdGNoIikgaWbFCs9NfQr8AV3nAQ9BcGnHH3Mp2y9EZXBlbmRlbmN5KFtb0jsudjEs5QGILuwBjS7mAYddXSkKICBAc8Y2KHsgdGl0bGU6ICJHb29m5AIOYXJvdW5kIiB97AHlx2XrAejSd%2BcBE3YxLMYIMscIM%2BkBp0BA6wDOcmVtb3bnAlgu7wG7LukBk%2FoAySnEUm9wIGRvU3R1ZmYo5gIlcmUu7QJbKeoBhn0%3D)

**Comment by timotheeguerin** [comment]
Slightly simplified repro. Think the problem comes from the fact that augment decorator on late bound property are run after the type is created so in this case after the core namespace has been created and ServiceTrait already has been resolved without the decorator.

```cadl
import "@cadl-lang/rest";
import "@cadl-lang/versioning";

using Cadl.Http;
@Cadl.Versioning.versioned(CoreVersions)
namespace Core {
  enum CoreVersions {
    core1, core2,
  }

  model ServiceTraits {
    ...ClientRequestId;
  }

  model ClientRequestId {
    @header("x-ms-client-request-id") requestId?: string;
  }

}

@Cadl.Versioning.versioned(ServiceApiVersions)
@Cadl.Versioning.versionedDependency([
  [ServiceApiVersions.v1, Core.CoreVersions.core2],
  [ServiceApiVersions.v2, Core.CoreVersions.core2]
])
@service
namespace Service {
  enum ServiceApiVersions {
    v1,
    v2,
  }

  @@Versioning.removed(Core.ClientRequestId.requestId,
    Core.CoreVersions.core2
  );

  op doStuff(...Core.ServiceTraits): string;
}

```
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5IdHRwOwpAxQxWySUuxzBlZChDb3JlxxlzKQpuYW1lc3BhY2UgxBggewogIGVudW3FDsgmxRYgIGNvcmUxLMUHMiwKICB9CgogIG1vZGVsIFNlcnZpY2VUcmFpdMgvLi4uQ2xpZW50UmVxdWVzdElkO841zx7HN0BoZWFkZXIoIngtbXMtY8UkLXLGJS1pZCIpIMcNSWQ/OiBzdHJpbmfHWX0K/AD45wCkQXBpxx9zKdsvRGVwZW5kZW5jeShbCiAgW9I+LnYxLOUBJy7sASwu5QEfXeQBINU0Mto0Cl0pCkBzxjTrAZjHRuoBm9JXxRwgIHYxxHcgIHbqAZ9AQOsA3XJlbW925wIC8AGcLukBVsZE9wClCiAgKTvEWW9wIGRvU3R1ZmYo5AHpxC7tAgUp6gGcfQo%3D)

**Comment by timotheeguerin** [comment]
Simpler problem outside of projection scope

```cadl
import "@cadl-lang/rest";
import "@cadl-lang/versioning";

using Cadl.Http;
namespace Core {
  model ServiceTraits {
    ...ClientRequestId;
  }

  model ClientRequestId {
    @header("x-ms-client-request-id") requestId?: string;
  }
}

@service
namespace Service {
  @@doc(Core.ClientRequestId.requestId, "request id post doc");

  op doStuff(...Core.ServiceTraits): string;
}

```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwpuYW1lc3BhY2UgQ29yZSB7CiAgbW9kZWwgU2VydmljZVRyYWl0c8UYICAuLi5DbGllbnRSZXF1ZXN0SWQ7CiAgfQrJNc8exzdAaGVhZGVyKCJ4LW1zLWPFJC1yxiUtaWQiKSDHDUlkPzogc3RyaW5nxll9CgpAc%2BYAiesAqucAm8VeQEBkb2Mo5AC88ACbLslVLCAixwwgaWQgcG9zdCBkb2MiKTvkALlvcCBkb1N0dWZmKOQA38RJ7QD7KeoAkn0K)
