### ISSUE TITLE
Completion on instantiated interfaces doesn't work

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#1249]
Note how you get no completions on FooT.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIEZvbzxUPiB7DQogIG9wIEJhcigpOiB2b2lkOw0KfQ0KDQphbGlhc8QoVCA9xS9zdHJpbmc%2BO8gbQmFyVcYbVC47xDI%3D)

**Comment by markcowl** [comment]
est: 5

**Comment by nguerrera** [comment]
Fix in PR
