### ISSUE TITLE
Allow operation templates in interfaces

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#1250]
I couldn't find a bug for this but I believe the following should work.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIEZvbzxUPiB7DQogIG9wIEJhcjxVPih4OiBUKTogVTsNCn0NCg0KYWxpYXPELFQgPcUzc3RyaW5nPjvIG0JhclXGG1QuxERudW1iZXI%2BOw%3D%3D)

**Comment by markcowl** [comment]
pri: 0

**Comment by daviwil** [comment]
# Interface-Templated Operation Signatures

We propose that it should be possible to define operation signatures within templated interface to achieve higher-order abstractions for Cadl libraries.

A simple example:

```
interface Foo<T> {
  op Bar<U>(x: T): U;
}

interface ConcreteFoo extends Foo<string> {}

op myBar is ConcreteFoo.Bar<int32>;
```

This enables the parameter type to be customized at the interface level while the response type is customized at the operation level.  Extending from the templated interface effectively allows you to partially apply customizations across all of the operations it contains so that they can be picked out and used as operation signatures elsewhere in the Cadl document.

## Azure.Core Use Case

This feature would be very useful for enabling "service traits" for the Azure Core library.  With it, we could define an interface containing all standard resource lifecycle operations such that all service traits could be applied at the interface level, leaving the door open for further customization of individual operations.

Here's how this could look in practice:

```cadl
namespace Azure.Core.Foundations {
  interface ResourceOperations<TParams, TResponse> {
    op ResourceRead<
      TResource extends object,
      TCustom extends Foundations.CustomizationFields = {}
    > is Foundations.ResourceOperation<
      TResource,
      TParams & Foundations.CustomParameters<TCustom>,
      TResource & TResponse & Foundations.CustomResponseFields<TCustom>
    >;

    op ResourceCreateOrUpdate<
      TResource extends object,
      TCustom extends Foundations.CustomizationFields = {}
    > is Foundations.ResourceOperation<
      TResource,
      {
        @doc("This request has a JSON Merge Patch body.")
        @Cadl.Http.header("Content-Type")
        contentType: "application/merge-patch+json";
        ...Foundations.Body<TResource>;
        ...TParams;
        ...Foundations.CustomParameters<TCustom>;
      },
      Foundations.ResourceCreatedOrOkResponse<TResource & TResponse & Foundations.CustomResponseFields<TCustom>>
    >;

    @action
    @autoRoute
    @actionSeparator(":")
    op ResourceAction<
      TResource extends object,
      TActionParams, 
      TActionResponse
    > is Foundations.ResourceOperation<
      TResource,
      TParams & TActionParams,
      TResponse & TActionResponse
    >;
  }
}

namespace Azure.Core {
  // Provide a standard version of this interface when no service traits are needed.
  interface ResourceOperations extends Foundations.ResourceOperations<{}, {}> {}

  // We can also provide the standard operation shapes in a backwards compatible way, if desired
  op ResourceRead<TResource, TCustom> is ResourceOperations.ResourceRead<TResource, TCustom>;
}
```

A service author could then use the templated interface like so:

```
namespace Contoso.WidgetManager {
  model EtagMixin {
    @header("ETag")
    etag: string;
  }

  model CustomResponseHeader {
    @header("x-ms-something")
    somethingHeader: string;
  }

  interface WMResourceOperations extends Azure.Core.ResourceOperations<{}, ETagMixin> {}

  interface Widgets {
    op readWidget is WMResourceOperations.ResourceRead<Widget, { response: CustomResponseHeader }>;
    op createOrUpdateWidget is WMResourceOperations.ResourceCreateOrUpdate<Widget>;
    op agitateWidget is WMResourceOperations.ResourceAction<Widget, { @query times: int32; }, Widget>;
  }
}
```

**NOTE:** It's possible that we may need to add more template parameters to the core `ResourceOperations` interface to be more explicit about customization points.  Alternatively, we could use a `TCustom`-like design to make the service trait extension points clearer, including adding extensions for specific operation types (read, create, etc).

## How It's Implemented

To implement this feature, we would need to do the following:

- Remove the restriction that prevents templated operations from being defined in an interface
- Update the interface template instantiation code to produce partially-instantiated operation signatures
- Ensure that existing code which looks at operations defined in interfaces takes this new possibility into account

  For example, route-scanning logic in the `@cadl-lang/rest` library would need to ignore any templated operations in a concrete interface definition, they should not be used for HTTP routes.

**Comment by timotheeguerin** [comment]
Issues to solve: what do we do about partial instance

## Different case about templated interface

### Case 1: Interface and operation are templates

```cadl
interface Foo<T> {
  @route("/bar") op bar<U>(x: T): U;
} 

interface MyFoo extends Foo<string> {} // No routes produces as `MyFoo.bar` is still a template declaration.

op myBar is MyFoo.bar<abc>; // /bar
```

### Case 2: Interface has a mix of template and fixed operation

```cadl
interface Foo {
  @route("/ping") op ping(): void
  @route("/bar") op bar<U>(): U;
} 

// Would this produce `/ping` or nothing
```

### Case 3 Templated interface resolve to some templated operation and some instance ones
```cadl
interface Foo<T> {
  @route("/ping") op ping(v: T): void;
  @route("/bar") op bar<U>(v: T): U;
} 

interface MyFoo extends Foo<string> {} // `MyFoo` becomes the same scenario as case 2, so would assume they are consistent between each other.
```

## How do we check something is a template instance vs template declaration

Before it was simple, either its a template or a template instance(has template arguments) but now we have this hybrid where an operation could be a template instance of an interface but still be a template declaration.

Do we qualify anything that is not fully instantiated as a template declaration still? Or is there any value in exposing this intermediate state.

**Comment by bterlson** [comment]
My opinion: whether something is an instantiation or a template should depend only on local information, we shouldn't muck about looking inside an interface to see if the interface itself is a template. This makes sense both from a simplicity standpoint, and an alignment with namespaces, which don't become templates even though they may contain templates.

In particular:

Case 1: 100% agreed on your comments
Case 2: IMO: just have ping (because bar is not instantiated).
Case 3: IMO: it's just case 2 again just have ping.

**Comment by timotheeguerin** [comment]
# Proposal

Allow operations inside of interface to be templated.

When instantiating an interface we would resolve the interface tempalate parameters used in all the operations. A templated operation would then remain a template declaration until it is in turn instantiated.

## Use case examples

Note: The `@route` are just for representation and examples show which routes are included as a way of seeing which operation are representing the service.

### (Baseline) Case 1: Templated interface

Establishing current behavior

```cadl
interface Ops<T> {
  @route("a") a(): T;
  @route("b") b(): T;
}
```

Extending the interface result in the operation to be instantiated and get included in the output

```cadl
interface MyOps extends Ops<string> {}

// Resulting routes:
// /a
// /b
```

Using an alias to instantiate the interface doesn't create any route

```cadl
alias MyOps = Ops<string> {}

// No resulting routes
```

But that alias can then be used to include the operation as different names

```cadl
alias MyOps = Ops<string> {}

op myA is MyOps.a;

// Resulting routes:
// /a
```

## Case 2: Templated interface with only templated operations

```cadl
interface Ops<T> {
  @route("a") a<A>(data: A): T;
  @route("b") b<B>(data: B): T;
}
```

Extending or alias the interface result in no operation being included as each operation is also templated

```cadl
interface MyOps extends Ops<string> {}
// or
alias MyOps = Ops<string>;

// Resulting in no routes
```

But then the interface can be used as a building block to instantiate the operations

```cadl
interface MyOps extends Ops<string> {}
// or
alias MyOps = Ops<string>;

op myA is MyOps.a<string>;
op myB is MyOps.b<int32>;

// Resulting in routes:
// /a
// /b
```

## Case 3: Templated interface with only some tempalated operations

```cadl
interface Ops<T> {
  @route("a") a(): T;
  @route("b") b<B>(data: B): T;
}
```

Extending the interface would mean that the non templated operation are not included in the service represenation

```cadl
interface MyOps extends Ops<string> {}

// Resulting routes:
// /a
```

`op is` can be used to include the other operations

```cadl
interface MyOps extends Ops<string> {}

// op myA  is MyOps.a; // adding this line would cause a duplicate route issue as MyOps.a is already included ^
op myB  is MyOps.b<int32>;

// Resulting routes:
// /a
// /b
```

Alternatively if this interface is meant to be used as a building block we can use an alias

```cadl
alias MyOps = Ops<string>;

op myA  is MyOps.a; // Now we can include this
op myB  is MyOps.b<int32>;

// Resulting routes:
// /a
// /b
```

## Internal changes

- `isTemplateInstance` would check if a template is fully instantiated(operation template wouldn't count as template instance if only the interface is instantiated)

```cadl
interface Foo {
  bar(): void; // Instance
}

interface Ops<T> {
  a(): T;  // Not instance
  b<B>(data: B): T; // Not instance
}


interface MyOps  extends Ops {
  // a => instance
  // b => not instance
}

op myB is MyOps.B; // Instance

```

**Comment by timotheeguerin** [comment]
interface OpFactory<T> {
  none(): T;
  a<A>(u: A): T;
  b<B>(u: B): T;
}

// Use `extends` to build extended factory
interface MyOpFactory<T> extends OpFactory<T> {
  c<C>(u: C): T;
}

// Use alias to instantiate building blocks
alias MyBuildingBlock = MyOpFactory<string>;

// Misuse? Could we emit a warning if extends an 
// interface that has tempalted operations 
// but not defining extra templates? 
interface TryInstance extends OpFactory<string> {}


interface MyEndpoints {
  a is MyBuildingBlock.a<string>;
  b is MyBuildingBlock.b<int32>;
  c is MyBuildingBlock.c<int64>;
}

// No shadowing of template params
interface Foo<T> {
  bar<T>(): T;
  //  ^-- error shadowing T in Foo
}

**Comment by timotheeguerin** [comment]
implementation issue #1389
