### ISSUE TITLE
Rename Uri type to url and update handling of urls in path and query parameters

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1251]
Implementation issue for: https://github.com/microsoft/cadl/issues/851

- [ ] Rename uri -> url
- [ ] Document usage of url using the spec: https://url.spec.whatwg.org/#relative-url-string

**Comment by markcowl** [comment]
est: 3

**Comment by timotheeguerin** [comment]
Do we want this non breaking? `alias uri = url`

**Comment by timotheeguerin** [comment]
@markcowl do we also want to change the format from `uri` to `url` then?
