### ISSUE TITLE
[Code Generation Issue] Custom action endpoint models not auto generated

### ISSUE THREAD

**Issue by lavinir** [microsoft/cadl#1268]
Seems the ProviderHub code generation is omitting models which are not resources (e.g. custom action endpoints (post requests)).

For example, for the following definition, no models will be generated for **CustomActionRequest** or **CustomActionResponse**

```
@armResourceOperations
interface Resource1
	extends ResourceOperations<
			Resource1,
			Resource1Properties
		> {
	@post
	@segment("customAction")
	op CustomAction(
		...ResourceInstanceParameters<Resource1>,
		@body parameters: CustomActionRequest
	): ArmResponse<CustomActionResponse> | ErrorResponse;
}
```

**Comment by markcowl** [comment]
@lavinir to add these to generation, you need to make sure the operation is decorated with `@armResourceAction`, for example:

``` cadl
@armResourceOperations
interface Resource1
	extends ResourceOperations<
			Resource1,
			Resource1Properties
		> {
	@post
	@segment("customAction")
        @armResourceAction(Resource1)
	op CustomAction(
		...ResourceInstanceParameters<Resource1>,
		@body parameters: CustomActionRequest
	): ArmResponse<CustomActionResponse> | ErrorResponse;
}
```

In the next release, operations that don't have this decoration will emit a diagnostic, asking you to add it.

**Comment by lavinir** [comment]
Thanks @markcowl ! 
Might also be useful to add this to the documentation / sample [here](https://github.com/Azure/cadl-azure/blob/main/packages/cadl-azure-resource-manager/README.md#generating-an-openapi-specification)
