### ISSUE TITLE
Pin all packages version together

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1270]
Considering if we should pin all the cadl-lang packages version to be together. That would simplify greatly managing cadl dependencies.
- `@cadl-lang/compiler`: `1.2.3`
- `@cadl-lang/rest`: `1.2.3`
- `@cadl-lang/openapi3`: `1.2.3`

This is a common pattern for some libraries that are spread across many packages:
- `@docusaurus`
- `@angular`
- `react` and `react-dom`
- `playwright`

Pro: 
- Very easy to upgrade packages. Just upgrade all together to the same version.
- Would be more obvious that you have dependency mismatch

Cons:
- Could release other packages to a new version even though there is no changes
- Not respecting semver on a per package basis

**Comment by markcowl** [comment]
CLosed for implementation issues: https://github.com/microsoft/cadl/issues/1366, https://github.com/Azure/cadl-azure/issues/2331
