### ISSUE TITLE
scalar type implementation

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1272]
## Create a new `scalar` type

Declared with `scalar`
Can `extends` another scalar

## Move intrinsic model types 
To scalar: 
```cadl
model bytes {}
model numeric {}
model integer {}
model float {}
model int64 {}
model int32 {}
model int16 {}
model int8 {}
model uint64 {}
model uint32 {}
model uint16 {}
model uint8 {}
model safeint {}
model float32 {}
model float64 {}
model string {}
model plainDate {}
model plainTime {}
model zonedDateTime {}
model duration {}
model boolean {}
```

As a compiler intrinsic type like `void` and `never`
```
model null {}
```

Items: 
- [ ] scalar type
- [ ] convert intrinsic types
- [ ] add tests
- [ ] make a migration tool

**Comment by markcowl** [comment]
est: 13
