### ISSUE TITLE
@Cadl.Rest.segmentSeparator doesn't work with `Azure.Core.ResourceCollectionAction`

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#1282]
...and it mostly but doesn't fully work with ResourceAction...

```cadl
import "@azure-tools/cadl-azure-core";

@Cadl.Rest.resource("whocareses")
model WhoCares {
  @key
  id: string
}

@Cadl.Rest.segmentSeparator("x")
op almostWorks is Azure.Core.ResourceAction<WhoCares, {}, {}>; // <-- produces a /whocareses/{id}/xalmostWorks route. The slash in front of the 'x' is questionable....

@Cadl.Rest.segmentSeparator("/")
op works is Azure.Core.ResourceAction<WhoCares, {}, {}>; // <-- produces a whocareses/{id}/works route

@Cadl.Rest.segmentSeparator("/")
op doesntWork is Azure.Core.ResourceCollectionAction<WhoCares, {}, {}>; // <-- produces a /whocareses:doesntWork route. Not what I would expect...
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvY2FkbC3GEWNvcmUiOwoKQENhZGwuUmVzdC5yZXNvdXJjZSgid2hvY2FyZXNlcyIpCm1vZGVsIFdob0PEEyB7CiAgQGtleQogIGlkOiBzdHJpbmcKfc1Kc2VnbWVudFNlcGFyYXRvcigieCIpCm9wIGFsbW9zdFdvcmtzIGlzIEHkAIsuQ29yZcQ4xX1BY3Rpb248yG8sIHt9xAQ%2B7gCr0mEvxmF331vfW9xbZG9lc27lALzXYENvbGxlxWTbag%3D%3D)

**Comment by markcowl** [comment]
est: 3

**Comment by tjprescott** [comment]
@johanste in the case of `segmentSeparator("x")` there is logic that says the only allowed separators are / and : and thus if the segment doesn't start with one of those, it appends /.  I could change that logic, but would it make more sense to prevent anything but / or : as allowed values for segmentSeparator. Thoughts?

**Comment by johanste** [comment]
I don't think that appending '/' is the right thing to do (not sure when I'd ever use that). I know that some services use a '+' or ',' in some cases (not Azure). At least one Azure service has (tried to use) '.'. If we want to restrict, we can restrict (and error out if it is not one of our approved ones), but appending '/' is not right. We may want to special-case empty string.

**Comment by tjprescott** [comment]
@daviwil @johanste so, the problem with ResourceCollectionAction is the order in which things get evaluated:

1. `@segmentSeparator(":")` on `ResourceCollectionAction`
2. `@collectionAction` on `ResourceCollectionAction`
3. `@segmentSeparator("/")` on `Foo is ResourceCollectionAction`

By adding `@collectionAction(WhoCares)` to `doesntWork` it then _does_ work, but it doesn't seem like it will be easy to fix this.

**Comment by johanste** [comment]
It sounds like a premature application of a decorator where last-in-should-win (I think).

**Comment by tjprescott** [comment]
@markcowl after looking into this and discussing with David and Johan, this is no longer est: 3. It's probably more like est: 8-13.
