### ISSUE TITLE
[Code generation issue] CADL compiler 0.37 generates `"modelAsString": false` objects for extensible enums

### ISSUE THREAD

**Issue by jaimeva-msft** [microsoft/cadl#1285]
I have a cadl definition making use of the following pattern described at https://microsoft.github.io/cadl/standard-library/built-in-decorators#knownvalues (example pulled from that link):

```
// cadl
enum OperationStateValues {
  Running,
  Completed,
  Failed,
}

@knownValues(OperationStateValues)
model OperationState is string;
```

With cadl compiler 0.35, this produced the following openapi output:
```
    "OperationState": {
      "type": "string",
      "enum": [
        "Running",
        "Completed",
        "Failed"
      ],
      "x-ms-enum": {
        "name": "OperationState",
        "modelAsString": true
      }
    },
```

This now produces the following openapi output:
```json
    "OperationState": {
      "type": "string",
      "enum": [
        "Running",
        "Completed",
        "Failed"
      ],
      "x-ms-enum": {
        "name": "OperationState",
        "modelAsString": true
      }
    },
    "OperationStateValues": {
      "type": "string",
      "enum": [
        "Running",
        "Completed",
        "Failed"
      ],
      "x-ms-enum": {
        "name": "OperationStateValues",
        "modelAsString": false
      }
    },
```

This means my generated swagger is now susceptible to unintended breaking changes if a downstream consumer uses the `OperationStateValues` object, since I've got a `"modelAsString": false` enum that I'm going to want to add entries to.

I couldn't see anything in the changelog suggesting a change this behaviour.

In reproducing this I realised `OperationState` is _also_ elided in 0.35 if it's not referenced - but similarly appears in 0.37 - perhaps this is a wider regression in how objects get elided from the output openapi spec?

**Comment by timotheeguerin** [comment]
This is an expected output. We changed to include all the models defined in the Cadl by default. You can use `omit-unreachable-types` options for the `openapi3` or `cadl-autorest` emitters https://microsoft.github.io/cadl/standard-library/openapi#omit-unreachable-types to only include referenced types.

**Comment by jaimeva-msft** [comment]
Thanks @timotheeguerin - is there a changelog entry or something I can reference for that change?

**Comment by jaimeva-msft** [comment]
Thanks! I hadn't thought to check the openapi3 changelog (still getting the hang of the cadl tooling!)
