### ISSUE TITLE
Allow custom target projection code

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#1286]
Right now, you cannot define your own serialization for a particular target using projection code as we have a default projection to implement the `@projectedName` decorator.

**Comment by timotheeguerin** [comment]
This this just coming as part of finding solution to this https://github.com/microsoft/cadl/issues/1131

**Comment by timotheeguerin** [comment]
Yeah I think this is due to using the same projection name in the same namespace with the same selector. Something we should be able to solve in #1131
