### ISSUE TITLE
Better error message for referencing properties declared later

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1288]
Per #804 
Currently the message is: `error invalid-ref Interface doesn't have member 'one'`

Should change to: `error invalid-ref could not find interface member 'one'.  This could occur if the member does not exist, or the reference occurs before the member declaration`

**Comment by markcowl** [comment]
est: 1

**Comment by timotheeguerin** [comment]
Closing as those are now supported in the checker. There is still an issue with projections tracked here https://github.com/microsoft/cadl/issues/1289
