### ISSUE TITLE
Investigate: Allow references within interfaces and models to members defined subsequently

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1289]
Investigate implementation for #804 

Core Piece of this: 
- investigate having more ahead of time symbol resolution for member types

Considerations
- Consider impact on predictable member ordering #948 
- Consider impact on decorator execution

**Comment by timotheeguerin** [comment]
Timebox: 21

**Comment by timotheeguerin** [comment]
This is fixed in the check here #1431 but it still has some issues with projections
