### ISSUE TITLE
Specify the deprecation story timeline

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1290]
We have quite a few deprecated items right now that we haven't removed. It would be good that we define how long should something be deprecated before we remove it. 
- 1 release
- 2 release
- 3 release

**Comment by allenjzhang** [comment]
One release seems too short given some of the service teams' life cycle varies widely. This also depends on our Cadl release cycle length as well. Let's pick 3 to be on the conservative side.

**Comment by markcowl** [comment]
Current phase:
- 2 release cycles:  deprecated things are removed after 2 release cycles.
- currently deprecated items: 2 release cycles [removed in February]

After March release:
- deprecation is severely limited

**Comment by markcowl** [comment]
- add work item for reviewing deprecated items for announcement
- add item for removing deprecated items in release

**Comment by markcowl** [comment]
Closing for https://github.com/Azure/cadl-azure/issues/2321
