### ISSUE TITLE
Add support for enum default

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#130]
```cadl
model A {
  optionalEnum?: OptionalEnum = OptionalEnum.foo;
}

enum OptionalEnum {
  foo = "foo",
  bar,
}
```

See PR for initial implementation and issues https://github.com/microsoft/cadl/pull/128

**Comment by markcowl** [comment]
Per discussion, the reference to an enum member returns the enum member, not just the value

**Comment by markcowl** [comment]
https://github.com/Azure/cadl-azure/issues/1096  is a related item
