### ISSUE TITLE
Location bug for diagnostics target being `operation.parameters` when declared with `op is` across files

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1318]
main.cadl

```
import "@cadl-lang/rest";
import "./lib.cadl";

using Cadl.Http;

op nobody is Action<{
  @header eTag: string;
}>;

model Bar {}
```

lib.cadl

```cadl
op Action<T>(@Cadl.Http.header("Content-Type") contentType: "application/json", ...T): void;

```

Error shows in teh complete wrong location
<img width="956" alt="image" src="https://user-images.githubusercontent.com/1031227/204366252-98d004c2-8682-4560-9218-3d1c1215d303.png">

This is due to `op is` in the checker copying the node from the other operaiton but changing the parent 

```
parameters = cloneType(baseOperation.parameters);
parameters.node = parameters.node ? { ...parameters.node, parent: node } : undefined;
```

**Comment by nguerrera** [comment]
Aha, nice catch

**Comment by timotheeguerin** [comment]
I think we could just remove that node reassignment.
