### ISSUE TITLE
Remove Cadl. namespace prefix from signatures in IDE features

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#1349]

**Comment by markcowl** [comment]
This is just for types in the Cadl namespace

**Comment by markcowl** [comment]
closed, as will happen as part of renaming

**Comment by nguerrera** [comment]
@markcowl Just to make sure we're on the same page, this issue would still want to strip the new namespace to make the IDE signatures shorter. Feels very separate from renaming to me.
