### ISSUE TITLE
Document how @knownValues decorator affects output of OpenAPI emitter

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#1370]
@timotheeguerin mentioned today that the OpenAPI emitter uses the `@knownValues` decorator. If this is accurate (it looks like it is from a quick look at the code), how it is used / what effect it has on the output should be described in the documentation for the OpenAPI emitter.

**Comment by markcowl** [comment]
Closing as duplicate of #1371.

@mikekistler Let me know if you think we need to resolve this sooner, and please put any notes on this in the linked issue.
