### ISSUE TITLE
@renamedFrom doesn't work correctly with @removed

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1372]
From @johanste 

 https://cadlplayground.z22.web.core.windows.net/prs/1361/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3ZlcnNpb25pbmciOwoKCkBzZXJ2aWNlKHsgdGl0bGU6ICJKb2hhbiB3YXMgaGVyZSEiIH0pCkBWyTcux0JlZChBcGnHGHMpCm5hbWVzcGFjZSBIZWxsb8gZOwoKZW51bSDLLCB7CiAgdjEsxAYyxQYzCn0KCm1vZGVsIFRoZVRoaW5nIHsKCiAgzHhyZcRjZEZyb23Mei52MiwgImNyZWF0ZWQiKdE1bW927gCrLnYyxCZfxzM6IHN0cmluZzvQcGFkZNU5yTh65AEFRGF0ZVRpbWXRP21hZGVPcHRpb25hbNNGZGVzY3JpxSA%2F6gCDfQoKb3AgYW5PcGVyYcQcKCk66QETOw%3D%3D

This is modeling the scenario where the type of a property changes. We should get:
- v1: created: string
- v2: created: zonedDateTime
- v3: created: zonedDateTime

**Comment by tjprescott** [comment]
@markcowl I think this probably needs a design issue. cc/ @timotheeguerin

**Comment by tjprescott** [comment]
So, if we change the ordering here, it works, which is somewhat disconcerting:
**Works**
```
model Test {
    @renamedFrom(Versions.v2, "created")
    @removed(Versions.v2)
    _created: string;
  
    @added(Versions.v2)
    created: zonedDateTime;
  }
```

**Doesn't Work**
```
model Test {  
    @added(Versions.v2)
    created: zonedDateTime;

    @renamedFrom(Versions.v2, "created")
    @removed(Versions.v2)
    _created: string;
  }
```

The reason this works is simple. For v1:
- sees that `created` applies to v2 and deletes it
- sees that `_created` exists on v1 and adds it
- renames `_created` to `created`

**Comment by johanste** [comment]
Given that the decorator is applied to (in this case) an attribute, it is very surprising/misleading that it looks up by name rather than staying applied to the instance.
