### ISSUE TITLE
Implementation: Operation temaplate inside of operation

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1389]
from: #1250 

```cadl
interface OpFactory<T> {
  none(): T;
  a<A>(u: A): T;
  b<B>(u: B): T;
}
```

Changes: 
- Allow operation inside of interface
- No shadowing of template params
```cadl
interface Foo<T> {
  bar<T>(): T;
  //  ^-- error shadowing T in Foo
}
```
- write docs and recommened usage of interface factory
- describe breaking change of `tempalateArguments` in api

**Comment by markcowl** [comment]
est: 13
