### ISSUE TITLE
Query parameter with a type being a model property crash openapi3 emitter

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1391]
```cadl
import "@cadl-lang/rest";

using Cadl.Http;

op foo(@query id: UserContext.id): void;

model UserContext {
  id: string;
}
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKb3AgZm9vKEBxdWVyeSBpZDogVXNlckNvbnRleHQuaWQpOiB2b2lkOwoKbW9kZWzMHiB7CiDFMnN0cmluZzsKfQ%3D%3D)

**Comment by markcowl** [comment]
- fix in openapi3
- check and fix in cadl-autorest

**Comment by tjprescott** [comment]
Yes, this bug exists in cadl-autorest as well, though not as ugly. The source of both bugs is inadequate type annotations in the code. Another example of why https://github.com/microsoft/cadl/issues/1563 would be good.
