### ISSUE TITLE
Clarify second parameter of @doc and fix how it works with template parameters

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#1393]
There are really two issues here but I'm clubbing them together since they are related:

## Clarify the description of the second parameter of `@doc`

Here's the current description:
> Syntax:
>
> ```@doc(text [, object])```
>
> @doc attaches a documentation string. Works great with multi-line string literals.
>
> The first argument to @doc is a string, which may contain template parameters, enclosed in braces, which are replaced with an attribute for the type (commonly "name") passed as the second (optional) argument.

This is unclear/confusing because the decorator syntax shows the second parameter as an `object`, but the description says that the second parameter is a "type". The easy fix here is to just change "object" to "type" in the syntax block.

It would probably help to give an example here. Another improvement would be to list what other "attributes" could be used here.

## Fix how second parameter of @doc works with template parameters

It looks like @doc does not correctly handle a template parameter passed as the second parameter.

That is, this works:
```
@doc("Return a {name}", Widget)
op works(): Widget | Error; 
```

It produces:
```
    "/": {
      "get": {
        "operationId": "works",
        "description": "Return a Widget",
        "parameters": [],
        "responses": {
```

But this fails to compile:
```
interface ResourceOperations<T> {
  @doc("Return a {name}", T)
  @get broke(): T | Error;
}

@route("/widgets")
interface WidgetService extends ResourceOperations<Widget> {};
```

<img width="764" alt="image" src="https://user-images.githubusercontent.com/85643503/206462633-bc9fc7d4-d6fb-4cca-b60e-82db4996fe68.png">

**Comment by markcowl** [comment]
(docs only)
est: 1

**Comment by markcowl** [comment]
This second parameter is being deprecated in favor of the new string interpolation system. Closing

**Comment by mikekistler** [comment]
Issue for new string interpolation system: [#932](https://github.com/microsoft/cadl/issues/932)
