### ISSUE TITLE
Multi-line `@doc` should support declare doc for members

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/cadl#1399]
Multi-line `@doc` should support declare doc for members

```
@doc("""
{id} the key to widget     // <-- these should be carried down to properties as single line @doc
{weight} sdfsdf
""")
model Widget {
  @key id: string;
  weight: int32;
  color: "red" | "blue";
}

op test(...Widget): void;
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGRvYygiIiIKe2lkfSBpcyB0aGUga2V5CiIiIikKbW9kZWwgV2lkZ2V0IHsKICAvL8YxMcgBIikKICBAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9CgpvcCB0ZXN0KC4uLsZqKTogdm9pZDsKCg%3D%3D)

**Comment by nguerrera** [comment]
This does not reconcile well with the unification proposal on #927 :

https://gist.github.com/nguerrera/a48a3d8f005eb5322683fc5ddc48c363
 
For moving things on parameters, that proposal has @param doc tag becoming a Doc.param decorator. There was nothing for documenting properties at the top-level comment, but it could follow that proposal and have `@property` tag perhaps.

The unification proposal also talks about supporting interpolation as a possibility, but it is not needed for the case of targeting a tag at a sub-entity. The parser can parse identifiers as the first argument to doc tags for that.

**Comment by nguerrera** [comment]
Superceded by #1501
