### ISSUE TITLE
[Tooling] Typing " should produce a double-quote pair

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#1417]
In VS Code with the Cadl VS Code extension enabled, typing an open paren will produce an open and closed paren and typing an open curly-brace will produce an open and closed curly-brace.  But typing double-quote `"` produces just a single double-quote.

This is contrast to the behavior of VS Code for TypeScript files, where typing a double-quote produces a double-quote pair, with the cursor after the first double-quote.  

I think VS Code for Cadl should work like VS Code for TypeScript and produce a double-quote pair when a double-quote is typed.

I'd also like this behavior in the Cadl playground.

**Comment by markcowl** [comment]
est: 1
pri: 2

**Comment by mikekistler** [comment]
I found the file where I could make this change but discovered this comment:
```
  // NOTE: quotes omitted here intentionally for now as they interfere with typing """
```

I'll add the double quote and submit the PR and we can decide how to proceed.
