### ISSUE TITLE
customize the operation name should not change the route for this operation

### ISSUE THREAD

**Issue by chunyu3** [microsoft/cadl#1420]
In ADP
```
@tag("Discovery")
interface DiscoverySpecialFileOperations {
  #suppress "@azure-tools/cadl-azure-core/use-standard-operations" "ADP data-plane API uses custom LRO response template the LRO actions."
  @doc("Initiates the process of generating SAS signed URIs for uploading special files for the discovery.")
  @extension("x-ms-long-running-operation", true)
  @asyncOperationOptions("location")
  @pollingOperation(LongRunningOperationStatus)
  generate is CustomLongRunningResourceCollectionAction<
    DiscoverySpecialFile,
    {},
    DiscoverySpecialFile,
    DiscoveryLroResponse
  >;

  ......
}
```

The auto-gen route will be 
/discoveries/{discoveryId}/specialFilesUploadInfo:generate

But in order to resolve naming confliction, customized code will be added to override the operation name in client.cadl as following;
```
#suppress "@azure-tools/cadl-azure-core/use-standard-operations" "ADP data-plane API uses custom LRO response template the LRO actions."
    @convenienceAPI
    generateDiscoverySpecialFileUploadLocations is Adp.DataManagement.Ingestion.Discovery.DiscoverySpecialFileOperations.generate;
```

The auto-gen router will be changed to `/discoveries/{discoveryId}/specialFilesUploadInfo:generateDiscoverySpecialFileUploadLocations `

When the operation name is customized, the operation name should not be updated.

**Comment by tjprescott** [comment]
Hi @chunyu3 if you have a resource action and don't specify the `@actionSegment` decorator, it uses the operation name as the action name.

**Comment by markcowl** [comment]
```cadl
@actionSegment"generate")
generateDiscoverySpecialFileUploadLocations 
```

would be how to deal with this.

**Comment by imakhlin** [comment]
@markcowl 
I think that there is no need in special `@actionSegment` decorator. SDK code generator should be able to deduce the route from the operation defined in the CADL. This is common scenario when developer combines APIs of multiple services into a single client interface (like I did for ADP for example). The main purpose of the client interface is to define unique names for the APIs exposed through the ${service}Client interface. The routs should remain exactly as they defined in the CADL for the operations.

**Comment by markcowl** [comment]
Closing in favor of #1466 Which covers any additional design elements for operation sharing.

**Comment by markcowl** [comment]
@imakhlin @chunyu3 In this case, using the action decorator on the source operation will pass through to the reused operation, which is what I would expect of a good operation template.  It is likely out of scope for us to make operations that do not use Azure Core components and do not follow reusable patterns easy to reuse.  This may result in additional linting rules for operations (for example, requiring the appropriate action decorator for resource actions) in order to make client reshaping easier.
