### ISSUE TITLE
Variable interpolation Cannot work When input a parameter by --arg in command

### ISSUE THREAD

**Issue by dw511214992** [microsoft/cadl#1434]
## How to reproduce
1. Download the [cadl project](https://github.com/Azure/azure-rest-api-specs/tree/dw/cadl-bug/specification/cognitiveservices/OpenAI.Inference) I used.
2. `npm install`
3. `npx cadl compile . --emit @azure-tools/cadl-java --arg "java-repo-folder=/tmp/java"`

## Result
The codes are generated in `{cwd}/azure-sdk-for-java`.

## Expected
The codes should be generated in `/tmp/java`.

## Other Issue:
In the `cadl-project.yaml`, you can find the value of `emitter-output-dir` is surrounded by double quotes. If I delete the double quotes, the cadl reports error: `bad indentation of a mapping entry (6:45)`

**Comment by dw511214992** [comment]
@allenjzhang @weshaggard @timotheeguerin

**Comment by dw511214992** [comment]
@timotheeguerin thank you. Is there an ETA to fixed it?

**Comment by timotheeguerin** [comment]
This has been resolved and a new version of the compiler has been released https://www.npmjs.com/package/@cadl-lang/compiler/v/0.38.4

**Comment by dw511214992** [comment]
Thanks @timotheeguerin It work now. But the value must be surrounded by double quotes, otherwise there will be issues. If it's expected, please also update the document:
![image](https://user-images.githubusercontent.com/40835867/208019291-42480423-f5bf-4637-9fe2-4b9be7ebb4b1.png)
