### ISSUE TITLE
Spread model/alias in an operation, cadl compiler return an anonymous model

### ISSUE THREAD

**Issue by chunyu3** [microsoft/cadl#1472]
When we spread an model/alias in an operation, the cadl compiler will return anonymous model.

```
model Thing {
  @path
  @doc("name of the Thing")
  name: string;
  age: int32;
}

alias ThingAlias = {
  @doc("name of the Thing")
  aliasName: string;
  ...Thing
};

op spreadModel( ...Thing ): void;

op spreadAlias( ...ThingAlias ): void;
```

cadl compiler will return an anonymous model as the operation body type.

To generate the model in SDK (specially .Net and Java), We need an model with a name.

**Comment by timotheeguerin** [comment]
This is expected, in the case of a model `getEffectiveModelType` can be used to retrieve the model where all the properties can come from
