### ISSUE TITLE
Swagger UI Schema array content summary not updating when new items are added 

### ISSUE THREAD

**Issue by outofcoolnames** [microsoft/cadl#1476]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiV2lkZ2V0IFPGGyIsCn0pCm5hbWVzcGFjZSBEZW1vxxs7Cgp1c2luZyBDYWRsLkh0dHA7zBFSZXN0OwoKbW9kZWwgx1XEaEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSB8IGdyZWVuIjsKfQoKQGVycm9yx15FxAzFXWNvZGXLSG1lc3NhZ2XKbH0KCmludGVyZuQAzOYAlecAziBleHRlbmRzIFJlc291cmNl5ADBxQlPcGVyYXRpb25zPMYyLMZxPsVyQOQA2EByb3V0ZSgiY3VzdG9tR2V0IikgyQwoKTrHa%2BQAgA%3D%3D)

See above. I selected the Widget Service example and added another entry to the Widget model array property "color":
```cadl
model Widget {
  @key id: string;
  weight: int32;
  color: "red" | "blue | green";
}
```
On the right hand side, I selected the swagger view.
I expanded the Widget schema. I then expanded the color array. This was shown:
```
<html><body>
<!--StartFragment--><span class="model-box"><div class="model-box"><span class="model"><span class=""><button aria-expanded="true" class="model-box-control"><span class="pointer"><span class="model-title"><span class="model-title__text">Widget</span></span></span><span class="model-toggle"></span></button><span class="brace-open object">{</span><span class="inner-object">

id* | [...]
-- | --
weight* | [...]
color* | stringEnum:Array [ 2 ]

</span><span class="brace-close">}</span></span></span></div></span><!--EndFragment-->
</body>
</html>
```
Note the Array[2]. There are 3 items in the array.
Expanding the array content does show 3 items: red, blue and green

**Comment by timotheeguerin** [comment]
Hey @outofcoolnames I think this is just because you still have 2 options:
- `"red"` 
- `"blue | green"`

The pipe is inside the string value

**Comment by outofcoolnames** [comment]
Yes, that must be it. Closing the issue now
