### ISSUE TITLE
exclusiveMinimum=true is not supported

### ISSUE THREAD

**Issue by asaflevi-ms** [microsoft/cadl#1481]
Hi 
I need to specify a property that indicates an age in a medical record.
Type should be a floating-point greater than zero.
For that I used (in OpenAPI) minValue(0) along with exclusiveMinimum=true.
Apparently,  exclusiveMinimum is not supported by CADL.

**Comment by markcowl** [comment]
## Proposal
- add new `@exclusiveMinValue`, `@exclusiveMaxValue`

- alternately, we could add an optional boolean or options parameter to existing decorator

**Comment by markcowl** [comment]
Complete
