### ISSUE TITLE
Projection of query and header

### ISSUE THREAD

**Issue by lmazuel** [microsoft/cadl#1487]
This should work fine:

```cadl
alias Params = {
  // "top" on the wire, "itemsByPage" on SDK side
  @projectedName("client", "itemsByPage")
  @query top?: int32;

  // "x-ms-request-id" on the wire, "RequestId" on SDK side
  @projectedName("client", "RequestId")
  @header "x-ms-request-id"?: string;

  // "$filter" on the wire, "FilterByName" on SDK side
  @projectedName("http", "$filter")
  @query FilterByName?: string;

  // "x-ms-correlation-id" on the wire, "CorrelationId" on SDK side
  @projectedName("http", "x-ms-correlation-id")
  @header CorrelationId?: string;
};

op getCert(...Params): CertificateAttributes;
````

[Playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwO8wRUmVzdDsKCm1vZGVsIENlcnRpZmljYXRlQXR0cmlidXRlcyB7CiAgQHByb2plY3RlZE5hbWUoImpzb24iLCAibmJmIinTIGNzaGFycMQiVmFsaWRBZnRlcsUpbm90QmVmb3JlOiBpbnQzMjsK215leHDFNWV4cGlyZXPJMyAgY3JlYXRlZMsSdXBkzRJ9CgphbGlhcyBQYXJhbXMgPeUAyC8vICJ0b3AiIG9uIHRoZSB3aXJlLCAiaXRlbXNCeVBhZ2XFG1NESyBzaWRl9ADabGllbnTkAJ7MNeUBBHF1ZXJ5IHRvcD%2FsAN3Ec3gtbXMtcmVxdWVzdC1pZNB%2FUsYaScYZ333GfcozxXtoZWFkZXLSaT86IHN0cmluZ%2BkAiyRmaWzkAY3vAINGxRZCecRo%2FwCGImh0dOUB28hL6wD9zEfSfOUAnmNvcnJlbGF0aW9u8wELQ8oe%2FwEP6wCJ1FjsARfNVesAl307CgpvcCBnZXTkAvooLi4u5gItKTr2Aws7)

According to @timotheeguerin , projections do not work on header and query as of now. They should, as using the augment syntax in `client.cadl` would enable DPG team to rename parameters without touching the CADL. 

Note that I project in both ways in the issue:
- CADL Name is HTTP, projected name is client
- CADL Name is client, projected name is HTTP

I'm not sure in the second scenario if the best target name is `http` or something else, but none of the current option really matches what we need: https://microsoft.github.io/cadl/standard-library/projected-names#known-targets

**Comment by markcowl** [comment]
pri: 2

**Comment by markcowl** [comment]
@lmazuel In this case, I would expect the names of alias properties to be good, conceptual names, and the http projections of those names to be part of http metadata. for example:

```cadl
alias Params = {
  // "top" on the wire, "itemsByPage" on SDK side
  @query("top") itemsByPage?: int32;

  // "x-ms-request-id" on the wire, "RequestId" on SDK side
  @header("x-ms-request-id") RequestId?: string;

  // "$filter" on the wire, "FilterByName" on SDK side
  @query("$filter") FilterByName?: string;

  // "x-ms-correlation-id" on the wire, "CorrelationId" on SDK side
  @header("x-ms-correlationId") CorrelationId?: string;
};
```

In a non-http protocol, these properties might be carried in the message body, or in some other protocol element, so that projections are not a great fit.

**Comment by markcowl** [comment]
@lmazuel Can I close this issue based on the advice above, or do you still have concerns?

**Comment by markcowl** [comment]
Closing as anwered, please reopen or let me know if you have additional concerns
