### ISSUE TITLE
Support base64url serialization format

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#149]
Similar to `base64` but has `+` serialized as `-` and `/` serialized as `_`
Meant to be safe to be used in urls

**Comment by markcowl** [comment]
How to fix:
- `@format("base64url")`

**Comment by markcowl** [comment]
Should be handled by #153

**Comment by markcowl** [comment]
Closing based on completed work, added https://github.com/Azure/cadl-azure/issues/1246 to track work on cadl-providerhub-controller
