### ISSUE TITLE
Could @tag decorator on an interface be inherited by operations?

### ISSUE THREAD

**Issue by markrendle** [microsoft/cadl#1502]
What I'd like is, when I put a `@tag` decorator on an `interface`, compiling to OpenAPI would have all the operations in that interface inherit that same tag, unless they have their own. So this:

```
@tag("Apps")
interface AppsService {
  //Create a new application.
  @post createApp(@body body: CreateAppForm): Application | UnprocessableContentError;

  // Verify credentials and get the current user.
  @route("verify_credentials") 
  @get verifyCredentials(): Application | UnauthorizedError;
}
```

would produce this:

```json

  "openapi": "3.0.0",
  "info": {
    "title": "Mastodon",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "Apps"
    }
  ],
  "paths": {
    "/api/v1/apps": {
      "post": {
        "tags": [
          "Apps"
        ],
        "otherStuff": "elided"
      }
    },
    "/api/v1/apps/verify_credentials": {
      "get": {
        "tags": [
          "Apps"
        ],
        "otherStuff": "elided"
      }
    }
  }
}
```

**Comment by timotheeguerin** [comment]
Hey @markrendle is that not already working? https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKQHRhZygiQXBwcyIpCmludGVyZmFjZSDEEVNlcnZpY2UgewogIC8vQ3JlYXRlIGEgbmV3IGFwcGxpY2F0aW9uLgogIEBwb3N0IGPFIkFwcChAYm9keSDEBTogc3RyaW5nKTogdm9pZDsKxUwgVmVyaWZ5xDJkZW50aWFscyBhbmQgZ2V0IHRoZSBjdXJyZW50IHVzZXLFYHJvdXRlKCJ2xTdfyzciKSDEIMQ5xh1DyhwoyXV9

**Comment by markrendle** [comment]
Ha, yes, it is. I was playing with the Moostodon sample and got confused about how the project was structured.
