### ISSUE TITLE
[OpenAPI] "format" and "pattern" are different. @format decorator currently only map to "pattern" 

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/cadl#153]
OpenAPI "format" contains open value, "pattern" is for regEx.  "format":"UUID" ARE widely used in our rest spec.

One choice is to add @pattern and repoint @format to "format". Thoughts?

----
https://swagger.io/docs/specification/data-models/data-types/

**Comment by markcowl** [comment]
format: bytes
format: dateTime
format: uuid

- move format decorator -> pattern
- add a format decorator whose value is transmitted directly to openAPI
 - ```@format("uuid") foo: string```  results in swagger with type: string, format: uuid, results in generators
  - we have built-in types for datetime, bytes, binary
- Should we have defined types for uuid, uri, email, ipv4, ipv6, ...?  Need a definitive list.  Where would these go?  [core?]
    - find the definitive list of formats
    - decide how to represent each
    - decide on constraints as appropriate
