### ISSUE TITLE
Add `@error` decorator to cadl core

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#155]
- Add a decorator and detection function to designate models as errors when included in an operation response.  Per [this design issue](https://github.com/Azure/cadl-azure/issues/732)
- OpenAPI emitters use @error, when present to determine default responses.

**Comment by markcowl** [comment]
- implement @error decorator in core
- add @error decorator to cadl-rpaas error types
- update cadl-autorest to use @error to determine the default response, based on the guidance in #732
- Add linting rule in cadl-rpaas to require *one* error response in each response union

**Comment by markcowl** [comment]
also:
- update openapi3 to use @error decorator to determine the error responses per #732

**Comment by mikekistler** [comment]
I'm going to take this one since it relates to the status code work I've been doing.
