### ISSUE TITLE
Linter rule to encourage strong-typing

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1563]
Follow-up item from: https://github.com/microsoft/cadl/pull/1562

Comparing these two:
```Typescript
const namespaceDependencies = new Map();

const namespaceDependencies = new Map<Namespace | undefined, Set<Namespace>>();
```

The first form here resulted in bugs, because you no longer have compiler type-checking of what you put in the map. Thus when you pull something out, expecting a certain form, you can get unexpected bugs at runtime, which feels very anti-TS.

Simply being more explicit, as in the second form, results in the compiler identifying the issue, catching the error at compile-time instead of runtime.

Can we add/enable a linter rule to the repo that flags when we use this kind of weak typing that could result in bugs sneaking into our code?

**Comment by markcowl** [comment]
@tjprescott Please paste in the error we get from  cadl-azure repo linting

**Comment by tjprescott** [comment]
Yeah, I can't the same code in Azure Core doesn't complain either, so it must be a different scenario. It does seem like it would be beneficial to prohibit (or at least flag) these instances where we put ambiguous type information in place to shut the compiler up only to get runtime errors down the road.

That being said, if there's no existing thing that checks for this, then I'm not advocating for spending engineering time to come up with our own rule.

**Comment by markcowl** [comment]
It might be worth a quick look through the esLint built-int to see if there is anything similar.  Feel free to close if there is no prior art

**Comment by bterlson** [comment]
I asked [on Masto](https://m.terlson.net/@SeaRyanC@fosstodon.org/109740221355764243) and it doesn't seem like there's a good out of box solution here surprisingly. We could write our own linter...

**Comment by tjprescott** [comment]
Yep, I didn't see anything in the eslint list. Like I said, I don't think it's worth the engineering effort to create our own rule, so I'll close this.
