### ISSUE TITLE
Feb Release: Breaking Changes and Deprecations

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1564]
# Compiler

## Breaking Changes

- Removed all `FooType` aliases of `Foo` types. Use `Foo` instead.
- Removed `uri` scalar. Use `url` instead.
- Removed `Map<K, V>` model. Use `Record<V>` instead.
- Removed `@serviceTitle` and `@serviceVersion` decorators. Use the `@service` decorator instead.
- Removed `getServiceNamespace`, `getServiceTitle`, `getServiceVersion`, `getServiceNamespaceString` and `setServiceNamespace` functions. Use the following functions instead: `getService`, `listServices`, `isService`, `addService`.

## Deprecations

- Deprecates the `@versionedDependency` decorator in favor of the `@useDependency` decorator.

For versioned libraries, `@useDependency` is now applied directly to the version enum members.
 
**Before**
```
@armProviderNamespace
@service({
  title: "Dynatrace.Observability",
})
@versionedDependency(
  [
    [Dynatrace.Observability.Versions.v2021_06_13_preview, Azure.Core.Versions.v1_0_Preview_2],
    [Dynatrace.Observability.Versions.v2022_04_30_preview, Azure.Core.Versions.v1_0_Preview_2]
  ]
)
@versionedDependency(
  [
    [
      Dynatrace.Observability.Versions.v2021_06_13_preview,
      Azure.ResourceManager.Versions.v1_0_Preview_1
    ],
    [
      Dynatrace.Observability.Versions.v2022_04_30_preview,
      Azure.ResourceManager.Versions.v1_0_Preview_1
    ]
  ]
)
@versioned(Versions)
namespace Dynatrace.Observability;

interface Operations extends Azure.ResourceManager.Operations {}

enum Versions {
  v2021_06_13_preview: "2021-06-13-preview",
  v2022_04_30_preview: "2022-04-30-preview",
}
```

**After**
```Cadl
@armProviderNamespace
@service({
  title: "Dynatrace.Observability",
})
@versioned(Versions)
namespace Dynatrace.Observability;

interface Operations extends Azure.ResourceManager.Operations {}

enum Versions {
  @useDependency(Azure.Core.Versions.v1_0_Preview_2, Azure.ResourceManager.Versions.v1_0_Preview_1)
  v2021_06_13_preview: "2021-06-13-preview",

  @useDependency(Azure.Core.Versions.v1_0_Preview_2, Azure.ResourceManager.Versions.v1_0_Preview_1)
  v2022_04_30_preview: "2022-04-30-preview",
}
```

For unversioned libraries that reference versioned libraries, simply replace `@versionedDependency` with `@useDependency`.

**Before**
```Cadl
@service({
  title: "Microsoft.EnvelopeTest",
  version: "2021-09-21-preview",
})
@versionedDependency(Azure.ResourceManager.Versions.v1_0_Preview_1)
@armProviderNamespace
namespace Microsoft.EnvelopeTest;
```

**After**
```Cadl
@service({
  title: "Microsoft.EnvelopeTest",
  version: "2021-09-21-preview",
})
@useDependency(Azure.ResourceManager.Versions.v1_0_Preview_1)
@armProviderNamespace
namespace Microsoft.EnvelopeTest;
```

# Rest

## Breaking Changes

- Removed `@segmentSeparator`. Use `@actionSeparator` instead.
- Removed `@produces` and `@consumes` decorators. Use `@header contentType: <ContentType>` instead in the operation return type.
- Removed `getSegmentSeparator` function. Use `getActionSeparator` instead.
- Removed `getProduces` and `getConsumes` functions. Use `getContentTypes` instead.

**Comment by nguerrera** [comment]
### Cadl extension for Visual Studio will stop supporting Visual Studio 2019 in the March release. Please upgrade to Visual Studio 2022
