### ISSUE TITLE
Azure CADL Playground has broken file bug link

### ISSUE THREAD

**Issue by sre-is-toby** [microsoft/cadl#1594]
**Description**

The CADL Playground "File Bug" link errors when clicked on and goes to a non-existent repository. 

**Repro Steps**

1. Go to https://microsoft.github.io/cadl/
2. Click on ["Cadl Playground for Azure Services"](https://cadlplayground.z22.web.core.windows.net/cadl-azure/).
3. Click on "file bug". 
4. See that it links to a non-existent repository under Azure, rather than here.

**Comment by markcowl** [comment]
Cadl Playground for Azure Services links to a website in a private Organization for Azure developers.  If you click the 'Playground' or 'Cadl PlayGround' links, that links you to the core language playground, which files issues here.
