### ISSUE TITLE
Parameters table doesn't render correctly for multi-line descriptions:

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1605]
![image](https://user-images.githubusercontent.com/5723682/215555030-99e147a7-6bd9-44cc-8348-3e6326f1c8b6.png)

Renders as:
![image](https://user-images.githubusercontent.com/5723682/215555110-e24db3cf-3033-4880-af48-7c4a3924385f.png)

It doesn't matter how many spaces you do (or don't) put for a hanging indent. If you put everything on a single line it works, but for all practical purposes we need to handle multi-line comments appropriately.

**Comment by markcowl** [comment]
timebox: 2
est: ?

@nguerrera please provide an estimate

**Comment by nguerrera** [comment]
est: 1, in PR
