### ISSUE TITLE
Can generated docs pull doc-comments from function definition?

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1606]
Right now, the doc generator seems to only pick up the docs for a decorator if the doc comment is copied from the function onto the `extern dec` statement. Just from the DRY principle, this is unfortunate, as it means that the docs need to be changed in two places, which will inevitably result in an inconsistency.

Is there no way to essentially reference the doc comments in the underlying function? Alternatively, could the function pull its doc comment from the `extern dec` statement in the cadl?

**Comment by markcowl** [comment]
Decided not to do this

**Comment by nguerrera** [comment]
We should *move* decorator usage documentation from .ts to extern dec, then it's still DRY.

**Comment by tjprescott** [comment]
Why would we decide to do nothing here? Do we want the documentation between extern dec and the actual decorator functions to be different?  Even Nick's comment above would suggest this issue shouldn't be closed since.

**Comment by nguerrera** [comment]
It's fine IMHO to reopen this to track *moving* any decorator docs out of .ts and into .cadl. The title should be changed in that case, or maybe just open a new issue.

We explicitly rejected pulling info from .ts after a long investigation where we started out trying to do exactly that and it was too expensive to drive IDE features and such.

**Comment by tjprescott** [comment]
Makes sense. If pulling intellisense from the `extern dec` is feasible, then I'm happy to reopen and change the title. If we _want_ the documentation to be different between the `*.cadl` and `*.ts` then it make sense to keep this closed--I just couldn't think of a reason we would want that.

**Comment by nguerrera** [comment]
> If pulling intellisense from the extern dec is feasible

It's not only feasible, it's already implemented :) This one o the major value adds of extern dec!

<img width="483" alt="image" src="https://user-images.githubusercontent.com/75470/215875928-e8cb8c3c-6ec4-4c35-b4fc-ba0a9e4f6ea3.png">

>  If we want the documentation to be different between the *.cadl and *.ts

No we don't want that. :)

**Comment by tjprescott** [comment]
Well, if it's already implemented, then I guess this can stay closed 😛

**Comment by nguerrera** [comment]
I think maybe I'm missing something. If there are docs in .js now that are duplicated in the .cadl, then we should delete them from the .js. Having an issue for that is fine and good. If there is not such duplication now, then yeah, we're done here.

**Comment by tjprescott** [comment]
It may just be in my PR. I was copying the docs from the *.ts to the *.cadl.
