### ISSUE TITLE
OpenAPI3 emitter output differs in Playground and Local compile

### ISSUE THREAD

**Issue by binoychitale** [microsoft/cadl#1613]
Hi team,
I'm trying to compile my cadl document to OpenAPI 3.

I first tried to compile the source in cadl playground, and it renders fine via Swagger UI.

However when I compile it locally using `cadl compile . --emit @cadl-lang/openapi3` I find that the output does not render correctly in Swagger.

On closer look, it seems like the output yaml in Playground (using @cadl-lang/openapi3 emitter) differs from the output when run locally using the same emitter.

Here is one difference I noticed between Playground output and local:
On playground, references are compiled to yaml in the following way:
```
schema:
              $ref: '#/components/schemas/<model-name>'
```

However, on the local compiler I see the same model reference compiled as:
```
schema:
              $ref:
                value: '#/components/schemas/<model-name>'
```

It seems to me that this is what is breaking the Swagger rendering when compiled locally, but it seems like Playground compiles it correctly.
I have verified that I am using the same emitter (@cadl-lang/openapi3)

Any help would be appreciated :)

**Comment by bterlson** [comment]
This was a recent bugfix that I thought was released as a hotfix. Will look into doing that. In the meantime, you can use json output which does not have the broken output (pass --option @cadl-lang/openapi3.file-type="json").

/cc @daviwil

**Comment by praneetloke** [comment]
@bterlson is the fix for YAML outputs available in the latest commit on `main`? I don't want to use the JSON output.

**Comment by markcowl** [comment]
@praneetloke @binoychitale Can you verify that this still occurs with the latest release (i.e. yesterday's release).  If this was working with the latest developer version 3 days ago, then it should be fixed when you upgrade.

**Comment by praneetloke** [comment]
@markcowl yep it looks good with the latest release :)

**Comment by markcowl** [comment]
Closing as fixed
