### ISSUE TITLE
Supporting parameterized host "x-ms-parameterized-host"

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/cadl#175]
https://github.com/Azure/azure-rest-api-specs/blob/dc439efcfc15448824877603f66fc1578d1c71c5/specification/search/data-plane/Microsoft.Azure.Search.Service/stable/2019-05-06/searchservice.json#L11

**Comment by markcowl** [comment]
## Proposal
- Add a new decorator for namespaces that allows specifying a host template, parameters, and optional schema.  Also consider adding a decorator that designates a model as metadata only.
  ``` typescript
  @compositeHost("{accountName}.{regionSuffix}", MyServiceHost, "https" )
  namespace Microsoft.MyService
  @metadata
  model MyServiceHost {
   @doc("The name of your myService Account")
    accountName: string;
   @doc("The regional suffix of the service")
   regionSuffix: "azure.com" | "azure.cn";
  }
   ```
- Export function accessors that allow retrieving the host details for a namespace: getHostTemplate, getHostParameters, getHostSchema
- Add decorators to the Azure library
- Note that parameter model could be inline, it might also contain references to properties in real models (for example, storage service parameters may be properties of the storage account, which may have a rpersentation in the library)

## Proposal 2
- Add a core mechanism for parameterizing strings and use this for the host
  ``` typescript
  @parameterizedString("${foo}/${bar}")
  model FooBarParameters extends string{
    foo: string;
    bar: string;
  }
  ```

**Comment by markcowl** [comment]
- add discussion of openapi3 servers feature
- include how we might represent paths and other common features using composite strings
  - clear indication that these things are strings
