### ISSUE TITLE
Errors not shown in IDE when document is on disk (not "untitled")

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#177]
Single quotes are not valid in Cadl but they are not flagged in the VSCode extension.

Simple recreate:
```
import "@cadl-lang/rest";
import "@cadl-lang/openapi3";

using Cadl.Http;

model Pet {
  name: string;
}

model CreatedResponse {
  @statusCode code: '201';
}

@route("/Pets")
namespace Pets {
  op create(): CreatedResponse & Pet;
}
```

This fails to compile with:
```
Diagnostics were reported during compilation:

/Users/mikekistler/Projects/Microsoft/cadl/packages/samples/scratch/bug.cadl:11:21 - error invalid-character: Invalid character.
/Users/mikekistler/Projects/Microsoft/cadl/packages/samples/scratch/bug.cadl:11:21 - error token-expected: Expression expected.
/Users/mikekistler/Projects/Microsoft/cadl/packages/samples/scratch/bug.cadl:11:25 - error invalid-character: Invalid character.
/Users/mikekistler/Projects/Microsoft/cadl/packages/samples/scratch/bug.cadl:11:22 - error token-expected: Statement expected.
/Users/mikekistler/Projects/Microsoft/cadl/packages/samples/scratch/bug.cadl:12:1 - error token-expected: Statement expected.
```

But no warnings are shown in VSCode.

The code compiles cleanly when the single quotes are changed to double quotes.

**Comment by timotheeguerin** [comment]
@nguerrera any ideas what could be causing this, wouldn't the vscode extension get the same errors?

**Comment by nguerrera** [comment]
Weird! I will take a look.

**Comment by nguerrera** [comment]
Separately, we should do better error recovery here too since this is a common mistake.

**Comment by timotheeguerin** [comment]
Could always do the same as the semi colon. Undestand it is a string but make it an error and say this is printable so the formatter can fix it.

**Comment by nguerrera** [comment]
It looks like language server is just completely busted right now :(

**Comment by nguerrera** [comment]
Hmm, it works on F5, but not in our sln, not sure what's up yet, no errors in output window at all. Very strange.

**Comment by nguerrera** [comment]
@timotheeguerin observes the distinction isn't monorepo vs. not, it's untitled docs vs docs with paths and likely the changes to path handling broke things here.
