### ISSUE TITLE
Using intersection in return type creates an anonymous model

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#178]
It would handy to be able to add a status code or header to a model as the return type of a method, like:
```
model Ok {
  @statusCode code: "200";
}

model Cat {
  meow: safeint;
}

@route("/Cats")
namespace cats {
  op read(): Ok &Cat;
}
```

But doing so currently creates an "anonymous model" as the response schema for read.  Without the intersection, the response schema would be the named schema "Cat".

I realize that in general intersection will create an anonymous model, but I wonder if an exception is warranted in the case where the only added properties are decorated with @statusCode or @header.

Note that the alternate form:
```
  op read(): {
    @statusCode code: 200;
    @body body: Cat;
  };
```

does give produce a response schema as the named schema "Cat", so we can accomplish what we want.  But we can't use the (IMHO) simpler and more elegant intersection approach to achieve it.

**Comment by markcowl** [comment]
Two options (currently) for how to represent a response template:

``` javascript
model ArmOKResponse<T> {
  ...OKResponse
  @body body: T;
}

model ArmOKResponse<T> {
  ...OKResponse
  ...T; // spreadsource: T
}
```

We think all of these representations should be equivalent:
``` javascript
op read() : ArmOKResponse<Cat> ;
op read() : {....OKResponse; ...BlobProps; }; // spreadsource: Cat
op read() :   OKResponse & Cat | ErrorResponse; //proposal: change spreadsource to something not tied to spread (source?)
op read(): Cat;
```

- what do we do with a model in which the logical response i mapped into protocol metadata in http?
``` javascript
model BlobProps {
  @header myProp: string;
}
```

- For this kind of case, we need a mechanism to differentiate metadata from logical response
- This is orthogonal to the representation inside Swagger - the correct swagger for any operation containing a response like this will not be able to generate a client that we want.

**Comment by markcowl** [comment]
@mikekistler  I believe this is covered by the algorithm in #182, as we all agreed that these forms should result in identical schema with identical names
