### ISSUE TITLE
Duplicate namespace silently ignored

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#180]
Defining a namespace more than once is silently ignored.  E.g. the following Cadl
```
import "@cadl-lang/rest";
import "@cadl-lang/openapi3";

using Cadl.Http;

@route("/")
namespace root {
  op read(): string;
}

@route("/test")
namespace root {
  op getStatus(): string;
}
```
creates the `/test` path but the root path is not emitted (by the openapi3 emitter).

I'm not sure if this is a problem in the emitter or in what is passed in to the emitter.

**Comment by timotheeguerin** [comment]
That's an interesting issue. Feel like in general you should be able to merge the namespaces(Like csharp namespaces) but here the metadata override the previous one.
Guess maybe we should emit a diagnostic that namespace `root` has 2 `@route`

**Comment by markcowl** [comment]
- first operation is dropped
- should be checking that decorators are not in conflict when merging namespaces
- investigate for a fix in v1
