### ISSUE TITLE
Revised design for status codes

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#197]
A comment from @markcowl on my cadl-autorest changes for status codes made me rethink the approach we've implemented in the core. He raised concerns about using "default" as a status code value.  Given that we have implemented `@statusCode` in the http library, I think this concern is warranted. We should restrict `@statusCode` to just values consistent with the http standard, and not mix in OpenAPI concepts.

So I propose:

1. Moving the validation of the status code value to the http library. I think it is a good general practice that the implementing library should define and enforce that values / meaning of its arguments -- and it eliminates the duplicate validation logic we have today across several emitters.

2. Introducing new decorators in the OpenAPI emitter for "pseudo-status-codes": `@default`, `@2XX`, `@4XX`, `@5XX` (possibly others). These decorators would only be valid on models. When present on a model used as a return type, the OpenAPI emitter will:
  - Issue a diagnostic if the model also contains a status code
  - Otherwise it will use the corresponding "pseudo-status-code" to define the response.

I can hear you asking: How will this interact with the `@error` decorator? I think:
  - If both @error and an "pseudo-status-code" decorator are both present, the response key will be set based on the "pseudo-status-code" (on the principle that it is more explicit).
  - @error alone without a status-code will use response "default"

**Comment by jianyexi** [comment]
I wonder in which scenario we prefer to use "pseudo-status-codes" to define a response model 
As if we implement `@error`  per  https://github.com/microsoft/cadl/issues/155 , we already have a mechanism about when to  generate the "default" error response in swagger

**Comment by mikekistler** [comment]
I agree that we _could_ use `@error` to specify the "default" response -- and in the absence of anything else we should make `@error` be "default".  But I think we want an _explicit_ mechanism for this. We have said many times that we want to avoid "magic". This was  our rationale for requiring http verbs to be specified explicitly. I think the same rationale applies here.

**Comment by mikekistler** [comment]
Fixed in #199 and #210.
