### ISSUE TITLE
Decorator diagnostics on decorator node or an argument 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#200]
Goal is to be able to emit a diagnostic from a decorator where the target is the decorator itself or one of the argument.
This is independent from the ability to provide a decorator definition that  can do the auto validation of most cases.

For example 
```cadl
 @added(<ERROR LOCATION IS HERE>"value-not-allowed")
 myProp: string 
```

## Proposal

https://gist.github.com/timotheeguerin/6f030d63926d9572557b78bea8e6837e

**Comment by timotheeguerin** [comment]
One use case of decorator composition:

```ts
export function $myMagicRoute(program, entity, path: string) {
   $route("/magic/${path}")
}
```

and then you have the following cadl
```ts
@route("/magic/foo")
op foo1(): string;

@magicRoute("/foo")
op foo(): string;
```

In that cases it result in the route decorator creating a conflicting route. I think I would expect the errors to show up on the corresponding decorators(route and magicRoute).
Maybe the solution when reporting diagnostic from a decorator is to get a "stacktrace" of the source and go back to the orginal decorator:
- if you are in the initial decorator use then you can get the position of the decorator or argument
- if you are in a composed decorator then it just return the position of the parent decorator.

**Comment by markcowl** [comment]
```
$other(context.passThru, "something)
``` 

or 

```
context.call($other, "something")
```

-- naming: getTargetForParam => getArgumentTarget

**Comment by markcowl** [comment]
avoid: `$other(context, "something")`

- this results in inaccurate diagnostic target
- could lint for this in libraries
