### ISSUE TITLE
Separate model templates out from models in semantic model

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#221]
It can be easy to get tripped up by trying to deal with a template as a concrete type.

Proposal: split off NamespaceType.modelTemplates from NamespaceType.models.

**Comment by markcowl** [comment]
- never see uninstantiated templates
- linkage between types instantiated to their templates
- annotation to express intention around mixin only versus intended as generic type
- same thing can apply to models when spread in

**Comment by markcowl** [comment]
- semantic walker what does it do:
  - visit the templated type
  - or this would be part of visiting

**Comment by markcowl** [comment]
Closing for action item #223
