### ISSUE TITLE
API review

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#233]
We should review all of the public JS API in the compiler and other packages.

We should probably also review the stdlib and package Cadl.

**Comment by markcowl** [comment]
Set of libraries to review
- [ ] core
- [ ] http & rest
- [ ] cadl-azure-resource-manager
- [ ] cadl-autorest

**Comment by allenjzhang** [comment]
Will do assessment for ProviderHub ARM release. Any pending work items will be treated as fast follow after release.
