### ISSUE TITLE
[Versioning] OptionalProperties/UpdatableProperties causes versioning metadata to be ignored

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#244]
The following cadl will emit an update endpoint which has an optional `color` property for v1, but `color` should not exist at all.

```
import "@cadl-lang/rest";
import "@cadl-lang/versioning";
import "@cadl-lang/openapi3";

@serviceTitle("DemoService")
@versioned("v1" | "v2")
namespace DemoService;


using Cadl.Rest.Resource;
using Cadl.Rest;
using Cadl.Http;

model Car {
  @key id: string;
  make: string;
  "model": string;
  @added("v2") color: string; 
}

model Error { }

interface MyResource mixes ResourceOperations<Car, Error> {
  @added("v2") @route("fix") @post fix(): Car;
}
```

**Comment by nguerrera** [comment]
I'll look at this as it will give me an excuse to go a little deeper into this code and get more acquainted.

**Comment by nguerrera** [comment]
This doesn't repro as written.

![image.png](https://images.zenhubusercontent.com/5bb3f3f3a3b09a49fd91842e/5b463a2d-48b4-40ff-8491-75250fba4870)

**Comment by nguerrera** [comment]
It doesn't repro if I make `color` optional either:

```diff
  @added("v2") color?: string;
  ```
  
![image](https://user-images.githubusercontent.com/75470/156626151-ea2d26dd-c2be-4750-b487-b97ff33caa3a.png)

**Comment by nguerrera** [comment]
@bterlson was this fixed?

**Comment by nguerrera** [comment]
Removing my assignment.

**Comment by nguerrera** [comment]
Oh wait, maybe I see.

**Comment by nguerrera** [comment]
Yeah, there's an inlined requestBody that has color in v1. Looking.

I'm surprised by the inlining, but it's separate.

**Comment by nguerrera** [comment]
OK, so this seems to be an issue with spread composing surprisingly with the versioned properties:

This is enough to repro:
```
import "@cadl-lang/rest";
import "@cadl-lang/versioning";
import "@cadl-lang/openapi3";

@serviceTitle("Repro")
@versioned("v1" | "v2")
namespace Repro;

model Car {
  @added("v2") color: string;
}

// repro
op test(): { ...Car; };

// no repro
// op test(): Car;
```

**Comment by nguerrera** [comment]
Spread is not sufficient. If spread into a non-anoymous model it works. Not 100% sure this is the same issue any more either.

**Comment by timotheeguerin** [comment]
So this is a bit tricky. We could add a reference of the namespace where an model expression was defined from and this solve this exact repo. However if you pass an anonymous model to a template in another versioned library then it doesn't work anymore with spread. At that point each ModelProperty needs to have a reference of the namespace they were defined in.

**Comment by bterlson** [comment]
Re: spread from across namespaces, it is debatable whether spreading respects your local namespace versioning or the versioning of the library you're spreading from, as both can be useful. I think @johanste had a case where he wanted the current semantics.

I don't think I'm opposed to giving types created from expressions a namespace. I was going to do it as part of this PR but @nguerrera talked me out of it - Nick can you share thoughts here?

**Comment by nguerrera** [comment]
Well, I didn't know about this consequence so take my argument with a massive grain of salt. But to me it was exceptionally strange feeling to say that there is My.Namespace.CadlPrimitive<T>

**Comment by nguerrera** [comment]
It didn't match any experience I had with generics or templates in C#, C++. More of a gut feeling than anything else to be honest.

**Comment by nguerrera** [comment]
We don't have type equivalence rules and maybe if they're purely structural ultimately it doesn't matter, but it opens weird questions like if two people instantiate a generic in different namespaces do they produce the same type. Do we cache template instantiation today, would we have to tweak it to return different `.namespace`?

Also, instantiating a template just doesn't feel like syntax that adds a member to a namespace. Maybe that is just bias from the other languages.

OK, I'm just brain dumping my gut reaction like I did when I talked you out of it last time. That's about all I've got.

**Comment by bterlson** [comment]
Templates are an interesting case as you could say the namespace is either where the template was declared (which I think is what you get today, FWIW) or where the type was instantiated. I think you're right that, due to caching, what we do today is the only issue.

However the issue above is more about types produced from type literals. Here it is perhaps clear that the anonymous model in the example above only belongs to the namespace it is lexically contained in. This is also true for tuple literals. However this is not the case for string/number/boolean literal types, which due to caching, have the same issue.

Would it make sense to give only model and tuple literal types a namespace based on where they are lexically defined? This feels safe to me, but if we'll just run into the problem again because e.g. the literal `"hello"` doesn't have a namespace, we'll need a more wholistic solution.

**Comment by johanste** [comment]
> I think @johanste had a case where he wanted the current semantics.
The scenario I have (had?) was somewhat complicated:

```cadl
// From sharedLibrary.cadl
namespace Azure.Core {
    model ConditionalReqeustsSupported<SupportStartedIn> {
        @added(SupportStartedIn)
        @header etag?: string;
    }
}
```
```cadl
// A specific service definition myservice.cadl
import "sharedLibrary.cadl"

@versioned("2020-03-01" | "2020-04-01")
namespace MyService {
    model Stuff { };
    op readStuff(): AzureCore.ConditionalRequestsSupportedIn<"2020-04-01"> & Stuff;
}
```

**Comment by bterlson** [comment]
I had a thought, which is if we specified versions by indexing into a version enum, do a lot of problems go away? Since the enum carries all the versions, and can be mapped to the namespace that is $versioned by it, it feels like it would clean a lot of this up..,

**Comment by nguerrera** [comment]
> However the issue above is more about types produced from type literals

That's fair. The only recollection I have of talking you out of anything was about templates, IIRC. Otherwise, I simply don't remember my argument. 😁

**Comment by nguerrera** [comment]
C# does have anonymous types (that are implemented with unspeakable names in .NET Metadata). I had forgotten if they go in a your namespace or not. Turn out they don't, but I'm not sure if I have an opinion on whether that matters: 

https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDIHYEMC2BTAzgB3QGNsACAWQE8A5LPQk0gb2VLdKgGYOZSBhZq3bCupAPYAjAFbYiAFwoAKAJSCkwjeygB2UqmwB3ZqQBiASwBOuObRwBeAEQAhC2fSoHAGlIAZdNdtsRwAVbAsAG1wxD1IAXwBuIU1YpLjkWKA

`<>f__AnonymousType0<<FirstName>j__TPar, <LastName>j__TPar>` is a class name only a compiler author could love. 🤣

**Comment by bterlson** [comment]
![image](https://user-images.githubusercontent.com/11236/161342714-d03bc410-c84a-4345-bea5-3d330adf4b33.png)

**Comment by johanste** [comment]
> `<>f__AnonymousType0<<FirstName>j__TPar, <LastName>j__TPar>`

I think someone saw how awesome snake casing was and then went one step too far!

**Comment by timotheeguerin** [comment]
I like the idea of using enum to solve the issue but in the meantime(until we can ref enum memebers) we can have a less clean solution.

So for this issue, I believe we can have a way to solve the spread issue using the `sourceProperty` when it is used inside the same versioned namespace and adding the declaring namespace to anonymous model.

However when you have a spread happening in another namespace with different versions then it tries to compare one against the other which doesn't work. I think this problem wouldn't even get solved by the version enum.

```
@versioned("l1" | "l2")
namespace Lib {
  model Spread<T> {
    ...T;
    spread: boolean;
  }
}

@serviceTitle("Repro")
@versioned("v1" | "v2")
@versionedDependency(
  Lib,
  {
    v1: "l1",
    v2: "l2",
  }
)
namespace Repro {
  // repro
  op test(): Lib.Spread<{
    @added("v2") color: string;
  }>;
```` 
The main problem is that when running the projection on `Spread` the version in question is `l1` and there is not more reference that it was `v1` for the color anonymous model.
