### ISSUE TITLE
Passing an unknown identifier to ResourceOperations shouldn't result in 44 errors.

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#246]
Compiling the following on the CLI results in a massive spew of error information due to a single error. We should perhaps ensure we don't run decorators when the arguments are errors.
```
import "@cadl-lang/rest";
import "@cadl-lang/versioning";
import "@cadl-lang/openapi3";

@serviceTitle("DemoService")
namespace DemoService;


using Cadl.Rest.Resource;
using Cadl.Rest;
using Cadl.Http;
model Error { }
interface MyResource mixes ResourceOperations<Car, Error> {
}
```

**Comment by timotheeguerin** [comment]
Doing a simple check to make sure a decorator doesn't run if one of the argument is an error type does reduce the errors to 12. There is however still is 12 some coming from just cascading generics.

What really we'd want here I think is that if a type is an error anything consuming it should stop running.

**Comment by timotheeguerin** [comment]
Adding another check after the checker to prevent `onValidate` to run (and one before the emitter) reduce it down to 4 errors.

This means that if there is any errors `onValidate` will not run after that if there is any error the emitter won't.
