### ISSUE TITLE
Better experience for `op` in interfaces

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#262]
It's really easy to forget that you don't use `op` for interface operations like namespace operations. We should have a better experience.

See discussion in https://github.com/microsoft/cadl/pull/99.

We could:

1. Do this error recovery but still not allow it as was proposed in the PR
2. Allow `op` optionally and make it "printable" so that the formatter removes it as a style preference.
3. Breaking change the language and require `op` for consistency.

**Comment by markcowl** [comment]
We will do (2)
