### ISSUE TITLE
Update handling of '@path' properties in models to include in response schema

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#267]
For a model and operation like this:

```cadl
model Foo {
  @path name: string;
  kind: string
}

@put op createOrUpdate(...Foo) : Foo;
```

Currently, the name parameter would be omitted from the 'Foo' schema.  This should change, in OpenAPI3 and OpenAPI2 emitters, the path parameter 'name' should appear in the body of the 'Foo' schema as a property with visibility read (readOnly: true), indicating that this is a schema property in responses, but not requests.

This was agreed from the discussion of protocol metadata handling here: #182

**Comment by allenjzhang** [comment]
The metadata work that Nick is working on is the final/more complete work that supersedes this issue. 
#182
