### ISSUE TITLE
Support converting cadl model types into json for `@extension` decorator

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#269]
The `@extension` decorator need to be able to pass complex json values (arrays, disctionaries) as the extension value to fully support extensions in OpenAPI.  To implement this, we should add a general capability to convert cadl Model Types into JavaScript objects.

- [x] Add `cadlToJson` function to core for use by emitters / decorators in parsing cadl models into json objects
- [x] Update `@extension` decorator in OpenAPI to accept model types as well as the current literals
- [ ] Update OpenAPI3 emitter to use the new functionality and emit extensions with complex values
- [ ] Update cadl-autorest emitter similarly
- [ ] Update documentation with examples of extensions that can be modeled this way

**Comment by markcowl** [comment]
@nguerrera @mikekistler Please take a look and edit as appropriate

**Comment by markcowl** [comment]
Resolves: https://github.com/Azure/cadl-azure/issues/1000

**Comment by bterlson** [comment]
There is a type I added for projections called an object type that could be used for this purpose if we gave it syntax. Object types are just maps of string -> type. They're used in projections for e.g. the return value of model#properties, with a forEach and get member. A strawman syntax might be something like `#{ a: "hi", b: "hi" }`

**Comment by nguerrera** [comment]
The room voted down adding syntax for now and went with adding a way for a decorator to convert a model argument to a JavaScript object by calling a helper that we'd add.
