### ISSUE TITLE
[IDE] Import completion

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#275]
It would be nice if we could complete path imports by enumerating file system and module imports by looking at available node_modules.

**Comment by timotheeguerin** [comment]
and libraries as well!

**Comment by nguerrera** [comment]
@timotheeguerin Are the follow-up items tracked already? I know we still want relative path completion and I believe there were some other improvements you had in mind? If they are tracked, linking from here would help find them. If not, could you file them?

**Comment by timotheeguerin** [comment]
No, still need to create the 2 new issues

**Comment by timotheeguerin** [comment]
https://github.com/microsoft/cadl/issues/621
https://github.com/microsoft/cadl/issues/622
