### ISSUE TITLE
Export `NodeHost` / make `CompilerHost` optional in compile API

### ISSUE THREAD

**Issue by xirzec** [microsoft/cadl#283]
It feels a bit odd to me that if you pull in `compile` from `@cadl-lang/compiler`, you have to pass `CompilerHost` but there's no way to get at the built-in [NodeHost](https://github.com/microsoft/cadl/blob/6595b501ce0f57448c5bde2cb5cc3b51fcccd8b7/packages/compiler/core/util.ts#L129) as it is not exported.

For cases where one wants to script calling the compiler instead of using the CLI, this feels moderately bumpy.

**Comment by bterlson** [comment]
The NodeHost should be exported. Hosting the compiler as a library is definitely something we want to support.
