### ISSUE TITLE
Update module resolution logic to consider top level package.json when resolving emitter names

### ISSUE THREAD

**Issue by xirzec** [microsoft/cadl#284]
Today if you want to write an emitter, you can't reference the package name of your emitter and expect `cadl` to resolve it correctly. You currently *must* use either a mono-repo pattern or use `npm link` for cadl to correctly resolve the emitter name.

My current workaround is to have a config file that does a relative import, but it's unfortunately relative *to the test file* instead of CWD from where cadl is executed from:

```yaml
emitters:
  "../dist/tsEmitter.js": true
```

Alternatively, it would be nice if emitters could be resolved by cwd so my emitter could simply be "." and it would parse package.json to find the main file.

**Comment by timotheeguerin** [comment]
@xirzec It should be working to pass:

```yaml
emitters:
  myCustomEmitterPkg: true
```
where you have `myCustomEmitterPkg` in the dependencies in the package.json

If this doesn't this looks like a bug to me. Though this is weird as we have e2e tests testing the scenario with the command line? Does it also fail if you pass the package name via the `--emit` flag?

**Comment by timotheeguerin** [comment]
Talked in the meeting and think I misunderstood the problem. Where you trying to reference the package itself?
```
/package.json # name: tsEmitter
/src
  /tsEmitter.ts # Emitter entrypoint
/samples
  main.cadl
  cadl-project.json # -> want to have emitters: tsEmitter
```

**Comment by xirzec** [comment]
> Talked in the meeting and think I misunderstood the problem. Where you trying to reference the package itself?

Exactly so! I want to be able to bootstrap calling cadl from within the emitter package I am authoring without having to create a secondary project that depends on my emitter package to test it.
