### ISSUE TITLE
console.log in emitter code breaks VS Code extension

### ISSUE THREAD

**Issue by xirzec** [microsoft/cadl#291]
If you `console.log` from inside of your ` $onEmit` function, you end up breaking the VS Code extension because it uses stdout to communicate to the client, so you end up having the extension silently freeze up and stop accepting messages.

@nguerrera had the patience of a saint figuring this out - it only took us a little over an hour of debugging 😆 

I think in this case, overriding `console.log` in the server process to failfast or at least print some kind of diagnostic warning you not to do this would be sufficient. Style points for redirecting the message appropriately.

**Comment by nguerrera** [comment]
Another possiblity is that we may be able to switch back to node ipc from stdio for the lsp pipe. It didn't work for us originally because VS code was stuck on node 12 and node 12 -> node 14 communication was broken.

But we still need to support stdio for other editors so this would still be worth doing regardless.

**Comment by nguerrera** [comment]
I believe it is better when it works. At one time it wouldn't work for us, but I think that shouldn't be an issue anymore. I propose that we try switching VS Code client to IPC *and* harden against/redirect console.log for other editors that would still need to use stdio.

**Comment by nguerrera** [comment]
It occurs to me that we have to figure out how vscode-languageserver writes to stdio and not block/redirect that. 😁

**Comment by nguerrera** [comment]
Although I guess it doesn't use console.log as we hijacked that in our debugging session successfully and got as far as invoking the emitter and finding its log.

**Comment by xirzec** [comment]
Thanks for the fix! 👍
