### ISSUE TITLE
Improve documentation of the @visibility and @withVisibility decorators

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#298]
I believe our visibility framework is not well defined / documented, both at the "core" level, where it is just a flexible capability to be used by emitters in any way they choose, and at the emitter level, where e.g. the autorest and openapi3 emitters impart specific meaning to certain visibility tags.

At the core level, here some specific issues to address:

- The definition of withVisibility is a bit loose / vague. In fact, there is no actual description for it outside of a comment in the code example:
   ```
   // The spread operator will copy all the properties of Dog into ReadDog,
   // and withVisibility will remove any that don't match the current
   // visibility setting
   ```

   I think this describes _a use case_ of @withVisibility but not the actual meaning of the decorator. My stab at a better description:
 
   > @withVisibility is a decorator that can be applied to a model to specify that it contains only properties with the specified visibility.  Any property without this visibility is omitted.

   This makes it clear that for
   ```
   @withVisibility("write")
   model WriteDog {
     ...Dog;
 
     @visibility(“read”)
     foo: string;
   }
   ```
   WriteDog does not contain “foo”.  In other words, it describes the decorator in terms of its effect on the model, not on spread.

- When a property has no explicit `@visibility`, what is the default value?  I think the default is "all values".  In other words, `@withVisibility(x)` will consider a property with no explicit `@visibility` to have "x".

- When multiple flags are specified to @withVisibility, do we select all properties with _any_ of these visibility flags or _all_ of these flags?

For the openAPI emitters, we should describe the specific visibility values it defines and how they are treated.  It is a bit tricky because openAPI actually _adds_ semantics to `@visibilty` -- by making properties `readOnly` even if there is no explicit `@withVisibility`. So we just need to clearly describe this.

**Comment by markcowl** [comment]
I think this is mainly about the `@withVisibility` decorator, as I think we want visibility in core to be a loose tagging concept, but we want specific applications to use it in a predictable fashion.  For example, if we allowed logical expressions in the `@withVisibility` tag parameters ```@withVisibility("read" || none)``` or ```@withVisibility("create" && "update")```  this would go a long way toward disambiguating the meaning in specific instances.

Note that the ```@withVisibility``` functionality could also be implemented with projections, which would also make the usage clearer.

In ARM, we have been translating the visibility values directly into `x-ms-mutability`.  The meaning there is roughly what you have suggested:

no setting = appears in PUT requests, PATCH requests and GET/PUT/PATCH responses
create = appears in PUT requests, and can be used when creating a new resource
update == appears in PUT and PATCH requests, can be used in PUT to set properties for new or existing resources
read == appears in GET/PUT/PATCH responses.  Note that a visibility of just "read" is represented as 'readOnly' in swagger.

**Comment by annelo-msft** [comment]
Thanks for linking this, @mikekistler!  I'm curious about the path forward here for code generators regarding what set of visibility values to support, and who will decide this.  Passing through OpenAPI values makes sense for the OpenAPI emitters, but for language emitters that go straight from Cadl -> SDK, is that the best set of values?  It feels like a decision that would ultimately come from the API Stewardship board regarding what needs to be represented for Azure and what the recommendations are, but would that fall under their purview or Cadl's?  @JeffreyRichter, @markcowl, thoughts?

**Comment by annelo-msft** [comment]
I'll add this question here, since it's come up on another channel as well - how should we think about visibility and polymorphism together?  Is it possible for a base type to be an output model and a derived type to be a round-trip model?  This has practical implications for how we design and generate model types.  It seems like if we wanted to enforce consistency in inherited types, we wouldn't be able to do this via compiler warnings if visibility isn't something Cadl is aware of.  Is this a concern?  @bterlson, @AlexanderSher

**Comment by JeffreyRichter** [comment]
Why is this even called "visibility"? It's more about property "usage"; the properties are always "visible".
