### ISSUE TITLE
Intersection of two template parameters not allowed (why not?)

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#301]
```cadl (stuff.cadl)
interface A<B, C> {
  stuff(): B & C;
}
```

$> cadl compile stuff.cadl 
error intersect-non-model: Cannot intersect non-model types (including union types).

**Comment by markcowl** [comment]
Is there no instantiation inside this doc?

**Comment by nguerrera** [comment]
We support `{...B, ...C}` so this should work too in my opinion.

**Comment by johanste** [comment]
> Is there no instantiation inside this doc?

No.

**Comment by bterlson** [comment]
Bug. Squash it.
