### ISSUE TITLE
Consider making @path optional based on info in @route

### ISSUE THREAD

**Issue by Petermarcu** [microsoft/cadl#306]
In many/most/all cases, the parameters to a route are identified in the route and the @path attribute could be considered redundant. 

Here, why do I need @path on id?
```
 @route("widgets/{id}") read(@path id: string): Widget | Error;
```

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCm5hbWVzcGFjZSBEZW1vxxg7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdAewogIEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsdWRcQMxVVjb2Rly0BtZXNzYWdlymTEOnJvdXRlKCIiKQppbnRlcmbkAL3mAJjnAL%2FFSsonIEDkALNsaXN0KCk6xypbXSB8xnfEZ8gsd8Uccy97aWR9IikgcmVhZChAcGF0aOsA6MlD1EHEbXBvc3QgY3JlYXRlKEBib2R5IMQFyDbdP2N1c3RvbUdldOgAtckR6gC6yjh9

**Comment by markcowl** [comment]
In interfaces, we are moving away from using the complexx route statements and instead using `@autoroute` and the keys and path segments encoded in the model type.

For namespace-based operations and other uses of `@route` though the extra metadata tag does feel redundant.

**Comment by bterlson** [comment]
Even in an autoroute world there will be the redundancy for any custom methods you want to add I think?
