### ISSUE TITLE
Semicolon after suppression has poor recovery behavior

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#319]
Subsequent declarations are marked as invalid, but we should only report the missing semicolon.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwojc3VwcHJlc3MgInByb2plY3Rpb25zLWFyZS1leHBlcmltZW50YWwiOwrKHyBXaWRnZXQjdG9UeXBlc2NyaXB0IHsKICB0byB7CgogIH0KfQoKQGVycm9yIG1vZGVsIEXFDMQkY29kZTogaW50MzI7CiAgbWVzc2FnZTogc3RyaW5nOwp9)

**Comment by timotheeguerin** [comment]
Seems to actually be the case if anything is passed to a directive that isn't a string literal or an identifier.
