### ISSUE TITLE
Request body for versioned schema includes fields from later versions

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#320]
I suspect this has something to do with spread? See the request body for the patch endpoint on line 89 of `openapi.v1.json`.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCkDHL2VkKFZFUlNJT05TKQpuYW1lc3BhY2UgRGVtb8ctOwoKYWxpYXMgyCggPSAidjEiIHwgInYyxGx1c2luZyBDYWRsLkh0dHA7zBFSZXN0OwoKbW9kZWwg5wCGewogIEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZMVuYmx1ZSLEGUBhZGRlZCjEfykg5AC1ykd9CgpAZXJyb3IgxnNFxQzEcmNvZGXLXW1lc3NhZ846aW50ZXJm5AEA5gCq5wECIG1peGVzIFJlc291cmNl5ADUxQlPcGVyYXRpb25zPMYwLMZvPsVw7AClxA9nZXTEB3JvdXRlKCJjdXN0b21HZXTFHckOKCk6x3w7Cn0%3D)

**Comment by timotheeguerin** [comment]
Think this might be the same underlying issue as @nguerrera investigated here https://github.com/microsoft/cadl/issues/244
