### ISSUE TITLE
ApiView emitter for Cadl (also, add to PlayGround)

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#326]
Since this is being implemented for Swagger, we could hook into this through emitting swagger first, or we could create a cadl-native version.

**Comment by allenjzhang** [comment]
https://github.com/Azure/azure-sdk-tools/issues/1208

**Comment by tjprescott** [comment]
This is completed. https://github.com/Azure/azure-sdk-tools/pull/4160

However, I can't seem to close this issue so I'll defer to @allenjzhang or @markcowl
