### ISSUE TITLE
Union base type with no properties produce no output

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#328]
```
import "@cadl-lang/rest";

op read(): A;

@discriminator("foo")
model A {
}

model B extends A {
  foo: "B";
  b: string;
}

model C extends A {
  foo: "C";
  c: string;
}

```

Result in 
```json
"/": {
      "get": {
        "operationId": "read",
        "parameters": [],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    }
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKb3AgcmVhZCgpOiBBOwoKQGRpc2NyaW1pbmF0b3IoImZvbyIpCm1vZGVsIEEgewp9CscNQiBleHRlbmRzxRcgIGZvbzogIkIiOwogIGI6IHN0cmluZzvKMEPVMEPFMGPMMA%3D%3D)

**Comment by markcowl** [comment]
- make sure that this works if there are child models and no discriminator
- - check cadl-autorest
- add regression tests

**Comment by timotheeguerin** [comment]
Same result with cadl-autorest and without `@discriminator`
