### ISSUE TITLE
Convert samples to unit tests where appropriate

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#33]
Some of our "samples" pre-date the compilation unit test harness we have now. And they're not really samples that someone would want to emulate, more like edge cases that we can't regress. One example is the 'recursive' sample. We should go through the samples and convert those that would be better as unit tests to unit tests.

- [x] recursive.cadl https://github.com/microsoft/cadl/pull/35

**Comment by timotheeguerin** [comment]
Not sure actually there is other samples that don't belong in samples but in unit test instead, feels like each one has some value to show how to use certain things

**Comment by nguerrera** [comment]
OK, then I guess we can close this when #35 merges and just keep it in mind when making further changes. 😁
