### ISSUE TITLE
cadl code install errors out

### ISSUE THREAD

**Issue by fhinkel** [microsoft/cadl#331]
As requested by @bterlson, I tried to work through the Readme.

MacOS, node v14.19.0, VS Code 1.65

I'm assuming "Using Docker" is an alternative and skip this step from the README.

```
npx cadl code install  
Cadl compiler v0.29.0

+ cadl-vscode@0.13.0
added 1 package from 1 contributor and audited 1 package in 0.341s
found 0 vulnerabilities

error: Command 'code' not found.
```

Thought maybe it should be `cadl vscode` as described on https://github.com/microsoft/cadl/tree/main/packages/cadl-vscode but according to the error message that's an `Unknown argument: vscode`. Trying again with a global `cadl` and without `npx`, but same error. Not sure if there's a regression or something specific about my OS/Node version.

**Comment by timotheeguerin** [comment]
@fhinkel do you have vscode `code` commnad available on the path? See this for installing it https://code.visualstudio.com/docs/setup/mac
I remember on MacOS it wouldn't do it automatically

**Comment by fhinkel** [comment]
> @fhinkel do you have vscode `code` commnad available on the path? See this for installing it https://code.visualstudio.com/docs/setup/mac I remember on MacOS it wouldn't do it automatically

That's it! Thanks, will follow the setup described in the link and try again :) Closing in favor of https://github.com/microsoft/cadl/issues/332
