### ISSUE TITLE
README doesn't specify emitter

### ISSUE THREAD

**Issue by fhinkel** [microsoft/cadl#340]
Reviewing the README, cc @bterlson: 

I'm following step 7 in `Getting started` in the Readme: `npx cadl compile .`
Without `--emit` or a config file, I'm not getting any output: 

```
npx cadl compile .
Cadl compiler v0.29.0

Compilation completed successfully, output files are in cadl-output.

No emitter was configured, no output was generated. Use `--emit <emitterName>` to pick emitter or specify it in the cadl config.
```

I did `npm i @cadl-lang/openapi3` and tried 
```
 npx cadl compile . --emit=@cadl-lang/openapi3
Cadl compiler v0.29.0

Diagnostics were reported during compilation:

error file-load: Cannot find package '@cadl-lang/openapi' imported from /Users/fhinkelmann/code/microsoft/cadl-project/node_modules/@cadl-lang/openapi3/dist/src/openapi.js
error emitter-not-found: Cannot find emitter with name default in @cadl-lang/openapi3

Found 2 errors.
```

**Comment by fhinkel** [comment]
Should we include 
`npm i   @cadl-lang/openapi  @cadl-lang/versioning` in the `Getting started` section to fix this? Or is there a problem with the package dependencies not getting installed with `openapi3`?

**Comment by fhinkel** [comment]
I'm using node v14.19.1 (npm v6.14.16). The Readme says to use 14.
Since `npm 6`, install does a save by default. Here's my package.json after installing the two dependencies manually: 
```
{
  "name": "cadl-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@cadl-lang/compiler": "^0.29.0",
    "@cadl-lang/openapi": "^0.7.0",
    "@cadl-lang/openapi3": "^0.9.0",
    "@cadl-lang/rest": "^0.12.0",
    "@cadl-lang/versioning": "^0.3.2"
  }
}
```

**Comment by fhinkel** [comment]
And I think `--emit` is missing from the Readme either way.

**Comment by timotheeguerin** [comment]
Is those error still happening with the package.json you are sharing?

error file-load: Cannot find package '@cadl-lang/openapi' imported from /Users/fhinkelmann/code/microsoft/cadl-project/node_modules/@cadl-lang/openapi3/dist/src/openapi.js
error emitter-not-found: Cannot find emitter with name default in @cadl-lang/openapi3

**Comment by fhinkel** [comment]
If you're fine with doing `npm i @cadl-lang/openapi @cadl-lang/versioning`, then it's just a documentation issue.

**Comment by timotheeguerin** [comment]
This is something we discussed when choosing peer dependencies, npm 7 and above will install them automatically so you won't need to install those packages when you depend on the openapi3 package. We should definitly update the doc with the recommended version of node and npm as well as describing this issue.
