### ISSUE TITLE
Improvement request: `cadl vs install` clarity

### ISSUE THREAD

**Issue by AMSDavis** [microsoft/cadl#342]
Background: I have multiple versions of visual studio installed including 2019 and 2022 as well as preview versions.

When I ran `cadl vs install` I saw the prompt to install to 2019, however I actually wanted to target 2022. It wasn't clear that the installer was going to attempt to install both i sequence.

Ask: It would be helpful to have a single prompt for which versions to target, or at least a warning that the installer will try to install for all versions of visual studio and to simply skip the versions that aren't desired.

**Comment by abatishchev** [comment]
+1, just ran into the same issue: `cadl vs install` installs an extension for VS 2019 without prompting which version I'd like which is 2022:

![image](https://user-images.githubusercontent.com/351644/160682929-a133d40c-f5f4-425c-a151-03a4cb79672c.png)

**Comment by abatishchev** [comment]
Oh, wow. Indeed! No. 2 worked for me: - I cancelled the installation for 2019 (I keep it just in case something goes wrong; by now I probably just should uninstall it altogether) and then it started an installation for 2022.

I'd wish there was an option like:

- cadl vs install -v 2022
- cadl vs install --version 2022
