### ISSUE TITLE
Request: Output view for CADL program structure

### ISSUE THREAD

**Issue by xirzec** [microsoft/cadl#343]
I've been toying with CADL a lot and sometimes it is hard to intuit the shape of the object graph being generated from different input. 

Similar to how we have the Playground that shows generated OpenAPI, I think it would be cool to have some kind of tree structure like how the TS Playground shows you the AST:

<img width="256" alt="TS Playground AST View" src="https://user-images.githubusercontent.com/639216/159084416-6bfc47d0-0795-40e1-81c5-917b6442bce3.png">

This would help with understanding how to spider particular data structures in CADL, e.g. showing how Model types contain ModelPropertyTypes which in turn reference the specific type of that property.

Right now there's a lot of debugging to figure this stuff out, and not all shapes are intuitive, like how parameters from getAllRoutes() are ModelPropertyTypes (so they can have a name, optionality, and default value I presume.)

**Comment by markcowl** [comment]
- need to figure out a good visualization of the type graph
