### ISSUE TITLE
Parent key names are not uniquified when constructing paths

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#352]
The following file: 

```cadl
model Parent {
  @key
  @Cadl.Rest.segment("parents")
  name: string;
}

@Cadl.Rest.parentResource(Parent)
model Child {
  @key
  @Cadl.Rest.segment("children")
  name: string;
}
interface Existing mixes Cadl.Rest.Resource.ResourceOperations<Child, {}> {}
```

[(playground link)](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKbW9kZWwgUGFyZW50IHsKICBAa2V5xAdDYWRsLlJlc3Quc2VnbWVudCgicMUmcyIpCiAgbmFtZTogc3RyaW5nOwp9CgrLMcYoUmVzb3VyY2Uoxl0px2tDaGlsZN9qImPEJXJlbtVraW50ZXJmYWNlIEV4aXN0aW5nIG1peGVzIMpJyHzJCU9wZXJhdGlvbnM85QCBLCB7fT4ge30%3D)

silently drops the item paths for the `Child` model and exposes the following paths:

```
/children/{name}
/parents/{name}/children
```

We should make parent keys unique by prepending the model name in the case of conflicts - e.g:

`/parents/{parentName}/children/{name}`

(we may have to do further disambiguation in degenerate cases)

It is not a valid assumption to assume that model key properties are always unique in any given parent/child relationship.

**Comment by johanste** [comment]
@daviwil, fyi.

**Comment by daviwil** [comment]
@johanste You must provide a key name to the `@key` decorator to avoid this, I don't think we can do it for the author automatically.  In fact, for the ARM library I made it mandatory to specify a key name, so we might need to do the same thing for the lower-level libraries too.

**Comment by johanste** [comment]
Even if you specify the key name, the key name will differ depending on the context it is being used in. Unless you expect all keys to always be qualified by the model name to avoid collisions.

**Comment by johanste** [comment]
...but.... either way... the fact that there is a silent failure/the wrong endpoints get emitted without any complaints from the compilation is problematic.

**Comment by daviwil** [comment]
Yeah, we definitely shouldn't let it happen without complaint.  I'll add a check to raise a diagnostic if any parent types of a resource have a conflicting key name.

**Comment by daviwil** [comment]
Closing in favor of https://github.com/microsoft/cadl/issues/462 which addresses the same issue.
