### ISSUE TITLE
[Documentation] Missing guide for using CADL within build pipelines.

### ISSUE THREAD

**Issue by AMSDavis** [microsoft/cadl#359]
There doesn't appear to be a guide yet documenting the steps needed to utilize CADL in a build pipeline such as ADO or Github, etc.

It would be useful to document the steps needed, since they differ slightly from the steps needed to build locally.

**Comment by markcowl** [comment]
Filed this issue in the private repo, as I believe this is MS-specific: https://github.com/Azure/cadl-azure/issues/1315

Closing in favor of tracking the issue there.
