### ISSUE TITLE
Show more info on VS extension activation failure.

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#361]
See https://github.com/microsoft/cadl/issues/358#issuecomment-1078476294

We should dump the stack trace of the exception and ask the user to file a bug on this repo, just like we do for internal compiler errors.

**Comment by nguerrera** [comment]
@milopezc I'm having trouble getting this to work. I return a context with failure message, but nothing happens when I click on the generic message. I don't know how to find the message I returned. Also, I do still see a yellow bar with link to the very verbose activity log afterwards in VS 2022.

**Comment by nguerrera** [comment]
Ah, so if I click on the exclamation mark bottom left afterwards, then I can click through and get the details in the output window, but not if I click on the original bubble, it seems.

**Comment by milopezc** [comment]
> Ah, so if I click on the exclamation mark bottom left afterwards, then I can click through and get the details in the output window, but not if I click on the original bubble, it seems.

Correct, sorry for not clarifying before.

**Comment by nguerrera** [comment]
@milopezc Thanks for confirming. Consider it small feedback that it would be nice if you could click on the original bubble too. I suspect the current way things are will lead to confusing conversations while trying to get that FailureMessage when users hit problems.
