### ISSUE TITLE
In-context documentation for decorators

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#364]
We should allow the user to obtain a description and possibly other information for a decorator in VS/VSCode, with right-click or some other gesture.

**Comment by nguerrera** [comment]
I believe the experience here is covered by https://github.com/Azure/cadl-azure/issues/614 and https://github.com/microsoft/cadl/issues/313

@mikekistler Can you look at the screenshots and descriptions and let me know if you agree or if this is asking for more than those are asking?

I'll close this as a duplicate, but feel free to reopen if there's something missing, or maybe add comments to the existing issues if there are requirements you'd like to add?

**Comment by mikekistler** [comment]
What I'm asking for here is a _description_ of the decorator, something like what is shown here for `Object.keys`:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/85643503/161335253-6ac24be1-f9d7-463a-8f39-fba6480fffd1.png">

I think this is more than signature / hover help, because AFAIK there is no established mechanism for a decorator to specify its description, so I think this needs to be added _and then_ all the decorators we currently have must be modified to use this mechanism to provide a description.

Do you see all of this as being covered by the above two issues?

**Comment by nguerrera** [comment]
Yes.

**Comment by nguerrera** [comment]
https://github.com/microsoft/cadl/issues/131 is also related.

**Comment by nguerrera** [comment]
> AFAIK there is no established mechanism for a decorator to specify its description

This is discussed on the issue. Signature help requires a design for specifying this metadata.

**Comment by nguerrera** [comment]
The metadata is both the signature (typing if you prefer) and description.

**Comment by nguerrera** [comment]
I added this comment https://github.com/Azure/cadl-azure/issues/614#issuecomment-1086293531 to clarify
