### ISSUE TITLE
Caching for demanding computation and duplicate diagnostics.

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#368]
We currently have 2 issues without a good solution:
1. How can we cache compute heavy resolution so it can be reused across validator, emitters, etc. For example `mapChildModels`
2. Some of the resolutions will emit diagnostics(For example `getRoutes` from rest library). if this function is called twice it will emit the same diagnostics multiple times. This can easily happen if you have 2 emitters each calling `getRoutes` and now end up with duplicate diagnostics.
   - Those resolution would also not emit any diagnostics if you don't have an emitter calling it.

Problem with caching:
- Invalidating the cache in the case of program mutation.
- From Brian: caching to prevent duplicated diagnostics seems like solving the problem at the wrong layer.

**Comment by timotheeguerin** [comment]
- Move validation to onValidate. Don't emit diagnostics from library helper getter.
- Move mapChildModels to be built in the compiler using `children` prop on model type
   - Check projection.ts for child models

Future idea?
Deduplicate diagnostics using exact location(line, col)

```cadl
model Foo {
  id: int32;
  @added(v2)
  name: string; 
}
```
  ```
  error int32suffix: cannot have int32 without suffix
  ```

**Comment by nguerrera** [comment]
(Removing my assignment since I think that was covering the discussion we already had to come to the conclusions above.)
