### ISSUE TITLE
Template parameters constraints

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#377]
## Problem

We currently do not support template constraints which leads to workaround to do any validation on the template parameters with decorators(See #375 for example). With the workaround we cannot get the correct location of the error.

For example with a decorator called `@validateTIsStringLiteral` which validate the template argument is a string literal 
```cadl
@validateTIsStringLiteral(T)
model Text<T> {}

model Bar {}
^ error would show up here

alias Foo = Text<Bar>
                 ^ error should really be here
```

## Solution

Most likely depend on the subtype relationship and assignment validation.

Add `is <constraint>` after the template argument 

```cadl
model Foo<T is [constraint]> {}
```

### Example

1. Validate the template argument is `string` or a string literal
  ```
  model Foo<T is string> {}
  ```

2. Validate the model as properties
  ```
  model Foo<T is {foo: string}> {}
  ```

3. Custom constraints with decorator. Seperate issue #602

**Comment by markcowl** [comment]
Agreement on (1) and (2) as just fine, (3) Needs some additional work.  Agreed to look at doing better targeting on these errors (targeting the decorator call in the template instantiation and the template instantiation) as an alternative

**Comment by bterlson** [comment]
For 2 I think we want extends rather than is since presumably it will do a subtype check?

**Comment by timotheeguerin** [comment]
I think we definitely need is but maybe extends seperately. With extends you cannot do something like

```
model Foo<T is {foo: string}> {}

model MyFooable {  foo: "bar" }
Foo<MyFooable>
```

you'd have to 
```
model Fooable {foo: string}
model Foo<T extends Fooable> {}

// and to use `extends all the time`

model MyFooable extends Fooable {
  foo: "bar"
}

Foo<MyFooable>
```

**Comment by bterlson** [comment]
I am not thinking of extends as an assertion that a model is literally extended from another model but that it is merely a subtype. To me this seems natural and aligns with similar constraints in TS (viz. Guerrera Rule). On the other hand is doesn't seem appropriate unless you need to pass exactly the type on the rhs.

**Comment by timotheeguerin** [comment]
I see, yeah I don't think supporting literal extends is import, definitely not as the first version. I do feel like however `extends` in that context would then be a bit confusing with our explicit meaning of `extends` for models.

**Comment by markcowl** [comment]
- completion over template parameters would be really nice

**Comment by markcowl** [comment]
Remaining design issues:
- exact vocabulary for cases (1) and (2) [conformance to a type shape]
- split off general function-based constraints into its own issue @timotheeguerin

**Comment by timotheeguerin** [comment]
# Dicussion left for this issue

Assumptions:

- Template constraint is using the subtype relation: which at this time is structural.

## `is` vs `extends` vs other?

```cadl
model Bar {name: string, value: string}
```

#### Using `is`

```cadl
// Using IS
model IsAString<T is string> {}
model HasFooProp<T is {foo: string}> {}
model HasBarProps<T is Bar> {}
```

#### Using `extends`

```cadl
model IsAString<T extends string> {}
model HasFooProp<T extends {foo: string}> {}
model HasBarProps<T extends Bar> {}
```

#### Other keyword/syntax

```cadl
// `:` symbol
model IsAString<T : string> {}

// Has keyword
model IsAString<T has string> {}

// CSharp style?
model IsAString<T> where T : string {}
```

#### Usage

```cadl
model TestIsAstring {
  // Valid
  a: IsAString<"abc">;
  b: IsAString<string>;

  // Error
  e1: IsAString<123>;
  e2: IsAString<int32>;
  e3: IsAString<{}>;
}

model MyModelWithFoo {foo: "abc"}
model TestHasFooProp {
  // Valid
  a: HasFooProp<{foo: "abc"}>;
  b: HasFooProp<{foo: string}>;
  b: HasFooProp<{foo: "abc", other: 123}>;
  b: HasFooProp<MyModelWithFoo>;

  // Error
  e1: HasFooProp<123>;
  e2: HasFooProp<int32>;
  e3: HasFooProp<{}>;
  e4: HasFooProp<{other: "abc"}>;
}

model MyModel { name: "abc", value: "def"}
model MyExtend extends Bar {}
model TestHasFooProp {
  // Valid
  a: HasFooProp<{name: "abc", value: "def"}>;
  b: HasFooProp<{name: "abc", value: "def", other: 123}>;
  b: HasFooProp<MyModel>;
  b: HasFooProp<MyExtend>;

  // Error
  e1: HasFooProp<123>;
  e2: HasFooProp<int32>;
  e3: HasFooProp<{}>;
  e4: HasFooProp<{name: "abc"}>;
  e5: HasFooProp<{other: "abc"}>;
}
```

#### Issues with each keyword syntax:

- `is`: Does `is` mean exactly `is` and not necessarly a subtype?
- `extends`: In that context feels too close to `model extends` which explicilty means inheritance and here would lead to confusion on why this is structural subtyping.
- `:`: 
- `has`: Another keyword to learn, which is why we removed `mixes`
- `where :`: Completely different syntax, another keyword, diverge more from Typescript "like"
