### ISSUE TITLE
Format misplaces namespace with commented attribute

### ISSUE THREAD

**Issue by abatishchev** [microsoft/cadl#381]
Input:

```
//@armNamespace
namespace Microsoft.Foo {
}
```

Run this command:

```
cadl format **\*.cadl
```

Result:

```
namespace Microsoft.//@armNamespace
Foo {
```

Run it again:

```
namespace Microsoft.Foo { //@armNamespace
}
```

**Comment by timotheeguerin** [comment]
Did get into this issue as well. Should have been fixed in https://github.com/microsoft/cadl/pull/374

**Comment by timotheeguerin** [comment]
https://aka.ms/trycadl playground is always using the current version of cadl (main branch) so the fix should be there. Please reopen if it is still happening for you there
