### ISSUE TITLE
Importing library with same helper method cause duplicate-symbol error

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#384]
Having 2 libraries or js files defining the same helper method cause a duplicate decorator error but those methods should be ignored. 

Errors: 
```
/Users/timotheeguerin/dev/azsdk/cadl/packages/samples/simple/lib1.js:1:1 - error duplicate-symbol: Duplicate name: "getDec"
/Users/timotheeguerin/dev/azsdk/cadl/packages/samples/simple/lib2.js:1:1 - error duplicate-symbol: Duplicate name: "getDec"
```

Repro

In `lib1.js` and `lib2.js`
```js
export function getDec(){}
```

In `main.cadl`
```cadl
import "./lib1.js";
import "./lib2.js";
```

**Comment by timotheeguerin** [comment]
Some discussion on this in  #382. The issue here is that every function exported by a library can be used in a projection.

**Comment by markcowl** [comment]
- use existing name conflict semantics (error on usage)
  - require namespace
  - what do we do in the global namespace
- opt-in mechanism for js libraries being callable in projections? [Design Issue]

**Comment by timotheeguerin** [comment]
There is no issue when the package has a root namespace with `export const namespace`
