### ISSUE TITLE
Type for time period/interval in ISO 8601 format 

### ISSUE THREAD

**Issue by abatishchev** [microsoft/cadl#393]
### Problem

Microsoft REST API Guideline (sections [11.4. Durations](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#114-durations) and [11.5. Intervals](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#115-intervals)) in general and ARM in particular require to express time period or duration in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) format:

> P[n]Y[n]M[n]DT[n]H[n]M[n]S

Examples:

- PT5M
- PT1H30M

### Solution

Currently (as of version 0.30.0), Cadl [built-in types](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#built-in-models) don't seem to support such format in a way other than plain `string`. Given the official Guideline is quite opinionated and doesn't offer other options, Cadl could and should provide native support for such.

### Workaround

To unlock me meanwhile, what would be the suitable workaround? A `string` with a `@pattern(regex)`?

**Comment by timotheeguerin** [comment]
we have a `duration` which does seem to not be documented in the built-in type list but should cover that

**Comment by abatishchev** [comment]
@timotheeguerin yes, please! and can you please point me to a test or a sample so I could start using it?

**Comment by timotheeguerin** [comment]
Can't find it used in a sample in the public repo. One thing to add when documenting it. 
It is defined here https://github.com/microsoft/cadl/blob/74addeed2e7dd3cd27d1047f50dcab49463333ed/packages/compiler/lib/lib.cadl#L63

But in the azure services sample you can see here https://github.com/Azure/cadl-azure/blob/3da85471f09591dd1f28000788225a079ce875a0/packages/cadl-samples/data-plane/searchservice/skills.models.cadl#L477

**Comment by abatishchev** [comment]
Found #48. Then let's use this issue to just update the `documentation`, hence the right tag is already here. Thanks!

**Comment by abatishchev** [comment]
Can you share an example? Would `5s` be translated to `PT5S` per the ISO standard / API guidline?

**Comment by timotheeguerin** [comment]
are you talking about the controller code for this?

**Comment by bterlson** [comment]
I think the docs are somewhat confusing, the e.g. might make you think the type is formatted a particular way. A duration is just a unit type which holds a span of time. How it is formatted on the wire is up to emitters, and presumably we would mostly use ISO8601 duration format there.
