### ISSUE TITLE
Support extending existing enums

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#395]
It should be possible to declare an enum using another enum as a starting point. Right now the only thing that can be done is copy/paste the enum you want to extend. Options for this mechanism include spread-like syntax or `enum extends` syntax.

Open questions include:
* How does this affect assignability? E.g. if I have `enum Child extends Base { }`, can I pass `Base.A` for `Child`? Can I pass `Child.A` for `Base` when A came from Base?
* How does this overlap with the Azure notion of "extensible enums", if at all? E.g. do we need some kind of opt-in mechanism for an enum to allow others to extend it?

Somewhat of an aside but, assuming `extends` syntax for this, you could imagine using this to create the notion of extensible enum we have today. Recall that it involves declaring both an enum and a string and passing the enum to a decorator on the string. We could perhaps have:

```
enum AnyStringButProbablyOneOfTheseStrings extends string {
  Good,
  Bad,
}
```

Which has a good feeling to me but I haven't thought through all the implications of yet.

**Comment by bterlson** [comment]
A strong argument against `extends` for this is that in all other cases `extends` creates subclasses. For enums, it does the opposite (if anything).

Using spread syntax is a possibility, but we need to decide if it's sugar (i.e. Base.A isn't the same type as Child.A because it's as if you declared them in the different enums) or if there is some sort of more meaningful relationship between these enums.

My opinion is that the former is the only workable solution as the latter is unlikely to be representable in any target language.

**Comment by bterlson** [comment]
Cards on the table: I'm heavily leaning toward the `spread sugar` approach to solve the main scenario.

One other note is that OP calls out a way to do "extensible enums" by extending some base type. This is a fine usage of `extends` because it does in fact create a subtype in the sense that the enums values are all subtypes of the extended type.

**Comment by markcowl** [comment]
Alternately we could use something closer to set semantics, like contains
```
enum bar {
  One: "1", 
  Two: "2", 
  Three: "3"
}
enum foo contains bar  {
  Four: "4", 
  Five: "5", 
  Six: "6"
}
```

I think if we use spread sugar, like

```
enum foo {
  ... bar;
  Four: "4", 
  Five: "5", 
  Six: "6"
}
```

then it is fair that `foo.One !== bar.One`, but it should be the case that `foo.One.name === bar.One.name` and `foo.One.value === bar.One.value`

**Comment by markcowl** [comment]
Design Meeting Consensus was to go with the spread syntax, above

**Comment by markcowl** [comment]
Closing for implementation issue #591
