### ISSUE TITLE
Address decorator garden path syntax concerns

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#397]
Cadl syntax has decorators occurring prior to cadl declarations. Cadl programs that make extensive usage of decorators run into an issue where the actual thing being decorated is buried under a pile of decorators. This becomes especially problematic when the semantics of a decorator depend on the construct being decorated, meaning users must skip over all the decorators to find the declaration, then return to the top and re-read everything. This issue exists for top-level declarations and for member declarations.

We have previously discussed an approach that would solve the declarations with blocks: namely allowing decorators inside the body of the thing being decorated. However this has issues (e.g. requires another sigil to disambiguate with decorators on the things inside the block).

Another option is to let decorators follow the things they decorate, but before any block.

```
import "@cadl-lang/rest";

namespace DemoService
  @serviceTitle("Widget Service")
  @serviceVersion("xxx");

using Cadl.Http;
using Cadl.Rest;

model Widget {
  id: string @key;
  weight: int32;
  color: "red" | "blue";
}

model Error @error {
  code: int32;
  message: string;
}

interface WidgetService mixes Resource.ResourceOperations<Widget, Error> {
  customGet(): Widget @get @route("customGet");
}
```

Once concern with this approach is I believe it precludes doing any decorators "in expression position" which is a line we've so far held and is probably fine. But even decorating expression forms of declarations could become problematic from a readability perspective since you could end up with things like `model Foo { property: model someModel @modelDec { } @propDec }` become difficult to parse for human brains.

I think the main question with this approach is, do we allow decorators in either position, the current position and the position proposed here? I am on the fence - on the one hand, having multiple places to place a decorator just means the prettier plugin has to pick and so why did we bother. On the other hand, I have a slight preference for short operation and model property decorators to precede the identifier, e.g. I like `@get custom(): OkResponse<Cat>` over `custom(): OkResponse<Cat> @get`.

**Comment by timotheeguerin** [comment]
More complex use case
```cadl
  // Current
  @doc("""Returns a pet. Supports eTags. This is very very long 
      This is very very long 
      This is very very long 
      This is very very long 
      This is very very long """)
  @post
  @route("/custom")
  op read(
    @doc("Some very long doc for id that") 
    @format("odd")
    id: int32): OkResponse<Pet> | NotModified<Pet> | Error;


  // After
  op read(
    id: int32 
      @doc("Some very long doc for id that") 
      @format("odd")
    ): OkResponse<Pet> | NotModified<Pet> | Error
    @doc("""Returns a pet. Supports eTags. This is very very long 
    This is very very long 
    This is very very long 
    This is very very long 
    This is very very long """);
    @post
    @route("/custom")
    
  // Before parentheses
  op read
    @doc("""Returns a pet. Supports eTags. This is very very long 
    This is very very long 
    This is very very long 
    This is very very long 
    This is very very long """);
    @post
    @route("/custom") (
      id: int32 
        @doc("Some very long doc for id that") 
        @format("odd")
    ): OkResponse<Pet> | NotModified<Pet> | Error
    
```

Problems: 
- Allowing both: error recovery: does it belong to previous or next statement/property
  ```cadl
  model PetId {
    foo: string
  
  
  
    // Some comment
    @doc("ABC") 
    petId: int32;
  }
  ```
- New syntax:
  - Better for properties?
  - Worst for `@get op`

Abstain change for now

**Comment by bterlson** [comment]
I think we can close this for now as we're not interested in pursuing this for now due to error recovery concerns. Additionally, we believe the only improvement would be to allow decorators both before and after declarations as certain decorators really want to come before, but this adds a lot of complexity for reading/writing/formatting/linting/etc.

Feel free to reopen if I got anything wrong!
