### ISSUE TITLE
Versioning sample broken in playground

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#398]
There is no output.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCkDHL2VkKFZFUlNJT05TKQpuYW1lc3BhY2UgRGVtb8ctOwoKYWxpYXMgyCggPSAidjEiIHwgInYyxGx1c2luZyBDYWRsLkh0dHA7zBFSZXN0OwoKbW9kZWwg5wCGewogIEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZMVuYmx1ZSLEGUBhZGRlZCjEfykg5AC1ykd9CgpAZXJyb3IgxnNFxQzEcmNvZGXLXW1lc3NhZ846aW50ZXJm5AEA5gCq5wECIG1peGVzIFJlc291cmNl5ADUxQlPcGVyYXRpb25zPMYwLMZvPsVw7AClxA9nZXTEB3JvdXRlKCJjdXN0b21HZXTFHckOKCk6x3w7Cn0%3D)

**Comment by timotheeguerin** [comment]
Error when using the same code locally 
![image](https://user-images.githubusercontent.com/1031227/161335374-f801877c-d701-459e-8385-07ef54e55b4b.png)

2 things to solve: 
1. This error
2. Why it doesn't show up in the playground.

**Comment by timotheeguerin** [comment]
Think that bug might be related to the other spread issue under the scene. Might be able to work around it by ignoring this requirement when things don't have namespace

**Comment by timotheeguerin** [comment]
Actually this seems to be causes by interfaces not having the namespace that they were defined it
