### ISSUE TITLE
Bogus "<unknown location>:1:1 - error intersect-non-model: Cannot intersect non-model types (including union types)." error message.

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#402]
The following code gives me a mysterious error:

```cadl
import "@cadl-lang/rest";

using Cadl.Http;

model Foo {
  name: string;

  size: int32;
}

model Empty {};

model SomeError {};

interface LifetimeOperations<
    TResource, 
    TRepeatableRequests=Empty,
    TError=SomeError>
{ 

    read(): TResource | { @statusCode _: 200; } & TError;
}

@route("/xxx")
interface X mixes LifetimeOperations<{}, 
    {}>{};
```
```
Diagnostics were reported during compilation:

<unknown location>:1:1 - error intersect-non-model: Cannot intersect non-model types (including union types).
```
 

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKbW9kZWwgRm9vIHsKICBuYW1lOiBzdHJpbmc7CgogIHNpemU6IGludDMyOwp9yC9FbXB0eSB7fclAU29tZUVycm9yxhVpbnRlcmZhY2UgTGlmZXRpbWVPcGVyYXRpb25zPAogICAgVFJlc291cmNlLCDIEHBlYXRhYmxlUmVxdWVzdHM9xWYsxh%2FFXT3JZz4KeyDkAJ8gIHJlYWQoKTrKUSB8IHsgQHN0YXR1c0NvZGUgXzogMjAwOyB9ICbHSOUAykByb3V0ZSgiL3h4eCIp6wCzWCBtaXhlc%2FQAu3t95wCve30%2B5ADp)

Swapping out the default value for the TError parameter to `{}` makes things compile.

**Comment by johanste** [comment]
[Simplified repro](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKbW9kZWwgRW1wdHkge307CgppbnRlcmZhY2UgTGlmZXRpbWVPcGVyYXRpb25zPAogICAgVFJlc291cmNlLCDGEEVycm9yPcVEPgp7IArFFnJlYWQoKTrKLiB8IHsgQHN0YXR1c0NvZGUgXzogMjAwOyB9ICbHRDsKfQoKQHJvdXRlKCIveHh4IinrAJBYIG1peGVz9ACYe30%2B5AC9)

**Comment by timotheeguerin** [comment]
I think this is the same problem as https://github.com/microsoft/cadl/issues/387
