### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#416]
- [x] Tutorial on writing an emitter 
- [x] Tutorial on creating a versioned API defn

**Comment by lmazuel** [comment]
I was looking for `friendlyName` today :)

**Comment by markcowl** [comment]
Moved the missing ref docs to #755

**Comment by rakshith91** [comment]
- [ ] documentation on friendlyName
- [ ] link to cadl playground on the README page
- [ ] add a sample here https://github.com/microsoft/cadl/blob/main/docs/cadl-for-openapi-dev.md#securitydefinitions--securityschemes-object
