### ISSUE TITLE
Just use extends

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#418]
Currently we have `model extends` and `interface mixes`. We used two verbs here because the semantics of extension and extension are different, the former establishes a type relationship while the latter is more of a mixin. This seems well motivated but there are a few factors that give me pause:

1. Typing `extends` instead of `mixes` is so common that we had to special case a good error.
2. #395 proposes something we'll want (IMO) where a user can create an enum starting from another enum, and that is really neither `extends` nor `mixes`.
3. I don't really like `mixes` that much 🤗

So what if we simply use the `extends` keyword for models, interfaces, and enums, and folks will just have to know that the semantics of `extends` means different things depending on what you are `extend`ing? While this may feel somewhat complicated, it is also complicated to have to remember the different keywords for extending (esp. since other languages don't draw this distinction in their syntax), so this might be a wash from a conceptual model complexity standpoint.

**Comment by timotheeguerin** [comment]
fixed in https://github.com/microsoft/cadl/pull/484
