### ISSUE TITLE
Cannot have a library with emitter and cadl files

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#420]
Right now if you want to have cadl files you need to set `cadlMain` to the cadl entrypoint of the library.

When loading a library the module resolver will see if `cadlMain` is set or use `main` otherwise as the library entrypoint.

However for emitter it loads the library as JS so if cadlMain is set to cadl file it fails to load it.

Solution
- `cadlMain`: Points to the `.cadl` entrypoint if any
- `main`: Points to the JS entrypoint

**Comment by nguerrera** [comment]
Does it not work for the entry point to be cadl and then that imports the .js? Or this is fallout from the change to make emitter configurable?

**Comment by timotheeguerin** [comment]
Yes that works for a library with `onValidate`. However for the emitter as its loaded separately it doesn't go through the Cadl files and expect a js file directly.
