### ISSUE TITLE
Allow file path(s) to be excluded from cadl format

### ISSUE THREAD

**Issue by AMSDavis** [microsoft/cadl#421]
I'm currently doing `cadl format -c **/*.cadl` however this is picking up on an additional cadl file included via the node modules that I don't actually have control over (resource.cadl). It's simple enough to run cadl format locally but this doesn't work if I want to enforce formatting in the build pipeline.

```
PS C:\redacted-path> cadl format -c **/*.cadl
Cadl compiler v0.29.0

Found 3 unformatted files:
 - src/path/cadl/main.cadl
 - src/path/cadl/node_modules/@cadl-lang/rest/lib/resource.cadl
 - src/path/cadl/foo.cadl
```

**Comment by timotheeguerin** [comment]
This is a good point. The formatter is a prettier plugin so if you format via prettier and check there you do get the full ignore functionality but the `cadl format` command doesn't

**Comment by AMSDavis** [comment]
I'm also having some issues where the command running in the pipeline appears to be picking up all 3 of the files, despite running `cadl format` to fix up the other two (main and foo). 
It's becoming a bit hard to debug since the --debug flag doesn't appear to provide any more information about _why_ they aren't formatted correctly, but I realize that since it's the prettier formatter being used here there may be a limit to what's realistic as a request here.
I'd like to be able to enable the cadl format check as part of our build pipeline, however I may just bypass it for now since it's not really worth the hassle.

**Comment by timotheeguerin** [comment]
That's interesting. Could it be a versioning issue. If you run `cadl format` in the pipeline then do a `git diff` to see the changes what do you get.

Might also be nice to have the check show you the diff when there is an error instead of just the files

**Comment by AMSDavis** [comment]
I did notice that the local version of the cadl compiler appears to be 0.29 whereas the pipeline one is 0.30

**Comment by timotheeguerin** [comment]
Must be the problem then, do you have 0.29.0 in your package.json?

**Comment by AMSDavis** [comment]
Generally the offending files is enough, but a --verbose option would probably be welcome, along with offending lines. I noticed that when I got the "failed to format" error it dumped the file, but didn't give any sort of line numbers, so my hopes for useful pointers were dashed a bit.

**Comment by AMSDavis** [comment]
Version in the package.json is "@cadl-lang/compiler": "~0.28.0",

**Comment by timotheeguerin** [comment]
You can run this `npm install -g @cadl-lang/compiler@0.29.0` to pin to an older version when installing globally

**Comment by AMSDavis** [comment]
@timotheeguerin a couple of additional data points:
- I updated to v0.30 locally and running `cadl format -c **/*.cadl` doesn't register anything out of line, and running format doesn't result in any changes
- I updated the pipeline to do a git diff, and the only things it is showing as changed is the package-lock file. The other two files aren't showing changes. This is the same in two scenarios:
    1. Running `cadl format` before the git diff (to format the files).
    1. Not running `cadl format` to format the files.
- If I run `cadl format **/*.cadl` in the pipeline first (scenario i) then the later `cadl format -c **/*.cadl` passes as expected, even though the files don't appear to have undergone changes.

**Comment by timotheeguerin** [comment]
weird, can you share teh content of the files having issues?

**Comment by AMSDavis** [comment]
(moved conversation elsewhere. will report back investigation findings)

**Comment by AMSDavis** [comment]
While we weren't able to definitely confirm that this was a line ending issue, the workaround that we found does point this direction.
To get the formatting to stop complaining we added a .gitattributes file to set always use LF for end of line, and then we also added a .prettierrc.yml file with `endOfLine: auto`
.gitattributes file:
```
# Use unix line endings always, even on Windows since CADL generates with LF always.
*                            text=auto eol=lf
```
