### ISSUE TITLE
Define cadl-server path in Visual Studio?

### ISSUE THREAD

**Issue by AMSDavis** [microsoft/cadl#442]
I appear to have two different versions of cadl-lang/compiler installed - one for global, and a different one is used for my csproj. Visual Studio is emitting an error and the intellisense highlighting appears to not be working.

Where can I define the cadl-server in VS? Getting this error after I uninstalled/reinstalled the VS extension. Global CADL is version 0.30, however the local appears to be 0.28 still. Thought npm update in the local directory would go 0.28 -> 0.30 and fix the issue but it didn't seem to change the lock. Here's the error in VS 2022 (intellisense error): 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/29488168/163269844-9dba6b34-dfb9-42ef-95fc-41986566cc8a.png)

I did force the update to v0.30, however other packages appear to be tied to ~0.28 as well, so i'll have to see. The mismatch is causing the same error to come up on build now that I rolled the local version back to ~0.28

**Comment by timotheeguerin** [comment]
Looks like we don't have docs for that but this is via this config https://github.com/microsoft/cadl/blob/d635c8535f25e21c75610b4efbd5305ddd0e518b/packages/cadl-vs/CHANGELOG.md#minor-changes-1

You should also be able to update the version in th epackage.json to be 0.30.0 too.
