### ISSUE TITLE
KeysOf<T> and ParentKeysOf<T> create duplicate parameters

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#462]
Currently, copyResourceKeyParameters creates new properties with different names than the original properties on a new model, but the parent .model still points to the source model. This seems like breaking an invariant and probably needs to be changed, but merely doing so makes the OpenAPI much uglier and more redundant.

This then causes the OpenAPI emitter to generate duplicate parameters and overwrite them. The problem is that there are other circumstances where you can have a duplicate parameter key (for example, with duplicate friendlyNames) where it would be an error to silently overwrite. I'm putting in a workaround to allow the overwriting only if the full JSON representation of the parameter is unchanged, and pointing back to this issue in a comment to find a long term solution.

**Comment by daviwil** [comment]
@nguerrera I took a look at #506, is my understanding correct that it will help implement this particular PR by not confusing the wrongly-parented key property with a property from the original model type?  Will that help with schema naming and inlining?

Any other thoughts on what I might need to do to fix this issue?

**Comment by nguerrera** [comment]
I think the real help for this would be #521. I think it might be reasonable to de-prioritize this until we have that. There is an effective (though ugly) workaround to dedupe the definitions that result in the OpenAPI emitter. The customer impact is maybe not high, but we should address the technical debt at some point and I think it would be easiest if we had #521. That said, there might be another fix that doesn't need that and it would still be goodness to fix it sooner in some easier way if we find one.
