### ISSUE TITLE
Migrate versioning library to use enums for version

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#466]
This should allow to cleanup a lot of the code to resolve the namespace https://github.com/microsoft/cadl/pull/441/files as well as a know issue introduce by the PR when the version name are not unique across different SDK

Idea would be to have something of the form:
```cadl

enum Versions { v1, v2} 
@serviceTitle("Pet Store Service")
@versioned(Versions)
@versionedDependency(
  Library,
  {
   [Versions.v1]: Library.Versions["1.0"],
    [Versions.v2]:  Library.Versions["1.0"]
  }
)
namespace VersionedApi;
using Cadl.Http;

```

**Comment by bterlson** [comment]
Discussed over chat but we don't have a way to map an enum member to another enum member, so likely we're looking at:

```
@versionedDependency(Library, [
  [Versions.v1, Library.Versions.v1]
  [Versions.v2, Library.Versions.V2]
])
```

**Comment by timotheeguerin** [comment]
Technically at that point we don't need the 1st argument too, wondering if maybe we could simplify

```cadl
@versionedDependencies([
   [Versions.v1, Library.Versions.v1, Other.Versions.v1]
  [Versions.v2, Library.Versions.V2, , Other.Versions.v2]
])

```

**Comment by bterlson** [comment]
True!

**Comment by markcowl** [comment]
dependent on enum reference work
