### ISSUE TITLE
Serialized/projected names

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#469]
As discussed in design issue https://github.com/Azure/cadl-azure/issues/1134 selected design is as follow.

## Spec

- Use projection to do any change of name relative to the context.
   - have known projection name that can be used to get the name for that context
      - `toJson`: Means the serialized json name is different
      - `toXml`: (Future) Means the serialized name is different
      - `to$WIRE`: Any other serialization format
      - `to$LANG`: For renaming for a specific language
- Add a new `@projectedName` decorator and a projection that automatically applies the same change
   ```cadl
      model Foo {
          @projectedName("toJson", "mybadpropertyname")
          @projectedName("toCsharp", "myCSharpPropName")
          myBetterPropertyName: string;
        }
   ```

### Using projection

```cadl
model Attributes {
  notBefore: int32;
  expires: int32;
  created: int32;
  updated: int32;
}

projection Attributes#toJson {
  to {
    renameProperty(self::notBefore "nbf")
    renameProperty(self::expires "exp")
  }
}

projection Attributes#toCsharp {
  to {
    renameProperty(self::notBefore "NotBeforeCS")
  }
}
```

### Using the decorator

```cadl
model Attributes {
  @projectedName("to_json", "nbf")
  @projectedName("to_csharp", "NotBeforeCS")
  notBefore: int32;

  @projectedName("to_json", "exp")
  expires: int32;

  created: int32;
  updated: int32;
}

projection Attributes#to_json {
  to {
    renameProperty(self::notBefore "nbf")
    renameProperty(self::expires "exp")
  }
}

projection Attributes#to_csharp {
  to {
    renameProperty(self::notBefore "NotBeforeCS")
  }
}
```

```

### Result

In Json `notBefore` and `expires` got renamed to `nbf` and `exp`

```json
{
  "nbf": 1430344421,
  "exp": 2208988799,
  "created": 1493938289,
  "updated": 1493938291
}
```

In Typescript there is not change the model is as it is

```ts
interface Attributes {
  notBefore: number;
  expires: number;
  created: number;
  updated: number;
}
```

In CSharp the `notBefore` property was renamed to `NotBeforeCS`

```cs
class Attributes
{
  [JsonProperty(PropertyName = "nbf")]
  public int NotBeforeCS {get; set;}

  [JsonProperty(PropertyName = "exp")]
  public int Expires {get; set;}

  public int Created {get; set;}

  public int Updated {get; set;}
}
```

Tasks: 
- [ ] Implement known @projectedName decorator
- [ ] OpenAPI emitter needs to use `toJson` projection to resolve the property names in schemas. (Loss of information)
- [ ] Cadl-autorest needs to use `toJson` projection to resolve proeprty name and if different use `x-ms-client-name`
- [ ] Cadl-controller emitter needs to use toJson to see if `JsonProperty` decorator needs to be specified
- [ ] Document knonw projection names

**Comment by bterlson** [comment]
In the proposal in the chat, to$WIRE was just a templated placeholder for toJSON/toXML/etc.

**Comment by timotheeguerin** [comment]
yeah maybe that isn't clear in the document above

**Comment by markcowl** [comment]
estimate: 13, pri: 1
