### ISSUE TITLE
IDE Feature: Suggested Code fixes

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#497]
There is many diagnostics that could benefit from having an automated quick fix proposed to the user.
- Auto import
- Auto add missing library
- Auto using
- Typos
- Many more

For example typescript provide quite a few of those:
https://github.com/microsoft/TypeScript/tree/main/src/services/codefixes

## Proposal

When emitting a diagnostic you can pass a list of code fixes to run.

### Option 1:
The list of code fixes are just an id reference

```ts
reportDiagnostic(program, {
   code: "library-not-found", 
   message: "Cannot find library @cadl-lang/rest",
   target: node,
   codefixes: [
      {  id: "install-lib", args: {name: "@cadl-lang/rest" }},

     // Could still have a typed function to get that reference.
     useInstalLibCodeFix("@cadl-lang/rest")
   ]
})
```

And code fixes are defined ahead of time
```
export $lib = createCadlLibrary({
   diagnostics: {

  },
  codeFixes: {
    "install-lib": async (context, libaryName: string) => {
       ... do the install ...
   },

  // Update the code
   "rename": (context, newName: string, id: IdentifierNode) => {
    // Return a list of action to do(replacing the text at a given node.
     return [
     context.replaceText(id, newName);
   ]
  },
});
```

### Option 2: inline

Code fixes is a list of callback 
```ts
reportDiagnostic(program, {
   code: "library-not-found", 
   message: "Cannot find library @cadl-lang/rest",
   target: node,
   codefixes: [
     createInstallLibCodeFix("@cadl-lang/rest"),
   ]
})
```

**Comment by markcowl** [comment]
```
{id: "rename", args: {newName: "bar", node: node.id}}
```

- implementation question: marshalling arguments between fix code and language server (e.g. diagnosticTarget)
 - potential impact on design?
 - favor option 2 unless option 1 helps with implementation challenges
