### ISSUE TITLE
Should `model is float64[]` work?

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#499]
FormRecognizer has types that are array. This would let `@minItems` and `@maxItems` be used on it.

Other things to think about: `float64[8]` -> mean an array of exactly 8 `float64`

cc: @tjprescott

**Comment by tjprescott** [comment]
Or something like in Swift
```swift
class MyArray: Array where Element is Float64 {
...
}
```

Or this could also work, where you have a model that wraps the array type, but implements a subscript interface so you can subscript into the object as if you were subscripting into the array directly.
```swift
class MyArray {
  private let innerArray: [float64]

  subscript(index: int) -> float64 {
    return innerArray[index]
  }
}
```

**Comment by bterlson** [comment]
I would say the model is example shouldn't work because array types are not model types and so this brings us back to a model = world.

That said the use case for an array that carries along some constraints is pretty clear. Is it another instance of wanting to decorate a type expression? E.g. we have wanted this for unions, though we solved this by adding a union declaration form...

**Comment by timotheeguerin** [comment]
There is a few things:
- be able to add decorator on an array and reuse that
- give a name to that array.(E.g. `BoundingBox` for Formrecognizer). Though what would this mean in the generator code? Would we provide an array wrapper?
- Another kind of related issue is wondering is could the language have a built-in way to specify the size of the array vs using decorators. For example right now the bounding box could be represented as `[float64, float64, float64, float64, float64, float64, float64, float64]` being an array of 8 `float64`(Openapi3 emitter not happy but this is valid Cadl)
    - This also bring then the same problem for giving tuple a name

**Comment by tjprescott** [comment]
Form Recognizer has a BoundingBox which is an array of 8 floats. How should someone represent that in CADL, because it is correctly represented today in Swagger.

**Comment by bterlson** [comment]
Also, `float64[2]` as sugar for `[float64, float64]` makes a lot of sense to me.

**Comment by tjprescott** [comment]
float64[8] would work for BoundingBox, but @timotheeguerin pointed out, how would you express "an array that has a min of x items and a max of y"?  With Swagger you can using minItems/maxItems, but how would you do it in CADL? `float64[1-2]`would have to be expanded to something like `[float64] | [float64, float64]`?

**Comment by bterlson** [comment]
That syntax is getting more clever than I like, and probably places a lot of burden on emitters to reason through unions of tuples. Possible to add such syntax in the future.

Synthesizing from the comments above, the other options on the table are:

### Arrays are models, my friend

```
@minLength(1)
@maxLength(2)
model ShortArray<T> is T[] { }
```

(But would need to figure out the subtyping semantics of arrays and objects, what it means to add properties to an array type, plus probably more issues)

### Declaration form of alias

```
@minLength(1)
@maxLength(2)
declare ShortArray<T> = T[];
```

(But would need to reason through the consequences of allowing decorators on arbitrary expressions, allowing arbitrary expressions to be declared (we had this via `model =` some time ago and it was painful, whether we would also allow decorators on alias, plus probably more issues)

**Comment by timotheeguerin** [comment]
I do agree that the min-max syntax gets too complex and having to use the decorator on an array at that point makes more sense. This is not easily representable in TS either.

For option 1 we already have all the primitive types that are "model" where it doesn't make sense to add properties to.

**Comment by bterlson** [comment]
That's a good point re: option 1. Ok, I answer yes to the topic question, but let's integrate these semantics into the subclassing proposal as well and make sure it hangs together. Perhaps it is sufficient to say we have a Record<T> which is a map of string -> T and an Array<T> which is a map of number -> T, and both are subclasses of `object`? This would force our hand on T[] being a subtype of U[] if T is a subtype of U, which I think Johan had some concerns about but does align with the current proposal.
