### ISSUE TITLE
Update azure library namespaces and improve error message when type is not found

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#512]
While trying to update the FormRecognizer example to use Azure.Core, I ran into an issue where Azure.Core could not be found. After consultation with @timotheeguerin the issue seems to be a namespacing bug. Here's the simplest repro (thanks @timotheeguerin!)

```
namespace Foo.Bar {
  model FooBarModel {
    
  }
}

namespace Microsoft.Foo.Custom {
  // This *should* work but does not
  model Custom extends Foo.Bar.FooBarModel {

  }
}
```

https://cadlplayground.z22.web.core.windows.net/?c=bmFtZXNwYWNlIEZvby5CYXIgew0KICBtb2RlbMQTQmFyTcUMxRcgIMQGfQ0KfQ0KDQrKPE1pY3Jvc29mdC7ERkN1c3RvbcYyyk3HFmV4dGVuZHPIb8QxzGTIYA%3D%3D

**Comment by tjprescott** [comment]
When I try to use a `using` statement, the autocompletion only shows Custom as a valid member of the Foo namespace:
![image](https://user-images.githubusercontent.com/5723682/166976168-fa295daf-932a-4876-a287-43957125f249.png)

**Comment by tjprescott** [comment]
And the less abstract example:
```
namespace Microsoft.Azure.FormRecognizer;

using Azure.Core;
```

This seems like it would be a very common pattern, so this is problematic.

**Comment by bterlson** [comment]
Is it expected that names from any parent namespaces are not in-scope? I.e. you would expect the following to fail:

```
namespace Foo.Bar {
  model L2 { }
}

namespace Foo.Bar.Baz {
  model L3 extends L2 { }
  model L3 extends Bar.L2 { }
}
```

**Comment by tjprescott** [comment]
It works if I remove the Microsoft prefix:
```
namespace Azure.FormRecognizer;

using Azure.Core;
```

**Comment by timotheeguerin** [comment]
> Is it expected that names from any parent namespaces are not in-scope? I.e. you would expect the following to fail:
> 
> ```
> namespace Foo.Bar {
>   model L2 { }
> }
> 
> namespace Foo.Bar.Baz {
>   model L3 extends L2 { }
>   model L3 extends Bar.L2 { }
> }
> ```

That code works in cadl(If you change the 2nd model to L4 so there is no name dup) [Playground](https://cadlplayground.z22.web.core.windows.net/?c=bmFtZXNwYWNlIEZvby5CYXIgew0KICBtb2RlbCBMMiB7IH0NCn0NCg0K0SouQmF6zS4zIGV4dGVuZHPJOckbNMkbxDnJWA%3D%3D)  and in csharp 
![image](https://user-images.githubusercontent.com/1031227/166984672-04afc9b6-63a7-457a-af5a-dce9ea17adb1.png)

**Comment by bterlson** [comment]
To clarify why I asked the question - does fixing the examples in the OP imply that the example I posted above would fail? Or are we proposing other semantics?

**Comment by timotheeguerin** [comment]
Yeah that's true, this original code would fail in CSharp as well 
<img width="819" alt="image" src="https://user-images.githubusercontent.com/1031227/166987191-95097f47-4e77-4d66-851a-0059870155e6.png">
to resolve you have to use `global::`
<img width="370" alt="image" src="https://user-images.githubusercontent.com/1031227/166987261-20aff616-b89e-4020-875b-d2d44115ca62.png">

We could also just merge the namespaces when resolving the values

**Comment by nguerrera** [comment]
I think this should remain an error as in C# and we could add something like `global::`. That said, I can count on one hand the number of times I've needed to use `global::` in two decades of C# programming. I think the guideline of always using Company Dot Technology might have helped there. I would suggest that we avoid using `Azure.*` if others are going to use `Microsoft.Azure.*` commonly. Maybe we should use Microsoft.Azure too?

**Comment by bterlson** [comment]
Support for some notion of `global::` seems like the best solution to this issue. I can't see any changes to identifier resolution that doesn't make things more confusing.

**Comment by nguerrera** [comment]
One thing C# does better here is that it tells you the full name of the namespace that doesn't have a member.

Cadl:  "Namespace doesn't have member Bar"
C#: "The type or name 'Bar' does not exist in the namespace **'Microsoft.Foo'**"

**Comment by tjprescott** [comment]
I think @nguerrera's suggestion of using `Microsoft.Azure.Core` makes sense, though it does claim part of the namespace. Would `Cadl.Azure.Core` make sense?

**Comment by nguerrera** [comment]
I would prefer `Microsoft.Azure` over `Cadl.Azure`. The latter makes it sound like it's part of the Cadl core and we should position it as a Microsoft extension to the Cadl Core.

**Comment by nguerrera** [comment]
Error message improved in #597, we still need to rename the libraries.

**Comment by markcowl** [comment]
- add global to the language
- recommend specs start with '```Azure.``` in namespaces', and enforce with linting rules in azure libraries

**Comment by nguerrera** [comment]
Filed #781

**Comment by markcowl** [comment]
- documentation on starting with Azure. in internal namespaces
