### ISSUE TITLE
Empty Tuple as template default parameter not valid (expression expected)

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#522]
```cadl
import "@cadl-lang/rest";

using Cadl.Http;


@Cadl.Http.route("/")
interface Operations<T=[]> {
  @Cadl.Http.post op invoke(@Cadl.Http.body param: string): string;
}

interface Service extends Operations {

}
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKCkDJDi5yb3V0ZSgiLyIpCmludGVyZmFjZSBPcGVyYXRpb25zPFQ9W10%2BIHsKICDLNXBvc3Qgb3AgaW52b2tlKMsaYm9keSBwYXJhbTogc3RyaW5nKcgJOwp9CstkU2VydmljZSBleHRlbmRzy3QgewoKfQ%3D%3D)

A non-empty tuple is valid. Feels broken to me... 

```cadl
import "@cadl-lang/rest";

using Cadl.Http;


@Cadl.Http.route("/")
interface Operations<T=["This works"]> {
  @Cadl.Http.post op invoke(@Cadl.Http.body param: string): string;
}

interface Service extends Operations {

}
```

**Comment by nguerrera** [comment]
Empty tuple is not valid anywhere, currently. So this isn't related to default parameters .The grammar specifies there must be at least one expression, and the parser respects this. I don't know if it was intentionally designed or not, though. cc @bterlson. If it is intentional, we should have a better error message at least.

**Comment by nguerrera** [comment]
To demonstrate that this applies anywhere, here's a smaller repro: https://cadlplayground.z22.web.core.windows.net/?c=YWxpYXMgRW1wdHlUdXBsZSA9IFtdOw%3D%3D

**Comment by bterlson** [comment]
I am not remembering any justification for disallowing empty tuple.

**Comment by nguerrera** [comment]
This will take just a few minutes to fix, so I'll go ahead and get that over with.
