### ISSUE TITLE
Decorator and function typing

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#528]
Filing a design issue to track the design needed to be able to do Signature Help: https://github.com/Azure/cadl-azure/issues/614

**Comment by nguerrera** [comment]
Draft propsoal with two alternatives: https://gist.github.com/nguerrera/626d6a9d65448a9d5cf38e9887fcc1d3

**Comment by nguerrera** [comment]
I will leave this open to track the design for typing. We have split off https://github.com/microsoft/cadl/issues/533 as an implementation issue to deliver the direct-from-ts experience regardless of whether or not we use it for typing.

**Comment by tjprescott** [comment]
This was brought up again at the ARB review on 8/11/2022.

**Comment by timotheeguerin** [comment]
Updated proposal https://gist.github.com/timotheeguerin/4d01caea2bbd85f96658007fd82daa2e

**Comment by timotheeguerin** [comment]
Created new issues for this 
Overall decorator proposal: #996
  - `extern` decorator implementation #994
  - Signature help #997
