### ISSUE TITLE
Investigate our use of options

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#538]
Look over all our options and see what should be:
- emiter options to be defined via #531
- not an option but a decorator
- what still needs to remain an option(Should it reallly?)

-- 
To be filled with findings

**Comment by markcowl** [comment]
We should do this as part of #233

**Comment by timotheeguerin** [comment]
## cadl-autorest

https://github.com/Azure/cadl-azure/blob/8ce2f51b06601df9775ef18789f70cf8397c0e34/packages/cadl-autorest/src/openapi.ts#L83

- `examplesDirectory`
- `version`

## cadl-providerhub

https://github.com/Azure/cadl-azure/blob/8ce2f51b06601df9775ef18789f70cf8397c0e34/packages/cadl-providerhub-controller/src/generate.ts#L79

- `serviceCodePath`
- `controllerHost`
- `operationPollingLocation`

**Comment by markcowl** [comment]
examplesDirectory is an emitter option
version is also an emitter option, it allows generating only one version for a multi-version spec.  It should likely take a list of versions, but it should certainly be an emitter option.

serviceCodePath, controllerHost should be emitter options
operationPollingLocation is service-level metadata.  It doesn't impact the emitted openapi at the moment, but that will likely change when we implement cadl lro. I would leave it as an emitter option until we add new lro capabilities.

**Comment by jianyexi** [comment]
In addition, 'outputSwaggerFileName' is another option needs to support , as in shift left pipeline, service would be able to specify a reasonable name for its output swagger

**Comment by leni-msft** [comment]
PR to document cadl-autorest `examplesDirectory` emitter option: https://github.com/Azure/cadl-azure/pull/1554

**Comment by timotheeguerin** [comment]
All of those should be emitter options that can be added with https://github.com/microsoft/cadl/pull/531
