### ISSUE TITLE
Problems in language server with multifile specs spread across directories

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#541]
In vs code, if the user represents their cadl spec using multiple files in different folders, the vs code extension reports false  errors resulting from not processing the entire spec..

For example, a structure like
- root
  main.cadl
  common.cadl
  - resources
     Foo.cadl
     Bar.cadl

where main.cadl imports all of the other files

Can result in errors when 'Foo.cadl' is opened in VS Code. For example, types referenced in 'Foo.cadl' that are defined in common.cadl or main.cadl are not found.  Also, decorators applied to a namespace in main.cadl are not recognized when the namespace is used in 'Foo.cadl', which can result in validation errors for required decorators like `@armNamespace`

If the same spec is all in one directory, these issues do not apply. ALso, if all files are opened in VSCode, this appears to fix many of the errors

Note that importing 'main.cadl' and 'foo.cadl' from the leaf directories resolves some of these issues, but does not solve them universally.

In all cases, the spec compiles correctly from the command line (using 'main.cadl or '.' as the argument to compile)

**Comment by nguerrera** [comment]
Does main.cadl ultimately import all of the files underneath it?

Are there any package.json files in this hierarchy?

Do you have a repro you can share?

**Comment by nguerrera** [comment]
Is there a rogue main.cadl in a subdirectory?

**Comment by nguerrera** [comment]
Hmm, I made a repro, looking.
