### ISSUE TITLE
Investigate running decorator after type graph is built

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#557]
investigate the phase design proposed here #502

Despite #502 being resolved by https://github.com/microsoft/cadl/pull/800, that fix is only specific to the `@route` decorator and could very well occur in another scenario where the decorator is keeping index on elements.

**Comment by timotheeguerin** [comment]
Think this is a little less important now that the upstream issue has been resolved. We can revisist

**Comment by markcowl** [comment]
Superseded  by subsequent issues
