### ISSUE TITLE
Make enum `members` a map like other member containers

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#560]
I am often annoyed that `members` is a plain array. I think getting the type of an enum member by name will be fairly common? But would also be ok with adding an API to get a member by name.

**Comment by timotheeguerin** [comment]
as the name are unique, feels like it make sense to do that

**Comment by timotheeguerin** [comment]
one issue with this one is that for versioning we do want to keep the order of members a map would technically hide that

**Comment by markcowl** [comment]
@bterlson @timotheeguerin marking as 'blocked' until we get an agreement and an estimate.

**Comment by timotheeguerin** [comment]
`Map` according to the es spec does keep the order of members and this is something we are counting on for properties as well #948
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
