### ISSUE TITLE
Inline generic instantiations without friendlyName in OpenAPI 2 and 3

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#562]
We agreed to do 3a of #464. The rest of that design issue is still up for discussion.

* Generic instantiations will now be inlined unless you use `@friendlyName` or `model is` to give it a name.
* The code to give generic instantiations default names with underscores will be deleted.

**Comment by markcowl** [comment]
@nguerrera Can you add an estimate to this?

**Comment by nguerrera** [comment]
@markcowl estimate: 5. It's a very small change, but it will change a lot of sample output and leaving time to vet the changes and see if there were unforeseen consequences.

**Comment by nguerrera** [comment]
I set it in the project as well, is there an easy way to jump from here to there?

**Comment by nguerrera** [comment]
Something that I learned while doing metadata that could have an impact here:

You can't really inline recursive models. That said, we already have this bug as we already inline non-anoymous and therefore possibly recursive templates in certain cases, and when I went to demo this, I hit other bugs in the compiler for this case.

I think the right fix for this would be to detect a cycle in something we try to inline and error out. User can provide friendly name to fix it.

**Comment by nguerrera** [comment]
I will see if this can be done quick to limit the window of time where the unfortunate output in #791 persists.
