### ISSUE TITLE
(0.32.0) Next cadl release breaking changes 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#596]
Issue tracking incoming breaking changes

## Versioning using enums #585

```cadl
// Before
@versioned("v1" | "v2")
namespace Api;

// After
@versioned(Versions)
namespace Api;

enum Versions { v1, v2 }
```

```cadl
// Before
@added("v2")
model Foo {}

// After
@added(Versions.v2)
model Foo {}
```

## Removed `@serviceHost` 

`@serviceHost` decorator has been removed and replaced with protocol specific decorator. Right now only `@Cadl.Http.server` https://github.com/microsoft/cadl/pull/581

Before 
```cadl
@serviceHost("example.com")
namespace MyService;
```

After
```cadl
@server("https://example.com")
namespace MyService;
```

**Comment by markcowl** [comment]
- release notes in the repos
