### ISSUE TITLE
[Template Parameter Constraints] Tooling support 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#603]
#377 

Support autocompletion/intelisense for template parameter constraints.

**Comment by markcowl** [comment]
@timotheeguerin Is this an implementation issue, or is there somethign about tooling support that needs to be discussed ina  design issue?

**Comment by timotheeguerin** [comment]
I guess that one is probably just the implementation

**Comment by nguerrera** [comment]
Adding some detail here. I think the feature is that you can write like


```
model Foo {
   x: string;
    y: string;
}

model Something<T extends M> {
   prop: T.x;
} 
```

And the remaining tooling feature would be to make sure you see all the available properties coming from the constraint when you type `T.`.

As I wrote this, I realize that this might have some potential to break renaming property `x` or goto definition on `T.x` so we should check that too.

**Comment by markcowl** [comment]
So, I thought this had to do with intellisense for instantiating templates with parameter constraints, so

```
model Something<T is string> {
}

MyInstantiation is Someting<|
```
 where '|' is the cursor

**Comment by nguerrera** [comment]
That should more or less work for free. I'm assuming that there is a TypeReference node after the `is`, we should complete it just like after `is` and `:` everywhere else.

**Comment by nguerrera** [comment]
Nevermind, I read that wrong.

**Comment by nguerrera** [comment]
C# doesn't do this either:

![image](https://user-images.githubusercontent.com/75470/173428945-771f06d6-4db5-44f0-b3bc-2ac431f5406a.png)

![image](https://user-images.githubusercontent.com/75470/173428972-838327c9-1cc6-4ea1-b02f-c64c7d86c4fc.png)
