### ISSUE TITLE
Content-Type header lookup is case-sensitive

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#607]
From [responses.ts](https://github.com/microsoft/cadl/blob/73c8bf794d5e12d91fe96a94f6bb74c7b01ace59/packages/rest/src/responses.ts#L209):

```typescript
 for (const prop of responseModel.properties.values()) {
      if (isHeader(program, prop) && getHeaderFieldName(program, prop) === "content-type") {
        contentTypes.push(...diagnostics.pipe(getContentTypes(prop)));
      }
```

This means that I had to use the (non-standard, but still working) lower-case of the header name in order for things to work. 

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0KDQptb2RlbCBTdHJ1Y3R1cmVkIHsNCiAgc2l6ZTogaW50MzI7xBBkYXRhOiBzdHJpbmc7DQp9yjpCaW5hcnkgaXMgYnl0ZXPGP0BDYWRsLkh0dHAuaGVhZGVyKCJDb250ZW50LVR5cGUiKSBjxg%2FEDjogImFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbeQAo33lAKfLUnBvc3Qgb3AgZG9TdHVmZijLG2JvZHkgxAU67ADSfOcApSnVFsVf)

**Comment by timotheeguerin** [comment]
Seems to still be an issue for request content types
