### ISSUE TITLE
Diagnostic count summary looks off in some cases

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#61]
See https://dev.azure.com/azure-sdk/public/_build/results?buildId=1195424&view=logs&j=69944193-f126-526b-b021-abb6fb4b38ee&t=a525eb91-4a52-5fc4-de8c-4f229a13c8bb

Notice there are runs with only info messages printing "`Found .`" and runs with multiple warnings printing "`Found 0 warnings`."

cc @timotheeguerin

**Comment by timotheeguerin** [comment]
interesting, will look at that.
