### ISSUE TITLE
test file naming convention

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#611]
We have a mix of different naming conventions for test code and I find it makes it really hard to navigate using Go-to-file. And it's sometimes confusing that, for example, namespaces.ts doesn't implement anything about namespaces, it tests them. Yes, the folder tells you, but like I said, go-to-file experience is annoying. We have a lot of test-*.ts, but we're inconsistent. I propose that we use test-*.ts throughout. We also have some casing differences that we might as well sort out at the same time, I think.

**Comment by timotheeguerin** [comment]
yeah I agree that having some differentiator would be a good idea. I personally like the `.test.ts` suffix. This is the pattern used a lot of the JS/TS world(That or `.spec.ts`). But if we prefer `test-` I'll live :)

**Comment by nguerrera** [comment]
That's fine with me too, I just picked something we already had in a bunch of places. I'm easily convinced as long as there's some differentiator :)

**Comment by nguerrera** [comment]
I prefer .test to .spec though. .spec seems unnecessarily technical and unclear IMHO, but I know it's common in JS community.

**Comment by timotheeguerin** [comment]
Yeah, fine with either, using `.test.ts` with autorest. Used to do `.spec.ts` for previous projects as it goes with the behavior testing naming of `describe`, `it` , `expect`
