### ISSUE TITLE
Playground doesn't seem to clear previous errors?

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#637]
See what happens here:

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIEZvbzxUPiB7DQogIGJhcigpOiBUO8YNesgNfQ0KDQphbGlhcyBTdHJpbmdGb28gPcU7c8UQPjvEIspVVXNhZ2XGVG9wxFcgacs7LmJhcjsgLy8gZGVsZXRlIGFuZCByZXR5cGXOJA0KfQ%3D%3D)

On my machine I get fairly random errors (e.g. identifier expected on the semicolon, or StringFoo doesn't have member b or ba).

**Comment by timotheeguerin** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/1031227/173701955-7d9d6ca0-1887-4ba3-9920-1a14e654f7fa.png">
I think this happens when there is an uncaught error(internal compiler error)

**Comment by timotheeguerin** [comment]
yeah and I think also a way for diagnostics that are not in the main.cadl file to show up somewhere
