### ISSUE TITLE
Allow omitting braces from `model is`

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#645]
I feel like the braces shouldn't be needed when such a prevalent usecase is just adding decorators and not adding any new properties.

**Comment by nguerrera** [comment]
I don't feel super strongly about this, but I am a little concerned about the asymmetry between namespace and model without braces. For namespaces, it means the rest of the file declares its members, for models it would mean there are no members.

For example, it is not unreasonable IMHO to expect that if 

`@dec model X is Y;`  is a complete declaration of a model, then `@dec namespace Z;` is likewise a complete namespace declaration.

**Comment by bterlson** [comment]
Design meeting consensus: do for `is`. Not for extends, not for empty model.
