### ISSUE TITLE
[OA3] Missing description for model-is of primitive types

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#646]
The docs show up for regular models but not when you e.g. `is` a number.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGRvYygiQSBzcGVjaWFsIG51bWJlciIpDQptb2RlbCBTxxhpcyBpbnQzMiB7fTsNCg0Kb3AgZ2V0KCk6yCI7)

**Comment by markcowl** [comment]
investigate and fix if simple

**Comment by timotheeguerin** [comment]
turn out to be a very simple bug, it was only allowing description if the type was `is string` probably a copy and paste issue from the other decorator that are string specific.
