### ISSUE TITLE
Standarized emitter options name

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#648]
We currently have options that are `kebab-case` or `camelCase` we should update all to be `kebab-case` and add a linter rule for it. 

I think this would be good to get in this milestone before the next release as we are already breaking the way options work better not do it twice.

**Comment by witemple-msft** [comment]
FYI I think this case is called `kebab-case` (because when CLI apps use it for flags, it looks like the words are on a kebab skewer: `--kebab-case`). Snake case would be underscore separated: `snake_case`.
