### ISSUE TITLE
Support references in OpenAPI emitters

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#649]
```cadl
model Bar {
  x: string; // <-- Squiggle squiggle pop "Couldn't get schema for type ModelProperty"
}

op y(): Bar.x;
```

On a side note, is there a way to include the source/originator of an error? I often find it helpful to know if the error was generated by an emitter or by something else. 

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgQmFyIHsKICB4OiBzdHJpbmc7Cn0KCgpvcCB4KCk6xB8ueDs%3D)

**Comment by bterlson** [comment]
The OA3 emitter doesn't have support for references of any sort yet. I believe I forgot to track that, so this issue can serve!

**Comment by markcowl** [comment]
- emitters should handle references correctly
- required for operation linking, and OpenAPI links
estimate: 5
