### ISSUE TITLE
Add list of supported decorators to documents

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#653]
It would be great if there were a documentation page describing the list of supported decorators so these were easily discoverable to Cadl users.  Thanks!

Update, I found this: https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#built-in-decorators, but it doesn't include `@header`, so wondering how to think about that?

**Comment by allenjzhang** [comment]
Preferred way: 
- IDE experience could help with autocompletion and intellisense support. 

- Open questions, need comprehensive documentation on the list of declarators from different packages.

**Comment by nguerrera** [comment]
Once we have signature help (https://github.com/microsoft/cadl/issues/653), you would see all the decorator docs and be able to pick them based on doc with completion after typing `@`. But we still have to go through and add the documentation to the decorators for signature help to consume.
