### ISSUE TITLE
When emitters throw errors, we tell people to file bugs here

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#655]
We show text like:

```
Unhandled promise rejection!
Internal compiler error!
File issue at https://github.com/microsoft/cadl
```

But we should probably not direct people to file bugs here when some emitter they're using that isn't ours fails.

**Comment by nguerrera** [comment]
I think the trickier problem is how to assign blame to an unhandledPromiseRejection event. It's pretty easy to put a more specific try/catch around emitter calls, but what's the equivalent for unhandledPromiseRejection? Would we have to make sense of the error stack?
