### ISSUE TITLE
Visual Studio extension doesn't find the cadl-server path in VSWorkspaceSettings.json when a solution is open

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#660]
It seems the way we're getting to this file doesn't work unless you use "open folder" instead of "open solution". 

It seems `CurrentWorkspace` is null when using a solution: 
https://github.com/microsoft/cadl/blob/067ed4523f79b0ae40b44f546a000fc869e52cc0/packages/cadl-vs/src/VSExtension.cs#L66

It might be time to use a different file for this, but we can first check if there's an easy fix. That file has other problems: it is .gitignored by default templates and otherwise contains a bunch of temporary state that is meant to be deleted, making it a terrible place to store user settings.

cc @abatishchev

**Comment by nguerrera** [comment]
From https://docs.microsoft.com/en-us/visualstudio/extensibility/workspaces?view=vs-2022 (emphasis mine)

> A workspace is how Visual Studio represents any collection of files in *[Open Folder](https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions?view=vs-2022)*

So it seems basing the cadl-server settings on this open-folder-specific thing is a poor choice. We could go hunting for the file ourselves by walking up from the active .sln to a .vs/ ancestor, but given that .vs/ is already a problematic location, I think we should just read it from somewhere else. 

I wonder if we can make both VS and VS Code extensions find and read cadl-project.yaml and add something there. This would allow teams to share the setting between VS and VS Code users. We could continue to support VS Code and VS (if using Open Folder) *settings.json as a fallback to avoid breaking people.

**Comment by nguerrera** [comment]
cadl-project is maybe not ideal either since the settings could be in different places and formats and we'd have to duplicate a lot of logic in C# for the VS extension, and pull in dependencies to read JSON and Yaml. However, it might be the best customer experience to not invent yet another config file for this so I'm still leaning towards it, but it's not a trivial change, so we should discuss the design on this.

**Comment by markcowl** [comment]
estimate: 8

**Comment by markcowl** [comment]
-workarounds

- open folder to use vsworkspacesettings.cs
- make default compiler finding work (need to document)

**Comment by nguerrera** [comment]
I'm going to try the cheaper fix of finding the json file ourselves when there is no workspace manager and then file a lower priority issue to reconsider the settings location / have a shared location for different IDEs.

**Comment by nguerrera** [comment]
The cheaper fix is in. Filed https://github.com/microsoft/cadl/issues/922 to consider supporting an alternate location.

**Comment by nguerrera** [comment]
> Another issue with VSWorkspaceSettings.json currently. We don't support ${workspaceRoot} and it appears to be relative to CWD always. cc @chadp777

This was fixed separately in #891
