### ISSUE TITLE
Configured cadl-server isn't used if there's another one in parent node_modules

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#663]
Filing on behalf of @chadp777, we debugged this together.

With a certain directory structure, if you set the cadl-server path in .vscode/settings.json, you can still end up with the compiler mismatch error that then tells you to configure it to that same path you already set. This happens if the resolveModule code that boots the server finds another cadl-server than the one you configured.

Example:

```
/parentDir 
    node_modules/
        @cadl-lang/compiler
    workspace/
        cadl-project/
            something.cadl
            package.json
            node_modules/
               @cadl-lang/compiler
```

Then settings.json has:

```
{
  "cadl.cadl-server.path":${workspaceRoot}/cadl-project/node_modules/@cadl-lang/compiler"
}
```

And we run `${workspaceRoot}/cadl-project/node_modules/@cadl-lang/compiler/cmd/cadl-server.js` as we should, but then it turns around and does a resolveModule and finds and prefers `${workspaceRoot}/../node_modules/@cadl-lang/compiler.` and we still have the mismatch despite the configuration.

**Comment by markcowl** [comment]
estimate: 3

**Comment by nguerrera** [comment]
Likely fix here, some way to disable the resolveModule when we're using a configured path. If the path is configured, we should use the compiler at that path or fail if not found.
