### ISSUE TITLE
Provide a way to indicate that a parameter is a "client parameter"

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#664]
We would like a way to indicate that the `hub` parameter in WebPubSub is a "client parameter", meaning it is a private member on the client and taken as a parameter to the client constructor (see [WebPubSub APIView](https://apiview.dev/Assemblies/Review/ac9256cefa2143c3af893b596542af6e#Azure.Messaging.WebPubSub.WebPubSubServiceClient)).

In swagger, this could be indicated as a global parameter, or by using the `x-ms-parameter-location` extension and setting the value to `client`.

**Comment by lmazuel** [comment]
Do-able short term with:

```cadl
import "@cadl-lang/openapi";

@doc("The mode with which you'll be handling your returned body. 'raw' for just dealing with the raw body, and 'model' if you are going to convert the raw body to a customized body before returning to users.")
model ModeParameter {
  @OpenAPI.extension("x-ms-parameter-location", "method")
  @doc("The mode with which you'll be handling your returned body. 'raw' for just dealing with the raw body, and 'model' if you are going to convert the raw body to a customized body before returning to users.")
  @path
  mode: Mode;
}
```

But agree we need a design that don't use `OpenAPI.extension` long term

**Comment by markcowl** [comment]
Discuss with #656

**Comment by daviwil** [comment]
Implementation issue: https://github.com/microsoft/cadl/issues/778
