### ISSUE TITLE
Allow adding `@produces` and `@consumes` at the operation level

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#665]
In the WebPubSub OpenAPI definition, produces and consumes blocks are specified at the operation level:
https://github.com/Azure/azure-rest-api-specs/blob/39c7d63c21b9a29efe3907d9b949d1c77b021907/specification/webpubsub/data-plane/WebPubSub/stable/2021-10-01/webpubsub.json#L187-L196

In order to represent this in Cadl, I believe we will need to represent this at the operation level as well, however this does not appear to be allowed currently:

![image](https://user-images.githubusercontent.com/21269347/176037278-32364765-512f-46cc-892b-4306446fb402.png)

**Comment by bterlson** [comment]
I feel like this should be inferred from the content types of the response bodies involved, rather than explicitly stated in a decorator. @mikekistler any thoughts here?

**Comment by bterlson** [comment]
In fact, does it work if you take a parameter like `@header accept: "application/octet-stream" | "text/plain" | "application/json"`? I think the difficulty is going to be that if you pass an `application/json` then the message body is an object, if it's `text/plain` then its a string, else its `bytes`. We talked about overloads for this scenario, but I don't believe we've implemented it. @johanste was involved and might chime in for how he would want to do this, being an overload-skeptic 😁

**Comment by annelo-msft** [comment]
> In fact, does it work if you take a parameter like @header accept: "application/octet-stream" | "text/plain" | "application/json"? 

The swagger2 output is not the same (note one uses a consumes block whereas one describes a header parameter), but is this a preferred way to indicate the same thing?  (My challenge is that right now the service-defined swagger is the source of truth for the API, although there may be multiple ways to describe it...)

- service description swagger:

```
 "/api/hubs/{hub}/:send": {
      "post": {
        "tags": [
          "webpubsub"
        ],
        "summary": "Broadcast content inside request body to all the connected client connections.",
        "operationId": "WebPubSub_SendToAll",
        "consumes": [
          "application/octet-stream",
          "text/plain",
          "application/json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "hub",
            "description": "Target hub name, which should start with alphabetic characters and only contain alpha-numeric characters or underscore.",
            "required": true,
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z0-9_`,.[\\]]{0,127}$"
          },
```

- generated swagger:

```
    "/api/hubs/{hub}/:send": {
      "post": {
        "tags": [
          "webpubsub"
        ],
        "operationId": "WebPubSubService_sendToAll",
        "summary": "Broadcast content inside request body to all the connected client connections.",
        "parameters": [
          {
            "name": "accept",
            "in": "header",
            "required": true,
            "type": "string",
            "enum": [
              "application/octet-stream",
              "text/plain",
              "application/json"
            ]
          },
          {
            "name": "hub",
            "in": "path",
            "required": true,
            "type": "string"
          },
```

**Comment by johanste** [comment]
Ignoring the fact that the swagger looks incorrect (the API only `produces` json, and only for errors at that), I would provide three different named methods (in Cadl) that all map to the same route. It would require emitters such as our own openapi family of emitters to do a much better job of joining the operations than its current strategy which is basically "throw your hands in the air like you just don't care"  and raise an error.  Any form of overload at the Cadl level would still require someone to invent a new name for any "overloads" that a given emitter cannot understand (e.g. golang or similar).

**Comment by johanste** [comment]
...also, assuming the hoisting of metadata from the logical T works the way I expect, you could indeed us a single message property that included the `Content-Type` header metadata...

**Comment by johanste** [comment]
Now, it looks like [headers get dropped](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKbW9kZWwgU29tZXRoxBx7CiAgQGhlYWRlcigiQ29udGVudC1UeXBlIikKICBjxhHEEDogImFwcGxpY2F0aW9uL3RleMRiICAKICBkYXRhOiBzdHJpbmc7Cn3IZUVsc2XfYNpgb2N0ZXQtc3RyZWFtzmhieXRlc8VnQHBvc3Qgb3AgZG9TdHVmZihtZXNzYWdlOusA4HzlAIcpOiB2b2lkOwo%3D) if you do what I suggested. But I think that is an openapi3 emitter bug...

**Comment by mikekistler** [comment]
I agree with @bterlson that we do not want decorators to define @consumes and @produces -- these should be defined on the models for the request body and return types.

**Comment by johanste** [comment]
I'm not sure if the serialization format (representation) - e.g. XML vs. json - belongs in the conceptual realm/directly on the model in the description of my service. And I definitely don't want to splatter it across all models in my service in the 99% case for Azure where produces/consumes is all `json`.

**Comment by bterlson** [comment]
Emitters can pick a default, and for REST APIs JSON seems like a fine default to pick. Also keep in mind that the "conceptual T" won't carry the accept/content-type, but it will be part of the parameter/payload somewhere. Treating accept/content-type like any other parameter/payload seems simple and clean to me.

**Comment by johanste** [comment]
Yeah, I'm not advocating for a decorator. I think. I am concerned about offloading too many things to emitters, though. By definition, doesn't that kind of mean that we've left important aspects of the specification up for interpretation? :). 

I'm not sure I fully grok the "won't carry but it will be part of" statement, and I'd probably need to see an example of what that would look like.

**Comment by johanste** [comment]
# Cadl overloads, take III(ish)

## Concrete examples for content type overloads:

### Single operation with two different content types, same route, same return value and parameters. 

This is the most common scenario.

```cadl
model Text is string {
  @Cadl.Http.header("content-type") contentType: "text/plain";
};
model Image is bytes {
  @Cadl.Http.header("content-type") contentType: "application/octet-stream";
}

@route("/doImageOrTextStuffOnly")
@post op doSimilarStuff(data: Text | Image, @query option?: string): void;
```

> Note: we are adding metadata/properties to a  string model
The following Python code can be emitted:

```python
def do_similar_stuff(data: str | bytes, *, option: Optional[str]=None) -> None:
    ...
```

### Two "overloaded" operations under two different endpoints (HTTP routes).
```cadl
model Resource {};

interface Resource {
  @Cadl.Http.route("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupId}/")
  @Cadl.Http.get
  @overload("list") // <- optional hint to code generator
  op listByResourceGroup(@path resourceGroupId: string): Resource[];

  @Cadl.Http.route("/subscriptions/{subscriptionId}/resources")
  @Cadl.Http.get
  @overload("list")
  op listBySubscription(): Resource[];
}
```

```python
def list(subscriptionId: str, resource_group_id: Optional[str]=None) -> list[Resource]:
    ...
```

### Two operations (same endpoint) with different sets of parameters and possibly different return types:

```cadl
model Text is string {
  @Cadl.Http.header("content-type") contentType: "text/plain";
};
model Image is bytes {
  @Cadl.Http.header("content-type") contentType: "application/octet-stream";
}

@route("/doStuff")
@overload("doStuff")
@post op doStuffWithText(data: Text, @query encoding?: string): int32;


@route("/doStuff")
@overload("doStuff")
@post op doStuffWithImage(image: Image): int64;
```

```python
@overload # <-- No, this is not the Cadl @overload - this is the standard python typing.overload decorator.
def do_stuff(data: str, *, encoding: Optional[str]=None) -> int:
    ...

@overload
def do_stuff(data: bytes) -> int:
    ...
```

## Representation in OpenAPI

OpenAPI suffers from not being able to represent different logical operations for the same path. Autorest-Swagger has addressed most of this issue through the use of the `x-ms-paths` vendor extension. OpenAPI3 added support for `oneOf` and per-content-type schemas. 

The Autorest-Swagger representations can use `x-ms-paths` to most faithfully represent the Cadl document. OpenAPI3 will be a lossy translation with a "permissive sum type" for parameters and responses per content-type. 

> Permissive sum type is a type that has all properties that can be present across all schemas, with the loosest restrictions across all schemas. That means that nothing is required unless it is required across all schemas, if there are restrictions on size, it will default to the largest/most permissive size etc.

## New syntax/language support:

We should not add core Cadl language support for overloads, but rather a) enable multiple operations to map to a single route and b) optionally provide an `@overload` decorator hint that the intent is for operations to have the same name. This mainly impacts/exposes limitations in emitters. Optionally, allow `@friendlyName` to do duble-duty as an naming hint when applied to an operation instead of inventing a new parameter.

> Issue: `@overload` values merge silently - meaning that accidental naming conflicts would be silently accepted. However, this could be addressed by taking an enum value rather than a string.

### Rationale

Adhering to the following ground rules:

- Do not introduce capabilities that force emitters to "make up" (infer) names (beyond what they already have to)

The rules around what is a valid overload and what is not differs greatly among emitters (assuming that the emitter supports overloads in the first place). For example, Python can differentiate based on parameter name (for keyword-only arguments), whereas most other languages only supports based on the parameter type. 

For OpenAPI, the closest thing to an overload is a route with a union (`oneOf`/`anyOf` request body or different content types) for the same path/http method combination.

**Comment by markcowl** [comment]
implementation issues:
https://github.com/microsoft/cadl/issues/756
https://github.com/Azure/cadl-azure/issues/1744
