### ISSUE TITLE
Add untemplated OkResponse to cadl.http

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#666]
We have an `OkResponse<Body>`, but for WebPubSub, it would be nice to have an OkResponse that doesn't have a body, per https://github.com/Azure/azure-rest-api-specs/blob/39c7d63c21b9a29efe3907d9b949d1c77b021907/specification/webpubsub/data-plane/WebPubSub/stable/2021-10-01/webpubsub.json#L292

**Comment by markcowl** [comment]
Yeah, we have needed to do this for a bit, it is tracked here: #545.  Closing this one as a duplicate

**Comment by annelo-msft** [comment]
@markcowl, I believe you that this is a duplicate, but I'm not sure you've linked the correct issue.  Can you confirm, I'd love to be able to track the progress of this work.
