### ISSUE TITLE
Model properties of union type <T | null> should be handled as reference type of <T> rather than "object"

### ISSUE THREAD

**Issue by imakhlin** [microsoft/cadl#668]
Model properties of union type `<T | null>` should be handled as reference type of `<T>` rather than "object".
Autorest code generator for csharp is unable to identify actual resource type and creates new type name as concatination of <model.name> and <memberName> which is not exactly what users expect in my opinion.

Example:

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0K0xtvcGVuYXBpxB4NCnVzaW5nIENhZGwuSHR0cDvNElJlc3TSEsQFb3VyY2XJG09wZW5BUEnFUUBkb2MoIkV4YW1wbGU6IGRlbW9uc3RyYXRlIGNvZGUgZ2VuZXJhdGlvbiBmb3Igb3DEC2FsIG51bGxhYmxlIHVuaW9ucy4iKQ0KbW9kZWwgRm9vIHsNCiAgxltSZWZlcmVuY2UgdG%2FTP3Byb3BlcnR5IG9mxksgdHlwZcVPICBiYXI%2FOiBCYXIgfMUyOw0KfeQAtcZpxBjFaWJvbzogc3RyaW5nyCJAdGFnKCJT5QDWIFNlcnZpY2XEVEByb3V0ZSgiL3PFG8QTbmFtZXNwYWNlIE1pY3Jvc29mdC5BRFAuxz3rAMvpASb9ARrxAMZA5ADixSlJZMlFT8cvVcQuxyjnAJxmb2%2FHEXBvc3TECW9wINQ3KMQcKTogT2tSZXNwb25zZTxGb28%2B5AEE)

**Comment by johanste** [comment]
OpenApi differs from C# in that it is the type itself that is considered nullable or not, not the property. So `Bar | null` is/requires a different type/schema than `Bar`. Not sure how to express this better in OpenAPI short of (potentially) generating two types, one nullable and one not nullable for `Bar`. A C# emitter consuming Cadl directly should be able to generate better code. 

[Added property in playground to illustrate nullable vs. non-nullable `Bar`](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0K0xtvcGVuYXBpxB4NCnVzaW5nIENhZGwuSHR0cDvNElJlc3TSEsQFb3VyY2XJG09wZW5BUEnFUUBkb2MoIkV4YW1wbGU6IGRlbW9uc3RyYXRlIGNvZGUgZ2VuZXJhdGlvbiBmb3Igb3DEC2FsIG51bGxhYmxlIHVuaW9ucy4iKQ0KbW9kZWwgRm9vIHsNCiAgxltSZWZlcmVuY2UgdG%2FTP3Byb3BlcnR5IG9mxksgdHlwZcVPICBiYXI%2FOiBCYXIgfMUyO8QVem9vxhU7DQp95ADDxnfEJsV3Ym9vOiBzdHJpbmfIIkB0YWcoIlPlAOQgU2VydmljZcRiQHJvdXRlKCIvc8UbxBNuYW1lc3BhY2UgTWljcm9zb2Z0LkFEUC7HPesA2ekBNP0BKPEA1EDkAPDFKUlkyUVPxy9VxC7HKOcAnGZvb8cRcG9zdMQJb3Ag1DcoxBwpOiBPa1Jlc3BvbnNlPEZvbz7kAQQ%3D)

**Comment by johanste** [comment]
> `{
  "allOf": [{ "$ref": "#/components/schemas/T" }],
  "nullable": true
}`
>
> @johanste Is that valid? Does autorest support it? If so, it seems like the most readable and DRY way to express T | null without making up names.

No. 

*Well, I think it **technically** is valid OpenAPI, but it doesn't do what you want it to do. It is generally not possible to make a "derived" type more permissive than the type it does an `allOf` of. So what you have done is basically expressed a somewhat redundant way that, yeah, it still has to be a `#/components/schemas/T`.*

**Comment by johanste** [comment]
Now, it looks like things may have changed in openapi 3.1 and `null` has (finally) become a valid type in openapi. So you could probably to an/a `anyOf` or `oneOf` between `Bar` and `null` there. As it stands today, it would still leave autorest and friends unhappy, though, since they do not understand `anyOf` or `oneOf` constructs.

**Comment by nguerrera** [comment]
> No

Yeah, I wasn't hopeful here, but it had to be ruled out 🤣

**Comment by nguerrera** [comment]
This actually "works" now and does the allOf we said was wrong above as of #773

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0K0xtvcGVuYXBpxB4NCnVzaW5nIENhZGwuSHR0cDvNElJlc3TSEsQFb3VyY2XJG09wZW5BUEnFUUBkb2MoIkV4YW1wbGU6IGRlbW9uc3RyYXRlIGNvZGUgZ2VuZXJhdGlvbiBmb3Igb3DEC2FsIG51bGxhYmxlIHVuaW9ucy4iKQ0KbW9kZWwgRm9vIHsNCiAgxltSZWZlcmVuY2UgdG%2FTP3Byb3BlcnR5IG9mxksgdHlwZcVPICBiYXI%2FOiBCYXIgfMUyOw0KfeQAtcZpxBjFaWJvbzogc3RyaW5nyCJAc2VydmljZVRpdGxlKCJ05AFfKQ0KQHRhZygiU%2BUA7SBTxiPFGHJvdXRlKCIvc8UbxBNuYW1lc3BhY2UgTWljcm9zb2Z0LkFEUC7HPesA4ukBPf0BMfEA3UDkAPnFKUlkyUVPxy9VxC7HKOcAnGZvb8cRcG9zdMQJb3Ag1DcoxBwpOuQBieQBDw%3D%3D
