### ISSUE TITLE
Open API emitter emits `@summary` in invalid places

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#670]
The VS Code Cadl plugin allows me to put a `@summary` tag on an operation parameter:

![image](https://user-images.githubusercontent.com/21269347/176280245-585d2dd0-f001-4165-986b-d32d7d3aa8aa.png)

This results in an invalid swagger schema:

![image](https://user-images.githubusercontent.com/21269347/176280507-3a03831b-9976-438e-8dc0-cac11b0eaf77.png)

From the Swagger Docs, it looks like "summary" is intended for operations and "description" is intended for parameters:
https://swagger.io/docs/specification/2-0/describing-parameters/

Our language generators are not able to read the input swagger file, and fail with this error:

  error   | schema_violation | Schema violation: must NOT have additional properties (paths > /api/hubs/{hub}/groups/{group}/connections/{connectionId} > put > parameters > 0)
    additionalProperty: summary
      - file:///C:/src/azure-sdk-for-net/sdk/template/Azure.Template/src/swagger/openapi.json:96:11

**Comment by nguerrera** [comment]
We should probably error out here. I think the user should be required to use `@doc` to get `description` in OpenAPI. We once had only `@doc` and logic that tried to be smart about whether to emit as `summary` or `description`, but some elements can have both.

We could also consider skipping @summary on invalid elements with the justification that another output format may allow @summary in more places. Or the OpenAPI emitter could merely warn that it is ignoring it.

**Comment by markcowl** [comment]
Feels like the OpenAPI emitter should ignore it - it is still valid documentation, just not usable there.  For Azure APIs, there will be a linting rule that requires an `@doc` for these, so likely no additional warning is required.

**Comment by timotheeguerin** [comment]
This is a problem only with cadl-autorest. In openapi3 the summary shows up under schema which is good. https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKb3AgdGVzdChAc3VtbWFyeSgiRm9vIikgQHF1ZXJ5IHNvbWU6IHN0cmluZynICTsK

**Comment by timotheeguerin** [comment]
Actually this is wrong in both openapi3 and swagger 2.0 `summary` is only allowed on the operation
