### ISSUE TITLE
Need a way to specify different `@server` endpoints on different clients described in Cadl

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#678]
The two Confidential Ledger clients in the .NET SDK, [ConfidentialLedgerClient](https://apiview.dev/Assemblies/Review/7e9dd9920e324259b8a3653c313b0c7f#Azure.Security.ConfidentialLedger.ConfidentialLedgerClient) and [ConfidentialLedgerIdentityServiceClient](https://apiview.dev/Assemblies/Review/7e9dd9920e324259b8a3653c313b0c7f#Azure.Security.ConfidentialLedger.ConfidentialLedgerIdentityServiceClient) each have a different endpoint definition in the ConfidentialLedger REST API:

- [ledgerUri](https://github.com/Azure/azure-rest-api-specs/blob/f68e478437a9065651c982788769337fc4d8fb37/specification/confidentialledger/data-plane/Microsoft.ConfidentialLedger/stable/2022-05-13/confidentialledger.json#L9)
- [identityServiceUri](https://github.com/Azure/azure-rest-api-specs/blob/f68e478437a9065651c982788769337fc4d8fb37/specification/confidentialledger/data-plane/Microsoft.ConfidentialLedger/stable/2022-05-13/identityservice.json/#L9)

In the draft Cadl definition for ConfidentialLedger, I've tried adding multiple `@server` blocks to describe both endpoints.  (see: https://github.com/Azure/cadl-azure/pull/1637/files#diff-9cb59a296d6b309750bfd0647c7860b6543ef3a241963b6f5601a676a76e46fcR13)

It would be ideal to have a designated way to specify different endpoints for different clients described for the same service.  Thanks!

**Comment by markcowl** [comment]
This might be tied in to how we define clients - if clients are defined by namespaces, then the `@server` decorator attached to a namespace would define the server parameters for that namespace's client.  Will leave open as part of the client designation design issue.

**Comment by markcowl** [comment]
handle with : https://github.com/microsoft/cadl/issues/656

**Comment by daviwil** [comment]
Implementation issue: https://github.com/microsoft/cadl/issues/778
