### ISSUE TITLE
Allow defining multiple services per cadl file

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#679]
Right now we assume in a few places (getAllRoutes, getServiceNamespace) that only a single service is defined per cadl compilation. I don't believe this restriction is justified and it can be useful to define multiple services in a single cadl. An example scenario is defining an app that has two function app endpoints, or a function app and an app service with different APIs.

**Comment by annelo-msft** [comment]
Seems related to https://github.com/microsoft/cadl/issues/678 ?

**Comment by markcowl** [comment]
Potentially, although the same server can be described through different @server endpoints

**Comment by timotheeguerin** [comment]
Actions:
- make `getServiceXYZ` allow multiple
- `getAllRoutes` takes in which service namespace
- rename `@serviceTitle` (deprecate) and others in `@service` decorator
- [More design] solve importing a service to get types but not take all the service description(don't want to gen service)

**Comment by timotheeguerin** [comment]
Notes from design meeting

```
@serviceTitle("FrontEnd")
@openapi  // in "@cadl-lang/openapi"
@client
namespace MyOrg.FrontEnd {
  
}

@service({title?: string })
@serviceTitle("InternalBackEnd")
@openapi
@useHttp
@azureFunctions({AppServicePlan: "foobar"})
namespace MyOrg.InternalBackEnd {
    
}

@grpc.package
namespace MyOrg.Foo {

}

// in sidecar.cadl
@@openapi(FrontEnd)
```
