### ISSUE TITLE
Sample in readme doesn't compile out of the box

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/cadl#68]
https://github.com/microsoft/cadl/blob/5068fc43935e331941024fdf47716fa8a3a027c7/README.md?plain=1#L96-L105

In order to get this sample to compile I had to remove the using and change @route to @path.

Once it compiled, the file generated did not contain a path.

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "(title)",
    "version": "0000-00-00"
  },
  "tags": [],
  "paths": {},
  "components": {}
}

```

**Comment by nguerrera** [comment]
The packages need to be published with the change to `@route`, I think.

**Comment by nguerrera** [comment]
I will kick that off now.

**Comment by darrelmiller** [comment]
I'm curious about the motivation to change the name from path to route?  Isn't route a highly implementation dependent term?  Route is one of those annoying words that people pronounce differently and overlaps with the pronunciation of the term root. which is also an important term when describing APIs.

**Comment by nguerrera** [comment]
cc @daviwil @johanste
