### ISSUE TITLE
Possible multi cadl dependency issue with file references

### ISSUE THREAD

**Issue by joheredi** [microsoft/cadl#680]
I'm prototyping a new emitter and found a weird behavior when debugging, where `getAllRoutes` would return 0. The same code ([Http sample](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCm5hbWVzcGFjZSBEZW1vxxg7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdAewogIEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsdWRcQMxVVjb2Rly0BtZXNzYWdlymR9CgppbnRlcmbkALLmAI3nALTFP0DkAJ1saXN0KCk6xx9bXSB8xmHEUUByb3V0ZSgid8Uccy97aWR9IinGOHJlYWQoQHBhdGjrANfJSM1GcG9zdCBjcmVhdGUoQGJvZHkgxAXIK9Y0x3pjdXN0b21HZXTId8kR6gC0yjh9Cg%3D%3D)) would generate expected output in the playground.

Talked to @bterlson and the hypothesis is that this may be caused because of multiple copies of CADL being loaded due to my project structure. This is my structure

![image](https://user-images.githubusercontent.com/21109913/176975872-ff7c142d-48f5-4ee1-b027-9fa0f5d49501.png)

Where `cadl-rlc` is the emitter I'm prototyping and `cadl-test` is a sample CADL spec I'm using to debug. 

This is how I reference the emitter from `cadl-test`

**packag.json**
```json
{
  "name": "cadl-test",
  "dependencies": {
    "@azure-tools/cadl-ts-rlc": "file:../cadl-rlc",
    "@cadl-lang/compiler": "latest",
    "@cadl-lang/rest": "^0.15.0"
  },
  "private": true
}
```

**cadl-project.yaml**
```yaml
emitters:
  '@azure-tools/cadl-ts-rlc': true
```

And I'm compiling with

```bash
npx cadl compile .
```

**Emitter - cadl-rlc/scr/indext.ts**

```typescript
import { Program } from "@cadl-lang/compiler";
import { getAllRoutes } from "@cadl-lang/rest/http";

export async function $onEmit(program: Program) {
  const [routes, _diagnostics] = getAllRoutes(program);
  console.log(routes.length);
  // 0
}
```

**Comment by markcowl** [comment]
- warning if library is loaded twice
