### ISSUE TITLE
Override `route`

### ISSUE THREAD

**Issue by lmazuel** [microsoft/cadl#685]
For instance:

```
@route("/foo")
interface OpGroup {
  @get op1();
  // many operations
  @routeOverride("/bar")
  @get op12():
}
```

IOW, I have many operations that shares the same route, but I want the last one to replace the interface `route`. There are situation out there, where operation groups are based on several blocks of CRUD together, that it may be interesting to avoid duplication of `route`, which I have to do if most are shared, but at least one is not.

Current workaround to at least avoid duplication:
```
alias commonPath = "/foo";

interface OpGroup {
  @route(commonPath)
  @get op1();
  // many operations that uses commonPath
  @route("/bar")
  @get op12():
}
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2VUaXRsZSgiRFBHQ2xpZW50IinJG1ZlcnNpb24oIjEuMC4wxBlkb2PFKyBTd2FnZ2VyLCB0aGlzIGlzIHRoZSBpbml0aWFsIHPGHSBhIMdJIGNvdWxkIGRvxERDYWRsLlJlc3QucHJvZHVjZXMoImFwcGxpY2F0aW9uL2pzb27OKGNvbnN1bdcobmFtZXNwYWNlIMUxVGVzdMR2ZXI7CnVzaW5nxhdIdHRwOwoKbW9kZWwgV2lkZ2V0IHsKICBAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9CgpAZXJyb3LHVkXEDMVVY29kZctAbWVzc2FnZcpkfegAiVBvc3RJbnB15gCMICB1cmzNJmFsaWFzIGFueSA9xyJAc3RhdHVzQ29kZSDKCzogMjAwxGsgIEBib2R5IMQFOiB7fTsKfeQB63JvdXRlKCIv5wGPRHJpdmXkATxpbnRlcmbkATxwYXJhbXPFZckuxRRldGVycyIpxBjlAf1IZWFkIHJlcXVlc3QsIG5vxzouXG4gSeYB%2F2x5IGhhc8QbcXVlcnnGIcVHLiBBZnRlciBldm9sdeQBxCwgYSBuZXcgb3DEDmFs0DLkAllhZGRlZOYAgWjEfMQFTm9QxXYoKTrkAR47Cv8AtygiR2V0IHRydWUgQm9vbGVhbiB2YWx1ZSBvbiBwYXRo7gC%2Bb27nAMNvbmXlAOtpcmVkIFHlAJvFeMRd%2FwDM%2FwDMIEDkAoFnZXRSx18o5gG95QCsSSBhbSBhynrJQ8U6ICBAz1roAjMK%2FwEO6gEO7gGq7QDnz1wgYW5kxSH4ANcuIP8BCf8BCUDkAv5wdekBCU%2FHNv8BEfQBEcgg5QGk6AEVLOQBDs5JbuoAm9dKyCDFSj%2F%2FAWDzAWBQT1NUIGEgSlNPTsYWcG9zdCDEBekCQHPzAOHlA7vJUS4gTecCjHZhbGlkxU4gZW50cnnkAUJ75gQtXCJodHRwOi8vZXhhbXBsZS5vcmcvbXlpbWFnZS5qcGVnXCIgfegA3c5gOuoEfwogIPQA3G1vcmXqALH%2FA074A07oAmL6AkH%2FAkD%2FAkDnA0n6Ajj%2FAe%2F6Ae%2FqARV9Cg%3D%3D)

**Comment by allenjzhang** [comment]
Radius's scenario was to able to replace `/subscription/id/resourcegroup/name/...` to a more morephable `/{rootScope}/...` that can be either the normal ARM one `/subscription/id/resourcegroup/name/...` or `/provider/...`.  This has not been approved by ARM review anyway. Thinking about it, nor do I want them to do that even if we have a @routeOverride for ARM.

Thankfully I was able to provide Radius with a customArm cadl file to affect the route prefix segment. They just need to run cadl twice to get the correct swaggers respectively. I am gonna keep this out of the route conversation at this point.

**Comment by allenjzhang** [comment]
David to investigate allowing route composition from multiple interfaces to avoid using @routeOverride.

**Comment by timotheeguerin** [comment]
Was this meant to be closed?
