### ISSUE TITLE
If an operation is not inside an interface, don't use namespace as operation group in OpenAPI emitter

### ISSUE THREAD

**Issue by lmazuel** [microsoft/cadl#689]
Right now `interface` name becomes operation groups, but without `interface`, the emitter uses the last part of the namespace as operation group. This should not do that, and create operation at the root in the OpenAPI spec.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCm5hbWVzcGFjZSBEZW1vxxg7CnVzaW5nIENhZGwuSHR0cDsKCm1vZGVsIMdAewogIEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsdWRcQMxVVjb2Rly0BtZXNzYWdlymR9CgppbnRlcmbkALLmAI3nALTFP0DkAJ1nZXQoKTrHHiB8xl7GdXJvdXRlKCIvZm9vIikKxS5vcMQxMtMy)

**Comment by markcowl** [comment]
- remove operation group for the root namespace
- verify that there is a mechanism for overriding the default operation group

**Comment by markcowl** [comment]
estimate: 3
