### ISSUE TITLE
Operation without @route when inside a namespace doesn't get included in openapi output

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#700]
```
namespace DemoService;

op test(): string;
```
[link](https://cadlplayground.z22.web.core.windows.net/?c=bmFtZXNwYWNlIERlbW9TZXJ2aWNlOwoKb3AgdGVzdCgpOiBzdHJpbmc7) 

however both of those work and produce the openapi operation
```
op test(): string;
```
[link](https://cadlplayground.z22.web.core.windows.net/?c=b3AgdGVzdCgpOiBzdHJpbmc7) 

```
import "@cadl-lang/rest"; 
namespace DemoService;

@Cadl.Http.route("/") op test(): string;
```
[link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOyAKbmFtZXNwYWNlIERlbW9TZXJ2aWNlOwoKQENhZGwuSHR0cC5yb3V0ZSgiLyIpIG9wIHRlc3QoKTogc3RyaW5nOw%3D%3D) 

Could argue that because the `DemoService` namespace doesn't have service metadata we don't want to include it in the generated output but then case 3 shouldn't also produce anything.

**Comment by markcowl** [comment]
We should have short design discussion on what we want to do in the case of no http metadata

**Comment by timotheeguerin** [comment]
Scenario 1: Show a warning that emitter didn't find any operations as the service namespace  couldn't be found
```
namespace DemoService;

op test(): string;
```

Scenario 2: Stay the same -> emit operation at `/` 
```
op test(): string;
```

Scenaario 3: @route is not a special case shouldnt' work and show same warning as scenario 1
```
import "@cadl-lang/rest"; 
namespace DemoService;

@Cadl.Http.route("/") op test(): string;
```
