### ISSUE TITLE
Add support for formData request bodies.

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#704]
Add support in the openapi3 emitter for operations that accept parameters in a `multipart/form-data` request body.

**Comment by timotheeguerin** [comment]
I think for openapi3 it just works as the only thing is you need a different content type 

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKQHBvc3Qgb3AgdGVzdCgKICBAaGVhZGVyIGNvbnRlbnRUeXBlOiAiYXBwbGljYXRpb24vZm9ybS1kYXRhIizEMGJvZHkgxAU6IHsKICAgIG5hbWU6IHN0cmluZzvFEmZpbGU6IGJ5dGVzxBF9Cik6IHZvaWQ7Cg%3D%3D


for cadl-autorest we don't support it
