### ISSUE TITLE
[Implementation] Cadl developer docs

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#719]
Implementation issue for https://github.com/microsoft/cadl/issues/131

Approved design: https://gist.github.com/nguerrera/01158db039e103dd37201c66978ce10b

This issue tracks parsing the comments into data you can retrieve from nodes in the AST and nothing more. It does not track consuming the data for signature help / intellisense, etc.

**Comment by markcowl** [comment]
@nguerrera Can you add an estimate for this?

**Comment by nguerrera** [comment]
estimate: 13 (it showed already as such in project for me)

**Comment by markcowl** [comment]
@nguerrera Yeah, I found it in the project, thanks!
