### ISSUE TITLE
Formatting in playground should be undoable

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#721]
You should be allowed to undo a format (Ctrl/Cmd+Shift+F) in playground with Ctrl/Cmd+Z. This works in VS Code. It would be particularly useful when the formatter has a bug as in #720

**Comment by bterlson** [comment]
It's more than undoing I think, because its the save gesture that puts the code in the url. I fight this in VSCode too, end up needing the "save without formatting" gesture.

**Comment by nguerrera** [comment]
We don't currently format on Ctrl+S in the playground so I don't think we need that gesture (yet).

VS Code does have one:
![image](https://user-images.githubusercontent.com/75470/179303997-68429158-4fb8-495d-9d2d-d9bc54a85071.png)

**Comment by timotheeguerin** [comment]
> We don't currently format on Ctrl+S in the playground so I don't think we need that gesture (yet).

I did explicitly think about not doing that so if there was a formatter bug it could be shared.

**Comment by nguerrera** [comment]
Yeah, I don't think we need format-on-save in playground. If we did then we'd need save-without-formatting and/or option to enable/disable it as VS Code does. But I don't see a lot of value. Format-on-save is useful to configure in a repo that enforces formatting, but I don't think we need it in a playground.

So I would just fix this literal issue: have the separate format gesture make an undoable edit and call it good.

**Comment by markcowl** [comment]
estimate: 2
