### ISSUE TITLE
Allow `@secret` on model members

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#723]
Right now it works only if you apply it to a model that `is string`, but I tend to think about certain fields of models being secret rather than the datatype being secret itself. Maybe I'm not alone? At least `@secret password: string` is easier to type than `@secret model PasswordString is string; password: PasswordString;`

**Comment by markcowl** [comment]
This would simplify both modeling and review

**Comment by markcowl** [comment]
estimate: 3
