### ISSUE TITLE
Prevent model @key properties from being marked optional?

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#736]
A discussion came up as a result of PR #735 about whether `@key` properties in model types should even be allowed to be marked as optional.

Here's an example of one in a `cadl-azure` sample:

https://github.com/Azure/cadl-azure/blob/1ceb9174f1a6aa6322dee98d0593ef31933a9e0a/packages/cadl-samples/data-plane/languageqna/Interface/questionanswering-authoring_models.cadl#L23-L26

Should this be allowed?  Should the `@key` decorator raise an error diagnostic when the key property is optional?

**Comment by allenjzhang** [comment]
@key uniquely identifies the resource model. It doesn't make sense that it is optional.
