### ISSUE TITLE
Reconsider behavior of primitives with intersection, spread, and is+properties

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#737]
It's weird that you can do this:

```
alias T1 = string & int32;
alias T2 = {} & string;
alias T3 = SomeModel & string;
```

I'm not sure what this *should* mean (if anything), but right now it basically creates a new anonymous type with the properties of the non-intrinsics in the intersection. You can sprinkle `& string` strangely around and getEffectiveType just makes it a no-op (previously it would cause inlining as the name would get lost).

This is also weird and basically a no-op too:

```
model M {
  ...string;
}
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKbW9kZWwgV2lkZ2V0IHsKICBAa2V5IGlkOiBzdHJpbmc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUiOwp9CgoKCmludGVyZmFjZcdVU2VydmljZcZcZ2V0CiAgbGlzdCgpOiAox3cmx2wpW13EXsQpcm91dGUoInfFIXMve2lkfSIpxUDEH3JlYWQoQHBhdGjrAKopOiB7Li4uxlQsIC4uLsYYIH3kAJo%3D)

This is also questionable and `anotherProp` just disappears:

```
model M is string {
  anotherProp: int32;
}
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKbW9kZWwgV2lkZ2V0IGlzIHN0csQjewogIGFub3RoZXJQcm9wOscYOwp9CgpAcm91dGUoIi8iKQppbnRlcmZhY2XHQ1NlcnZpY2XFQEDEU2xpc3QoKTrHH1tdxEI%3D)

I think disallowing `extends <primitive>` didn't go far enough.

I find that we regularly get tripped up into treating these primitives like any other empty model, and the results are suprising. I wish primitives and models were disjoint in the compiler typing. That would cause an issue for `model Foo is <primitive>;` but I am starting to wish there was another representation for primitive+annotation than `model is`. Maybe we can avoid breaking as hard  by representing it differently in the semantic model while still reusing `model is <primitive>;` syntactically for this case.

**Comment by timotheeguerin** [comment]
To note sample 1 & 3 above will create errors wth the type relation PR https://cadlplayground.z22.web.core.windows.net/prs/571/?c=YWxpYXMgVDEgPSBzdHJpbmcgJiBpbnQzMjsNCsccMiA9IHt9ICbHIcoZMyA9IFNvbWVNb2RlbMwgDQptxRNNIHsNCiAgLi4uyRt9yx4yIGlzyHbFKWFub3RoZXJQcm9wOukAhn0%3D

**Comment by bterlson** [comment]
I think spreading something with a never indexer should be an error (which would make sample 2 an error).

**Comment by bterlson** [comment]
Re: "you can't intersect a primitive", I'm not entirely sure "primitive" is a concept we have or want? E.g. the notion that a primitive could be decorated, and the difference between a primitive like `string` and a literal type like `"hi"`, might be strange. The notion that types have an indexer and sometimes the indexer is `never` which indicates it can never hold properties could be simpler to understand modulo some improvements to the error messages. Just thinking out loud at this point.

**Comment by nguerrera** [comment]
Yeah, maybe something like "Type X cannot be spread because it cannot hold properties" for the error?

Somewhat related, we had an instance of referring to "value type" in the type relations PR and that is also a term we don't want?

**Comment by markcowl** [comment]
@nguerrera, please update

**Comment by nguerrera** [comment]
I will create a new issue
