### ISSUE TITLE
OpenAPI and Swagger emitter incorrectly generates type literal

### ISSUE THREAD

**Issue by lmazuel** [microsoft/cadl#738]
A type literal is a constant, and the way we represent constant in Swagger was a enum with a single value AND not extensible. IOW:
```
        "status": {
          "description": "The status of the capability.",
          "enum": [
            "Default",
          ],
          "type": "string",
          "x-ms-enum": {
            "name": "CapabilityStatus",
            "modelAsString": false
          }
        },
```

Since the emitter do not generate the `x-ms-enum` and `modelAsString` today in that scenario, the Swagger do not represent properly the intent of the CADL.

[OpenAPI3 Playground](https://cadlplayground.z22.web.core.windows.net/?c=Ly8gY2FkbA0KbW9kZWwgVHlwZUxpdGVyYWwgew0KICAgIG5hbWU6ICJkcGciOw0KfQ0KDQpvcCBmb28oKSA6zDE7) / [Swagger Playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvY2FkbC3GEWNvcmUiOwrJJ8UbbGFuZy9yZXN0IjsKdXNpbmcgQcQtLkNvcmUuT3BlcmF0aW9uczsKCm1vZGVsIEVucm9sbG1lbnQgewogIEBrZXnEB0NhZGwuUmVzdC5zZWfEHigiZckqcyIpCiAgaWQ6IHN0cmluZzsKfdJPR3JvdXDMVNUwUmVnaXN05wCV2y5pbnRlcmZhY2UgSW90RHBzUmVzb3VyY2VMaWZldGltZTxUyBI%2BxUZvcCBjcmVhdGUgaXMgyBtDxRJPclJlcGxhY8w0O8YzcmVhZMwxUmVhZNImZGVsZc5ZRMUS0ipsaXN0zChMaXN0zSZ9CgrmAWtIdHRwLnJvdXRlKCIv7gFq6gD76gFdcyBleHRlbmRz%2BAEPyivpARBhdHRl7gCPQWPkAXfLLCwgeyBzb21lUGFyYW3oAYAgfcgXUmVzdWx0yhj%2FAMHpAgb4AMbGHf8Ay%2BsAn8UwPiB71nVy7AJLzXLtAmXqAwTfeTzNN8R3OwoK)

**Comment by nguerrera** [comment]
I believe we interpret straight OpenAPI 2/3 enum as "not extensible" and therefore believe we shouldn't need to use x-ms-enum for this case. Does autorest default to extensible in the absense of x-ms-enum + modelAsString=false?

Also, I think the Swagger Playground link should have been:

https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=Ly8gY2FkbAptb2RlbCBUeXBlTGl0ZXJhbCB7CiAgICBuYW1lOiAiZHBnIjsKfQoKb3AgZm9vKCkgOswtOw%3D%3D

**Comment by lmazuel** [comment]
@nguerrera yes, autorest does default to extensible, meaning if you want to model a constant in Swagger you have to use x-ms-enum to tag the enum as "modelAsString:false". This is the trigger for "autorest from Swagger" to get M4 to expose this as a constant. You won't get fidelity of intent without having it in the generated Swagger :(

cc @timotheeguerin

**Comment by nguerrera** [comment]
OK, I would argue the autorest interpretation is the one that is "incorrect" as OpenAPI 2 and 3 ref to JSON schema for the meaning of "enum", which in turn [states](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-enum):

> An instance validates successfully against this keyword if its value is equal to one of the elements in this keyword's array value"

which implies not extensible.

I suppose we could change cadl-autorest as it exists to feed into autorest, but I think the openapi3 behavior should remain unchanged.

**Comment by timotheeguerin** [comment]
Yeah, I think in cadl-autorest we should add `x-ms-enum.modelAsString=false` to be consistent with what enums are doing but there is nothing to change in the openapi3 emitter that is not adding any extensions

**Comment by lmazuel** [comment]
As long as this is clear that ARM team that goes through translation and not direct CADL have to be using cadl-autorest to translate, and can't use OpenAPIv3 emitter, I'm fine.

**Comment by timotheeguerin** [comment]
if it was just about autorest we should have `cadl-autorest` also emit openapi v3 but with extensions. But I think we have to do all of that to satisfy linter in azure-rest-api repository

**Comment by markcowl** [comment]
I was unaware that m4 automatically treated swagger enums as extensible.  It is harmless to add the extension, and if it helps with client generation from swagger, we should make it so. We want to be careful about the impact on discriminator values when we fix this.

@lmazuel Are we using constant values in any specs that we need to model right away, or can we defer this fix until next month?

**Comment by lmazuel** [comment]
@markcowl you can defer to next month, we discovered it while doing a review of features, not because a particular service had a problem.

**Comment by markcowl** [comment]
estimate: 1

**Comment by jianyexi** [comment]
One question is how to generate the x-ms-enum.name,  seems not make sense to use the literal value.

**Comment by timotheeguerin** [comment]
The name was made optional in autorest for just that reason so I would omit it

**Comment by jianyexi** [comment]
> The name was made optional in autorest for just that reason so I would omit it

But name is required by this extension, see https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-enum

**Comment by timotheeguerin** [comment]
Need to update the doc, it isn't required anymore.

**Comment by jianyexi** [comment]
this already fixed in https://github.com/Azure/cadl-azure/pull/1893
