### ISSUE TITLE
Reconsider naming ModelTypeProperty vs. ModelPropertyType naming

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#739]
At one point, I think the justification for this seeming naming discrepancy was that it was a "property of a model type" and not "a type that is a model property", but model properties *are* `Type`s.

I am also starting to wonder if it wouldn't be best to drop the `Type` suffixes and have `Model`, `Operation`, `ModelProperty`, etc.  These names are shorter, sufficiently distinguished from the `XxxNode` syntax counterparts, and match the Type.kind values 1:1. I also find it more approachable for the casual emitter author who probably doesn't spend a lot of time thinking about these entities as "types".

**Comment by timotheeguerin** [comment]
+1 to fixing the order, keep trying to type `ModelPropertyType`.
for removing `Type` all together, don't have an opinion

**Comment by nguerrera** [comment]
Turns out `ObjectType` and `FunctionType` can't drop suffix as that would conflict with core types `Object` and `Function`. I'd also keep them for IntrinsicType since `Intrinsic` seems too generic.

It's also worth noting that UnionTypeVariant is a little bit like ModelTypeProperty in inconsistency.

So here's a proposal, with comments next to existing `type Type` variants. `-> X` means "rename to X". `= X` means "keep name X".

```
export type Type = // = Type
  | ModelType // -> Model
  | ModelTypeProperty // -> ModelProperty
  | InterfaceType // -> Interface
  | EnumType // -> Enum
  | EnumMemberType // -> EnumMember
  | TemplateParameterType // -> TemplateParameter
  | NamespaceType // -> Namespace
  | OperationType // -> Operation
  | StringLiteralType // -> StringLiteral
  | NumericLiteralType // -> NumericLiteral
  | BooleanLiteralType // -> Boolean
  | TupleType // -> Tuple
  | UnionType // -> Union
  | UnionTypeVariant // -> UnionVariant
  | IntrinsicType // = InstrinsicType
  | FunctionType // = FunctionType
  | ObjectType // = ObjectType
  | ProjectionType; // -> Projection
  ```

**Comment by markcowl** [comment]
Remove type suffix as above: yes
 - deprecate /alias: yes
 - guide to migration: yes
 - tooling for migration: 
   - consider as separate issue for code modification tooling
   - Also how to modify Cadl code under deprecation (possibly using code fixes)

**Comment by markcowl** [comment]
@nguerrera Please file an implementation issue for this.  I will file issues for migration tooling

**Comment by nguerrera** [comment]
Filed #783
