### ISSUE TITLE
Referencing a template parameter inside an anonymous model fails

### ISSUE THREAD

**Issue by tg-msft** [microsoft/cadl#743]
I'm trying to create mixins like:

[Playground Link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/prs/1730/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0KDQp1c2luZyBDYWRsLkh0dHDFFG1vZGVsIE1peGFibGU8DQogIFRSZXNvdXJjZSwgLy8gPC0tIGVycm9yOiBDb3VsZG4ndCBnZXQgc2NoZW1hIGZvciB0eXBlIFRlbXBsYXRlUGFyYW1ldGVyxjbEUVZhbHVlRGVmaW5pdGlvbiA9IHsgIHbEFTrKbTsgfSzELUV4dHJhyi1zxS59Pg0Ke8QeLi4uz07FNS4uLtA4DQp95ADfLy8gRXhhbXBsZSBvZiBzdGFuZGFyZCB1c2XoAPtQZXJzb24geyBuYW1lIDogc3RyaW5nOyB9DQpAcm91dGUoInBlb3BsZSIpDQpA5AD7b3AgR2V0xjgoKTrpAT3GEj7lAVfOeGN1c3RvbWl6YeUBAC0gcmXFbSLlAQUiIHRvICJmYXJtIugAlEFuaW1hbOcAlPUAk2HFInPvAJTGOCgpIOoAlcYTLCB7IMRiOsdbOyB95ACo)

```
import "@cadl-lang/rest";

using Cadl.Http;

model Mixable<
  TResource, // <-- error: Couldn't get schema for type TemplateParameter error
  ValueDefinition = {  value: TResource; },
  ExtraDefinitions = { }>
{
  ...ValueDefinition,
  ...ExtraDefinitions
}

// Example of standard use
model Person { name : string; }
@route("people")
@get op GetPerson(): Mixable<Person>;

// Example of customization - rename "value" to "farm"
model Animal { name: string; }
@route("animals")
@get op GetAnimal() : Mixable<Animal, { farm: Animal; }>;
```

**Comment by bterlson** [comment]
[Slightly smaller repro](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0KbW9kZWwgTWl4YWJsZTwNCiAgVFJlc291cmNlLCAvLyA8LS0gZXJyb3I6IENvdWxkbid0IGdldCBzY2hlbWEgZm9yIHR5cGUgVGVtcGxhdGVQYXJhbWV0ZXLGNsRRVmFsdWVEZWZpbml0aW9uID0geyAgdsQVOsptOyB9DQo%2BIHvEMS4uLs80LA0KfQ0KDQpvcCBHZXRBbmltYWwoKSA66QC5e30%2BOw%3D%3D)

Looks like it has to do with an anonymous model as a default referencing a template parameter.

**Comment by markcowl** [comment]
estimate: 5
