### ISSUE TITLE
cadl-autorest emitter do not emit x-ms-pageable for ResourceList

### ISSUE THREAD

**Issue by lmazuel** [microsoft/cadl#745]
[Playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvY2FkbC3GEWNvcmUiOwrJJ8UbbGFuZy9yZXN0IjsKdXNpbmcgQ2FkbC5IdHRwyBFBxD4uQ29yZS5PcGVyYXRpb25zOwoKCm1vZGVsIEZURSB7CiAgQGtleQogIGZ0ZUlkOiBpbnQzMjsKICDEYXVhZ2U6IHN0cmluZzsKfQoKb3AgbGlzdMQ7aXMgUmVzb3VyY2VMaXN0PEZURT47Cgo%3D)

Since the goal of cadl-emitter Swagger emitter is to generate Swagger that autorest can read, `ResourceList` usage must generate a `x-ms-pageable` extension.

**Comment by markcowl** [comment]
@tjprescott Will this be addressed once tha paging implementation is complete?

**Comment by tjprescott** [comment]
@markcowl yes. My open PR ensures Azure.Core.Page<T> emits the x-ms-pageable. And follow up PRs will make resource-manager and providerhub use Azure.Core.Page<T>

**Comment by timotheeguerin** [comment]
@tjprescott has this then been resolved by https://github.com/Azure/cadl-azure/pull/1638 and can it be closed?

**Comment by timotheeguerin** [comment]
Looking at the initial playground link and seeing `x-ms-pageable` in the result I'm going to assume that it is indeed resolved by this PR.
