### ISSUE TITLE
Internal compiler error when referencing interface member

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#746]
[    Playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIEhlbGxvIHsKICBvcCBvbmUoKTogdm9pZDsKfQoKyidXb3JsZMUndHdvIGlzxjgub25lOwp9)

```cadl
interface Hello {
  op one(): void;
}

interface World {
  two is Hello.one;
}
```

Internal Compiler error
File issue at https://github.com/microsoft/cadl
TypeError: Cannot read properties of undefined (reading 'id') at getNodeSymId (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:26341:28) at checkOperationIs (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:26873:36) at checkOperation (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:26817:35) at checkInterfaceMembers (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:27887:28) at checkInterface (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:27869:9) at getTypeForNode (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:26251:24) at checkSourceFile (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:27309:13) at Object.checkProgram (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:27304:13) at createProgram (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:29719:21) at async compile (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:30263:12)

**Comment by timotheeguerin** [comment]
I think this gets fixed with https://github.com/microsoft/cadl/pull/703
