### ISSUE TITLE
realpath in module resolution breaks language server in multi-file cases on Windows

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#751]
I'm about to submit a fix for this as it was really getting in my way as I needed to change .cadl in a lot of samples. When we change import of relative paths to use module resolution, that introduced a realpath which in turn started converting VS Code's normalized lower-case drive letters (annoying but VS Code refuses to change this) back to their canonical uppercase. 

The language server works like this:

1. Find main.cadl for the current document
2. Check that compilation of main.cadl included the current document

If either 1 or 2 fails, then the document is used as its own main file, and step 2 started failing when there are case-mismatches.

So this breaks scenarios like this:

main.cadl
```
import "./common.cadl";
import "./other.cadl";
```

common.cadl
```
model CommonType {}
```

other.cadl
```
// CommonType won't be found 
model OtherType extends CommonType {}
```

**Comment by markcowl** [comment]
estimate: 0
