### ISSUE TITLE
Type relation: Override base model property when using `extends`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#762]
Non implemented part of the type relation proposal.

```cadl
model Parent {
  name: string;
}

model Child extends Parent {
  // Currently now allowed
   name: "abc";
}
```

Rules for override: 
- property type of `Child` should be assignable to property type of `Parent`
- warning if it is the same?

**Comment by markcowl** [comment]
restrict to intrinsic types for now

**Comment by markcowl** [comment]
estimate: 5

**Comment by annelo-msft** [comment]
If possible, we would like to issue a warning/error in the following cases:

-	Base and derived models have properties with the same name, but different types
-	Base and derived models have properties with the same name and type, but base model property is declared as read/write, while derived model property is declared as read-only
-	Base and derived models have properties with the same name and type, but base model property is declared as read-only, while derived model property is declared as read/write

@AlexanderSher FYI

**Comment by bterlson** [comment]
Mentioned this in email also, but I'm not sure what we should do with read/write in core Cadl? Is there a generally useful/accurate-across-all-target-langs thing we can error on? Ensuring same-visibility (or that no visibility is declared) when base property has visibility would solve the above use cases. I also was pondering requiring that subtypes have a subset of visibility flags but you probably want different variance depending on where the model is used? E.g. in some contexts shadowing a read/write with read is ok but not all contexts?

**Comment by annelo-msft** [comment]
I think this relates to a conversation we were having on the DPG side about what visibility represents in terms of the service API, and how it applies with regard to requests and responses (i.e. on a round-trip model, what does it mean for a property to be both required and read-only with regard to the request?).

We were planning to move forward with the assumption that read-only when defined on a resource model means the resource property can only be set by the server.  This would then have the implication that clients never set read-only properties on these models, but required/optional still applies with regard to whether the service would return a value for that property or not.

I'm not sure what the implications are when a model doesn't represent a resource, or if visibility attributes would ever apply in this case.

From an inheritance perspective, it does seem like you could have derived types where sometimes a property is set by the service-only and sometimes the client should provide it.  I'm curious whether we know of any practical instances of this, @johanste?

FYI: @lmazuel, @snagar, @iscai

**Comment by allenjzhang** [comment]
1. Create simple + complex type examples and verify against different languages (TS, Go, C#, C++)
2. If intentions are expressed as designed, we go ahead with this with not just intrinsic types.

**Comment by timotheeguerin** [comment]
Created design issue for override of  intrinsic type implementation https://github.com/microsoft/cadl/issues/1137
