### ISSUE TITLE
Type relation: Remaining properties type

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#763]
Discussion that came out of https://github.com/microsoft/cadl/pull/571.

Do we want a way to specify the type of remaining properties. This is different than the index type which makes sure all the properties are the same type.

```cadl


model Foo {
  age: number;

  // but remaining properties to be string
}
```

**Comment by markcowl** [comment]
For additionalPropeties: true, use:

```cadl
model Foo extends Record<unknown> {
 bar: int32;
}
```

For constrained additional Properties, a separate model is required.

```cadl
model Foo {
  bar: int32;
  additionalStuff: Record<string>;
}
```

- Fix bug on extends Record<string> with incompatible schema
- Ensure openAPI emitters actually emit additionalProperties
- Potentially linting rules around these patterns (discourage Record<unknown>)

**Comment by markcowl** [comment]
- linting rules to discourage extending `record<unknown>` in Azure.Core

**Comment by markcowl** [comment]
currently

```cadl
model Foo extends Record<string> {
 id: int32;
```
This should not work - we should disallow this.

**Comment by mikekistler** [comment]
> This should not work - we should disallow this.

Do you mean that Cadl should not support this (it does today) or that Cadl.Azure should disallow it with linter rules?
