### ISSUE TITLE
Default to `post` when body is present and no verb is specified

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#766]
I feel like it's fine to just use post in this case:

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0Kb3AgZm9vKGE6IHN0cmluZywgYsgLKTogdm9pZDs%3D)

**Comment by bterlson** [comment]
Additional rationale - using `get` by default feels a little arbitrary too, so maybe if we like the no-verb error for body, we should have no-verb error for no-body too?

**Comment by markcowl** [comment]
pri: 2, estimate: 2
