### ISSUE TITLE
getAllRoutes() return operation bodyType model with EMPTY name for cadl-ranch project

### ISSUE THREAD

**Issue by changlong-liu** [microsoft/cadl#785]
When I try to use python emitter to generate cadl-ranch project here: https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/input-basic, I find the tool function getAllRoutes() in route.ts return operation bodyType with EMPTY named model as below picture:
![image](https://user-images.githubusercontent.com/59815250/181442367-b3c181f2-3338-4a01-be1c-78aba3552e7d.png)

We can't generate model with no name, so I expect every model returned from cadl should have a name?

**Comment by nguerrera** [comment]
Hmm, there are definitely situations where the body type can be anonymous, but I would not expect it on that spec. Checking.

**Comment by nguerrera** [comment]
I can't repro yet.

![image](https://user-images.githubusercontent.com/75470/181671973-0349f1e1-f667-4c85-8563-39f7a7250134.png)

I did make a few changes to the spec to get it to compile in isolation with just core libraries so I could debug quickly:

```diff
import "@cadl-lang/rest";
import "@cadl-lang/openapi";
-import "@azure-tools/cadl-azure-core";
-import "@azure-tools/cadl-ranch-expect";

using Cadl.Http;
-using Azure.Core.Operations;

@serviceTitle("InputBasicClient")
@serviceVersion("1.0.0")
@server("http://localhost:3000", "TestServer endpoint")
@doc("Illustrates an input-only model with required reference and value type properties.")
namespace Cadl.TestServer.InputBasic;

@doc("Input Model")
model InputModel {
  @doc("Required string, illustrating a reference type property.")
  requiredString: string;

  @doc("Required int, illustrating a value type property.")
  requiredInt: int32;
}

+@error
+model ErrorResponse {
+  msg: string;
+}

-@scenario
-@scenarioDoc("Generate and send an input-only model with required reference and value type properties.")
@route("/models")
@get
op getModel(@body input: InputModel): Response<200> | ErrorResponse;
```

**Comment by nguerrera** [comment]
You would get an anonymous request body type in these ways:

1. No explicit @body: parameters that are not `@header`/`@query`/`@path` form the properties of an anonymous body:

`op getModel(requiredString: string, requiredInt: int32)`;


2. Same as (1) but via spread into parameter list 
`op getModel(...InputModel)`


3. Explicit @body of anonymous type
`op getModel(@body input: { requiredString: string; requiredInt: int32 })`


In case 2, you can recover the name InputModel using program.checker.getEffectiveType, which is what the OpenAPI emitter does to allow this style. I think we should push that down into the rest layer. I will look at doing that.


But you have:

4. explicit `@body` of named type
`op getModel(@body input: InputModel)`

and that should work as you expect already and that's what I'm seeing...

**Comment by changlong-liu** [comment]
> I can't repro yet.
> 
> ![image](https://user-images.githubusercontent.com/75470/181671973-0349f1e1-f667-4c85-8563-39f7a7250134.png)
> 
> I did make a few changes to the spec to get it to compile in isolation with just core libraries so I could debug quickly:
> 
> ```diff
> import "@cadl-lang/rest";
> import "@cadl-lang/openapi";
> -import "@azure-tools/cadl-azure-core";
> -import "@azure-tools/cadl-ranch-expect";
> 
> using Cadl.Http;
> -using Azure.Core.Operations;
> 
> @serviceTitle("InputBasicClient")
> @serviceVersion("1.0.0")
> @server("http://localhost:3000", "TestServer endpoint")
> @doc("Illustrates an input-only model with required reference and value type properties.")
> namespace Cadl.TestServer.InputBasic;
> 
> @doc("Input Model")
> model InputModel {
>   @doc("Required string, illustrating a reference type property.")
>   requiredString: string;
> 
>   @doc("Required int, illustrating a value type property.")
>   requiredInt: int32;
> }
> 
> +@error
> +model ErrorResponse {
> +  msg: string;
> +}
> 
> -@scenario
> -@scenarioDoc("Generate and send an input-only model with required reference and value type properties.")
> @route("/models")
> @get
> op getModel(@body input: InputModel): Response<200> | ErrorResponse;
> ```

Thank you @nguerrera for taking look at this!
I copied your changes and find it still exists in cadl-ranch project. But the problem disappeared if I update my local cadl-ranch to use latest cadl core in github main branch

So I think the problem is in the released core packages and already get fixed in latest cadl core code.

**Comment by changlong-liu** [comment]
> You would get an anonymous request body type in these ways:
> 
> 1. No explicit `@body`: parameters that are not `@header`/`@query`/`@path` form the properties of an anonymous body:
> 
> ```
> op getModel(requiredString: string, requiredInt: int32)`;
> ```
> 
> 2. Same as (1) but via spread into parameter list
> 
> ```
> op getModel(...InputModel)
> ```
> 
> 3. Explicit `@body` of anonymous type
> 
> ```
> op getModel(@body input: { requiredString: string; requiredInt: int32 })
> ```
> 
> In case 2, you can recover the name InputModel using program.checker.getEffectiveType, which is what the OpenAPI emitter does to allow this style. I think we should push that down into the rest layer. I will look at doing that.
> 
> But you have:
> 
> 4. explicit `@body` of named type
> 
> ```
> op getModel(@body input: InputModel)
> ```
> 
> and that should work as you expect already and that's what I'm seeing...

CC to @iscai-msft, @msyyc, @lmazuel .
To work with the anonymous body model, shall we name it as "[OPERATION][BODY]" in python-emitter?

**Comment by nguerrera** [comment]
> So I think the problem is in the released core packages and already get fixed in latest cadl core code.

Interesting. I am curious what was happening and what fixed this so I will test with released packages.

**Comment by nguerrera** [comment]
Hmm, no repro with latest released package either. In that release there was no `operations.parameters[0].bodyType`, but `operations.parameters[i].body.type` is named:

![image](https://user-images.githubusercontent.com/75470/181752861-5793b2c2-ad35-4d8c-bb06-5d23333bbae6.png)

**Comment by nguerrera** [comment]
Oh, sigh, I think I see. It must be a version mismatch between. If you end up applying `@body` decorator on one version of the rest library then calling getAllRoutes on another version of the rest library, it behaves like `@body` is not there, turning case 4 above into case 1. See also #784. cc @timotheeguerin

**Comment by nguerrera** [comment]
I'll close this against #784

**Comment by changlong-liu** [comment]
> Oh, sigh, I think I see. It must be a version mismatch. If you end up applying `@body` decorator on one version of the rest ...

I see, my environment does be like your said. Thanks @nguerrera !
