### ISSUE TITLE
[versioning] Version enums sometimes become "disconnected" from namespace after projection 

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#786]
While investigating the blocking issue around https://github.com/Azure/cadl-azure/pull/1754, I discovered that enums that are used with the `versioned` decorator on Cadl namespaces sometimes lose their connection to the namespace they are assigned to.

In other words, the `checkIsVersion` function in the versioning library no longer identifies a specific enum member as a version for a particular namespace.  I think versioning projections have something to do with this but I couldn't track down why it was happening.

This seems to happen only under a very specific set of circumstances.  I put together the following minimal repro which requires the branch of that PR.  I've included a couple of tweaks below the repro which will cause the issue to no longer reproduce in case that helps with investigation.

```
import "@cadl-lang/versioning";
import "@azure-tools/cadl-azure-core";
import "@azure-tools/cadl-azure-resource-manager";

@armNamespace
@Cadl.Versioning.versioned(Contoso.Service.Versions)
@Cadl.Versioning.versionedDependency([
  [Contoso.Service.Versions.v2021_06_13_preview, Azure.Core.Versions.v1_0_Preview_1],
  [Contoso.Service.Versions.v2022_04_30_preview, Azure.Core.Versions.v1_0_Preview_1]
])
namespace Contoso.Service {
  using Azure.Core;
  using Azure.ResourceManager;

  enum Versions {
    v2021_06_13_preview: "2021-06-13-preview",
    v2022_04_30_preview: "2022-04-30-preview",
  }
}
```

This repro returns the following errors:

```
/home/daviwil/Projects/Code/adl/packages/cadl-azure-resource-manager/lib/arm.cadl:8:22 - error @cadl-lang/versioning/version-not-found: The provided version 'v1_0_Preview_1' from 'Versions' is not declared as a version enum. Use '@versioned(Versions)' on the containing namespace.
> 8 | @versionedDependency(Azure.Core.Versions.v1_0_Preview_1)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/daviwil/Projects/Code/adl/packages/cadl-azure-resource-manager/lib/arm.cadl:8:22 - error @cadl-lang/versioning/version-not-found: The provided version 'v1_0_Preview_1' from 'Versions' is not declared as a version enum. Use '@versioned(Versions)' on the containing namespace.
> 8 | @versionedDependency(Azure.Core.Versions.v1_0_Preview_1)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Found 2 errors.
```

**Repro Tweaks**

You can make this repro succeed by making one of the following tweaks:

- Remove the `armNamespace` decorator from the `Contoso.Service` namespace
- Rename `Contoso.Service` namespace to `Service`

Somehow this issue requires *both* of these factors to be in place for the issue to reproduce.

**Comment by timotheeguerin** [comment]
Smaller repro without the extra libs https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3ZlcnNpb25pbmciOwoKQHNlcnZpY2VUaXRsZSgiZm9vIikKQENhZGwuVskpLsc0ZWQoQ29udG9zby5TxjfIJXPcNURlcGVuZGVuY3koCiAgWwogICAgW9hJLnYxLCBBenVyZS5Db3LLGGMxXSzfO3Yy2TsKICBdCikKbmFtZXNwYWNlIM9FIHsKICBlbnVtIMg2xRIgIHYxOiAiMjAyMS0wNi0xMy1wcmV2aWV3IuYAjHYyxh4yLTA0LTMwzR59Cn0K%2FAFLyGnsAJbqAL75AJFj5ACRdjFfMF9Qxm1fMd9v8AGF9gEj8gCHUmVzb3VyY2VNYW5hZ2VyIHsKCn0K
