### ISSUE TITLE
Allow trailing comma in tuples

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#789]
We had a bug in the formatter that was adding a trailing comma to multi line tuple but this isn't something we actually support.

From bug https://github.com/microsoft/cadl/issues/787, bug fix the formatter to remove the trailing comma but question is should we allow the other way around and have the formatter add it automatically.

TS/JS support that and prettier (at least our config) will automatically add one. This make it nicer to work with multi line arrays, reducing the number of line changed in diff when adding a new entry at the end and make it easier to move items around.

**Comment by nguerrera** [comment]
+1 we should allow it. 

I am less opinionated on what the formatter should do, but I think following the prettier defaults makes sense. Having the trailing one makes nicer diffs when you add something to the end.

**Comment by nguerrera** [comment]
I'm thinking we should maybe consider allowing trailing in all lists and leave it to the formatter if we have opinions about when not to use it (like in a single line).

When I refactored everything to go throuhg parseList helper, I preserved the cases where trailing delimiter is not allowed, but there's an explicit `trailingDelimeterIsValid: false` for that. We could consider removing that and saying it's also valid. We should still add formatting tests for all the lists this impacts, and update the grammar if we go down this route.

**Comment by nguerrera** [comment]
I made example of all the places:

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=Ly8gUHJvcG9zYWwNCg0KLy8txAEgTk9UIE9LIHRvZGF5LCBtYWtlIHRoZW0gYWxsxBgtLS3GLiB0ZW1wbGF0ZSBwYXJhbWV0ZXJzDQptb2RlbCBGb288VDEsIFQyLD4ge33QMWFyZ3VtZW50yTBCYXIgZXh0ZW5kc8U8c3RyaW5nLCBpbnQzzkN1cGxlcw0KYWxpYXMgVCA9IFvHLF3HImhlcml0YWdlDQppbnRlcmZhY2UgQSB7fTsgzBJCxBLMEU%2FpAIBBLCBCLCB7fSAvLyBCYWQgZGlhZ25vc3RpYywgd2hpY2ggaXMgY3VyaW91c8R0I3N1cHByZXNzICJwcm9qZWN0aW9ucy1hcmUtZXhwZXJp5ADqYWwiDQrKHyDlAPcjeCB7DQogIHRvKHgsIHksKSB7xHXLJ%2BwBWiAgIMQeZnVuxhxjYWxsxhZmKDEsIDIsKTvkAI%2FHJ2xhbWJkYdFBKGEsIGIsKSA9PiB7IHJldHVybsVSxRgpOyDkARUgIH0NCugBcS0t6QINxxJvcGVyYfEAnm9wIGZvbyhhOiBib29sZWFuLCk6IOYBm%2BUAly8vIGRlY29yYXRvcuwCAEBkb2MoIntuYW1lfSIsIFQsKeoCFHo8VOQB%2Bw%3D%3D)

**Comment by nguerrera** [comment]
## Proposal 
* Allow trailing comma in all lists. (Make everything NOT OK [here](https://cadlplayground.z22.web.core.windows.net/?c=Ly8gUHJvcG9zYWwNCg0KLy8txAEgTk9UIE9LIHRvZGF5LCBtYWtlIHRoZW0gYWxsxBgtLS3GLiB0ZW1wbGF0ZSBwYXJhbWV0ZXJzDQptb2RlbCBGb288VDEsIFQyLD4ge33QMWFyZ3VtZW50yTBCYXIgZXh0ZW5kc8U8c3RyaW5nLCBpbnQzzkN1cGxlcw0KYWxpYXMgVCA9IFvHLF3HImhlcml0YWdlDQppbnRlcmZhY2UgQSB7fTsgzBJCxBLMEU%2FpAIBBLCBCLCB7fSAvLyBCYWQgZGlhZ25vc3RpYywgd2hpY2ggaXMgY3VyaW91c8R0I3N1cHByZXNzICJwcm9qZWN0aW9ucy1hcmUtZXhwZXJp5ADqYWwiDQrKHyDlAPcjeCB7DQogIHRvKHgsIHksKSB7xHXLJ%2BwBWiAgIMQeZnVuxhxjYWxsxhZmKDEsIDIsKTvkAI%2FHJ2xhbWJkYdFBKGEsIGIsKSA9PiB7IHJldHVybsVSxRgpOyDkARUgIH0NCugBcS0t6QINxxJvcGVyYfEAnm9wIGZvbyhhOiBib29sZWFuLCk6IOYBm%2BUAly8vIGRlY29yYXRvcuwCAEBkb2MoIntuYW1lfSIsIFQsKeoCFHo8VOQB%2Bw%3D%3D) OK.)
* Allow formatter to do whatever comes easiest and is most consistent with JS/TS prettier defaults
* Don't implement any formatter knobs yet. If that is desired, consider it as a separate, lower priority issue.

## Implementation issue notes:
* Delete trailingDelimiterIsValid, and behave as though it was always true.
* Add parser tests for all cases.
* Add formatter tests for all cases.
* Update language grammar

**Comment by nguerrera** [comment]
Approved on 8/3 design meeting. #809 tracks implementation.
