### ISSUE TITLE
Experience problems with collisions between namespaces

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#79]
Consider this:

```cadl
using A;
using B;

namespace A {
  model M {} // error here
}

namespace B {
  model M {} // and here
}

model Foo {
  m: M; 
}
```
```
C:\t\main.cadl:5:3 - error duplicate-symbol: Duplicate name: "M"
C:\t\main.cadl:9:3 - error duplicate-symbol: Duplicate name: "M"
```

This is misleading because M is not "duplicated" until you use both namespaces. It also means you can't have `using A` and `using B` together even when you never reference the colliding names or always fully qualify them.

Now look at morally equivalent C#, where I would argue the experience is much better. I think we should make things work this way.

``` C#
using A;
using B;

namespace A {
  class M {}
}

namespace B {
  class M {}
}

class Foo {
  M m; // error here
}
```
```
C:\t\Program.cs(13,3,13,4): error CS0104: 'M' is an ambiguous reference between 'A.M' and 'B.M'
```

**Comment by timotheeguerin** [comment]
Should probably just try to resolve the reference just in time, looking up at the current usings vs flattening everything
