### ISSUE TITLE
Add support for sidecar client definition for complex clients

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#799]
- [ ] Support using a sidecar file for more complex client definitions
  - See: https://teams.microsoft.com/l/message/19:16f8f1ed70d044139be153707bdaee0e@thread.skype/1658416290857?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1658416290857&teamName=Azure%20SDK&channelName=Cadl%20Engineering&createdTime=1658416290857  for details/example
  - This would allow separating client shape from the core spec, where this is desirable, by creating client-specific models and referencing types from the source doc
  - Should eventually have linting rules for things like unreferenced operations to help with maintenance
- Note that the sidecar provides no new functionality, it is just a convenience when we want to separate client-specific definitions and decorators from the rest of the spec
- [ ] Model a few data planes and revisit design

**Comment by markcowl** [comment]
related to #778

**Comment by markcowl** [comment]
estimate:

**Comment by allenjzhang** [comment]
#841 
We will close this issue once 841 is completed. And close private #1786 for DPG consumption.

**Comment by johanste** [comment]
Proposal: https://gist.github.com/johanste/26230aa2fc2612673c1e0289576656ee

**Comment by markcowl** [comment]
@johanste  Can you add documentation issues for the client sidecar implementation and then close this issue?

**Comment by markcowl** [comment]
Closing per [#2313](https://github.com/Azure/cadl-azure/issues/2313)
