### ISSUE TITLE
Templated "filter types" used in versioned namespaces create duplicate types

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#812]
While adding versioning to Azure.Core (https://github.com/Azure/cadl-azure/pull/1754), I encountered another strange issue with the projections created when adding a `versionedDependency` to the service namespace:

1. Define a model type (`Widget`) which has a property of another model type (`WidgetDetails`)
2. Define an operation which wraps `Widget` in `UpdateableProperties` as the operation body (`op oops(...UpdateableProperties<Widget>)`)
3. The OpenAPI emitters will now start complaining that there is a duplicate `WidgetDetails` type.

Check out this [playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0K0xt2ZXJzaW9uaW5nxCENCnVzaW5nIENhZGwuSHR0cDvNElJlc3TOElbJP8U%2BQMdPZWQoTGlicmFyecgicykNCm5hbWVzcGFjZSDHHSB7DQogIGVudW0gyCcgeyB2MSB9Ow0KfcVRc2VydmljZVRpdGxlKCJTxg4iKcxrRGVwZW5kZW5jedF1LnYxzXjHQMZ4bW9kZWwgV2lkZ2V0xhIgIEBrZXnHCnNlZ21lbnQoInfFInPEdcQZxE46IHN0cuYA9cQTZGV0YWlscz86x05ExhDFHuUAx85txx8ge%2BQA58QdQGF1dG9Sb3V0ZcQOaW50ZXJm5ACvUHJvamVjdHPpAJ5kb2MoIkdldHMgdGhlyHcgb2YgYSDmAKYu6ACmZ2V0KCnoAJDnAKfGBi8vIENvbeQA2yBvdXTFSW5leHQgbGluZSB0byBtYWtlxRZlcnJvciBnbyBhd2F5IcY9b29wcyguLi5VcGRhdGVhYmxlUHJvcGVydGllczzGbT7Od30NCn0%3D) to see for yourself.  Comment out either the `@versionedDependency` decorator or the `op oops` operation to see the error go away.

When I started debugging this, I found that the OpenAPI emitter ends up encountering two forms of `WidgetDetails`, one that has been projected and one that has not (judging from `projectionSource` and `projectionBase` only being set on one of the instance).

Thus, it seems that something about types like `UpdateableProperties<T>` (including `OptionalProperties<T>`, etc) causes the projector to let the original model type slip through the cracks.

**Comment by markcowl** [comment]
pri: 0

**Comment by timotheeguerin** [comment]
Minimal repro 
```
import "@cadl-lang/versioning";

using Cadl.Versioning;

@versioned(Library.Versions)
namespace Library {
  enum Versions {
    v1,
    v2,
  }
}

@serviceTitle("Service")
@versionedDependency(Library.Versions.v1)
namespace Service {
  model Widget {
    details?: WidgetDetails;
  }

  model WidgetDetails {}
  interface Projects {
    oops(...UpdateableProperties<Widget>): Widget;
  }
}

```
