### ISSUE TITLE
Compiler version mismatch in IDE

### ISSUE THREAD

**Issue by markweitzel** [microsoft/cadl#813]
I was working to setup the review session we did this morning but keep hitting the following error. I followed the recommendation to update the cadl-server setting, but this did not resolve the issue. This error essentially disables tooling support.

```
Current Cadl compiler conflicts with local version of @cadl-lang/compiler referenced in /Users/markweitzel/gitrepos/azure-rest-api-specs-pr/specification/cognitiveservices/data-plane/MetricsAdvisor/Adel/preview/2022-07-10-preview/cadl. 
If this error occurs on the command line, try running `cadl` with a working directory of /Users/markweitzel/gitrepos/azure-rest-api-specs-pr/specification/cognitiveservices/data-plane/MetricsAdvisor/Adel/preview/2022-07-10-preview/cadl. 
If this error occurs in the IDE, try configuring the `cadl-server` path to /Users/markweitzel/gitrepos/azure-rest-api-specs-pr/specification/cognitiveservices/data-plane/MetricsAdvisor/Adel/preview/2022-07-10-preview/cadl/node_modules/.bin/cadl-server.
  Expected: /Users/markweitzel/.nvm/versions/node/v16.14.0/lib/node_modules/@cadl-lang/compiler/dist/core/index.js
  Resolved: /Users/markweitzel/gitrepos/azure-rest-api-specs-pr/specification/cognitiveservices/data-plane/MetricsAdvisor/Adel/preview/2022-07-10-preview/cadl/node_modules/@cadl-lang/compiler/dist/core/index.jsCadl(compiler-version-mismatch)
```

cc: @nguerrera

**Comment by nguerrera** [comment]
I am OOF right now but will do my best to help without being set up to investigate deeply.

Do you have end-to-end repro steps? Can you share the settings.json you used?

I think one thing that is unfortunately missing from that error is that you will need to restart VS Code for the setting to be used. Or Ctrl + P, Restart Cadl server. Did you do that either of those?

One thing that will help here is #784 which would allow this to at least get downgraded to a warning and things would still work in the majority of cases. But we should still get to the bottom of why you cannot resolve this with the configuration.

**Comment by nguerrera** [comment]
https://github.com/microsoft/cadl/issues/657 also has some ideas for making the IDE smarter about this, but #784 is the much cheaper path forward IMHO.

**Comment by markcowl** [comment]
pri: 0, estimate: 1 (investigation)

**Comment by nguerrera** [comment]
Closing this with #784 now resolved, it will be a non-blocking warning. I am still interested in repro steps to see why the message triggered if you had configured the cadl-server path accordingly. If you can provide those, feel free to re-open.
