### ISSUE TITLE
Updateable properties versioning issue when in another namespace

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#823]
In this example when using 
- `UpdateableProperties<T>` inline it always include both properties 
- `ResourceUpdateModelProperties` when defined inside the service namespace. everything works great
- `ResourceUpdateModelProperties` when defined inside another namespace
   - if not-versioned, everything is always included
   - if versioned `@removed` property is never included, `@added` is always
```
import "@cadl-lang/rest";
import "@cadl-lang/versioning";

using Cadl.Versioning;
using Cadl.Http;
using Cadl.Rest;

@serviceTitle("ContosoProviderHubClient")
@doc("Contoso Resource Provider management API.")
@versioned(Versions)
@versionedDependency([[Versions.v1, Lib.Versions.l1], [Versions.v2, Lib.Versions.l1]])
namespace MyService {
  enum Versions {
    v1,
    v2,
  }

  @doc("Employee properties")
  model Foo {
    @doc("Profile of employee")
    @format("base64Url")
    @removed(Versions.v2)
    thisWasRemoved?: bytes;

    @doc("Profile of employee")
    @format("base64Url")
    @added(Versions.v2)
    thisWasAdded?: bytes;
  }

  // op test(): ResourceUpdateModelProperties<Foo>;
  op test(): Lib.ResourceUpdateModelProperties<Foo>;
  // op test(): UpdateableProperties<Foo>;
}

@versioned(Versions)
namespace Lib {
  enum Versions {
    l1,
  }

  @friendlyName("{name}Update", T)
  model ResourceUpdateModelProperties<T> is UpdateableProperties<T>;
}

```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0K0xt2ZXJzaW9uaW5nxCENCnVzaW5nIENhZGwuVskbO80YSHR0cM4SUmVzdMU%2BQHNlcnZpY2VUaXRsZSgiQ29udG9zb1Byb3ZpZGVySHViQ2xpZW50IikNCkBkb2PJIiBSZXNvdXJjZSDILCBtYW5hZ2VtZW50IEFQSS7FM%2BcArWVkKOcAnHPNFkRlcGVuZGVuY3koW1vIIi52MSwgTGli6ADPcy5sMV0sIMsgMtIgXSkNCm5hbWVzcGFjZSBNeVPmANcgew0KICBlbnVtIMguxhMgIHYxLMcJMsUJfeQBDyAg5gDmRW1wbG95ZWUgcHJvcGVydGllc%2BQA0CAgbW9kZWwgRm9vyEfGMFByb2ZpbGUgb2YgZcc7xjAgIEBmb3JtYXQoImJhc2U2NFVybMkacmVtb3brARwudjLHG3RoaXNXYXNSxiE%2FOiBieXRlc%2BUBst9133UgQGFkZNxzQcQfy3HpARkvLyBvcCB0ZXN0KCk66QH%2FVXBkYXRlTeQBFlDpASs8Rm9vPsU8yzLkAbLfNsg2zmvGLWFibGXSLOUAnPYCZuoCDkxpYvsCCGzmAgjoAf9mcmllbmRseU5hbWUoInvERn3mAIIiLCBU6wIE%2FgDMVD4gaXP2ALtU5wC5)

**Comment by markcowl** [comment]
Fixed
