### ISSUE TITLE
Document possible values for `@visibility` decorator

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#825]
In the Cadl tutorial, the example in the [visibility decorator](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#visibility-decorators) section shows "read" and "write" visibility values, but does not list the full set of possible values.

It would be great to document the full set of values, and define the less-standard values like "create" and "update".

Thanks!

**Comment by mikekistler** [comment]
Dup of #298
