### ISSUE TITLE
Documenting various union bugs

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#834]
I am cleaning up the union code and am documenting the various things I think are incorrect.

1. [Nullable doesn't work when there are multiple variants](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgWCB7DQogIHByb3A6IGludDMyIHwgc3RyaW5nIHwgbnVsbDsNCn0NCm9wIGZvbygpOiBYOw%3D%3D)
2. [Can't combine literals and models if the literal comes first](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgQyB7DQoNCn0NCsYQWMQQICBwcm9wOiAxIHwgQzsgLy8gbm90IG9rP8gbMjogQyB8IDHFHMUYfcRGb3AgZm9vKCk6IFg7)
3. [Can't use enums in unions, but I think it should be fine?](https://cadlplayground.z22.web.core.windows.net/?c=ZW51bSBBIHsNCiAgYTogMQ0KfQ0KDQrFF0LGF2I6IDLFF21vZGVsIFjGFnByb3A6IEEgfCBCxR1vcCBmb28oKTogWDs%3D)
4. [Can't use different literal types in a union, but could be expressed as a union of multiple enums](https://cadlplayground.z22.web.core.windows.net/?c=DQptb2RlbCBYIHsNCiAgcHJvcDogMSB8ICJzdHJpbmciDQp9DQpvcCBmb28oKTogWDs%3D) ([we do that already when a model is in the union](https://cadlplayground.z22.web.core.windows.net/?c=DQptb2RlbCBYIHsNCiAgcHJvcDogc3RyaW5nIHwgMSB8IDJ8ICLGESINCn0NCm9wIGZvbygpOiBYOw%3D%3D))

**Comment by timotheeguerin** [comment]
feels like a lot of leftover of the swagger 2.0 union code where those restrictions were justified

**Comment by bterlson** [comment]
Fixed via #837 .
