### ISSUE TITLE
Unpin node in CI/PR validation

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#835]
A while ago we pinned node 16.14.2 and 18.2.0.

See dee20cf44997cad2f68726c1d1faab7f36c83753 and 867cdf944ab3679c6a32a2c24d3c3c4123e689b5

Opening an issue to revert this when 16.latest and 18.latest work again. I tried in #833 but the issue persists in 16.latest and there's a new issue running playground tests in 18.latest.

**Comment by markcowl** [comment]
Pri: 1, estimate: ?
