### ISSUE TITLE
implement augment decorator (`@@`) for sidecar file support

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#841]
This is the implementation issue for the first part of: https://github.com/microsoft/cadl/issues/218
- Implement augment decorator `@@decorator(target, params)`  that allows sidecars to decorate any element in an existing spec.
- add mechanism for referencing operation parameters and operation return values

**Comment by markcowl** [comment]
pri: 1, estimate: 8

**Comment by tjprescott** [comment]
Where was this implemented? It is released?
