### ISSUE TITLE
Way to skip or specify to urlencode a parameter

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#851]
Currently autorest has this extension `x-ms-skip-url-encoding` which lets tells that the parameter shouldn't be url encoded. We are lacking this functionality

**Comment by markcowl** [comment]
pri: 0

**Comment by tjprescott** [comment]
I'd be happy to work on this but I can't assign myself.

**Comment by mikekistler** [comment]
I recently got some clarification on URL encoding from Darrel Miller:
> URLs should be encoded at the point of construction. That is the only time when you know which parts are data elements in the URL. If a URL has been fully constructed, it should be considered sufficiently encoded [ref [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.1)]

So I'm wondering when we would ever want to specify "x-ms-skip-url-encoding".

**Comment by timotheeguerin** [comment]
`/file/{filePath}` I think a path parameter like that you don't want `/` to be encoded no?

Or if the type is `uri` for the server variables. but for that one we can maybe auto guess

**Comment by timotheeguerin** [comment]
I mean in this case
```
@server("{host}/foo", {host: uri})
```

I do feel like this is something we need to support. For example github api to get files:
https://docs.github.com/en/rest/repos/contents

which is at `/repos/{owner}/{repo}/contents/{path}` and would be that `https://api.github.com/repos/octocat/Hello-World/contents/notes/hello.txt` for `notes/hello.txt` as the path.

**Comment by lmazuel** [comment]
@mikekistler example of case, scope in ARM is a url, like `/subscription/123-456-789/resourceGroup/rgname` and when you set a policy you do something like POST `/subscription/123-456-789/resourceGroup/rgname/policy`. The template will be defined as `{scope}/policy`. with scope tagged to NOT be encoded.

**Comment by timotheeguerin** [comment]
So wondering if the only case is really that we don't want to escape `/` but wouldn't we maybe still want to escape in between.
For example if the scope was `/subscription/123-456/rg with spaces/bar` (just supposing that was allowed)

Wondering if maybe what we want is a way to say that a path parameter is actually multiple:
```

@route("{*scope}/policy") // I think the way dotnet does it with a * prefix.
@route("{scope*}/policy") // With a * suffix
@route("{scope+}/policy") // With a + suffix
op test(@path scope: string);
```

**Comment by mikekistler** [comment]
@lmazuel My point is that if we know something is a URL then we _never_ want to encode it. It would be _wrong_ to encode it. So there is no need to specify "skip-url-encoding" on URLs.

**Comment by lmazuel** [comment]
@mikekistler the parameter is not a full url by itself, it's a part of the final url.

**Comment by mikekistler** [comment]
For parameters that are part of a URL, the opposite should hold -- these should _always_ be encoded. It would be wrong _not_ to encode it. Do we impose this on the user rather than doing it ourselves?

**Comment by lmazuel** [comment]
As I explained in https://github.com/microsoft/cadl/issues/851#issuecomment-1218434233, there are situation where a path value must not be encoded, for instance ARM scopes are URL based and part of the url. For instance, `subscriptions/ae640e6b-ba3e-4256-9d62-2993eecfa6f2` is a valid ARM scope, and it has to be passed part of the url. If we encode the `/`, the url is now invalid:
```
https://mgmt.azure.com/subscriptions%2Fae640e6b-ba3e-4256-9d62-2993eecfa6f2/providers/Microsoft.Authorization/policyAssignments
```
For this scenario, the Swagger template is defined as:
```
"/{scope}/providers/Microsoft.Authorization/policyAssignments/{policyAssignmentName}"
```

**Comment by timotheeguerin** [comment]
@lmazuel agree about that use case, would there be any other or that only cases we should care about are:
| Case | Action|
|-|-|
| path parameter is of `uri` type and is used in `@server` | keep|
| path parameter might contains(`/`) | keep but we need a way to specify that exact case |
| otherwise |  **encode**|

**Comment by lmazuel** [comment]
@timotheeguerin LGTM!

**Comment by timotheeguerin** [comment]
So I think question here is how can we design the 2nd case. Where those are some options:

> 
> @route("{*scope}/policy") // I think the way dotnet does it with a * prefix.
> @route("{scope*}/policy") // With a * suffix
> @route("{scope+}/policy") // With a + suffix
> op test(@path scope: string);
> ```

**Comment by markcowl** [comment]
ready to discuss

**Comment by timotheeguerin** [comment]
## Proposal

Path parameters are always url encoded except: 
- the path parameter type is `uri` and is used in `@server` value.
  - if path parameter is `uri` in an operation it gets encoded 
- A path parameter is marked as having multiple segments(multiple `/`)
  - In this case it wouldn't actually skip encoding completely, it would only need to skip encoding of `/` 

## How to mark a path parameter as having multiple segments(multiple `/`)

### Option 1: Have a convention in the `@route` path 

```cadl
@route("{*scope}/policy") // I think the way dotnet does it with a * prefix.
@route("{scope*}/policy") // With a * suffix
@route("{scope+}/policy") // With a + suffix
op test(@path scope: string): void;
```

Pros: 
- Similar to a lot of web api framework

Cons:
- Cannot reuse the parameter with this config. (But maybe that's better that way)

### Option 2  Add a flag on `@path` decorator

```cadl
@route("{scope}/policy") // With a + suffix
op test(@path({multi: true}) scope: string): void;
```

Pros: 
- Easier to reuse the parameter. When using this param wherever it will always skip encoding of `/`

Cons:
- ?

**Comment by mikekistler** [comment]
Path parameters that may contain unencoded "/" are strongly discouraged as they make the REST API definition ambiguous. If we support this then we also need a linter message that flags these.

**Comment by markcowl** [comment]
@route("{scope+}/policy")
or
@autoRoute
op myOp(@path scope: string[], @path name: string) : void;

"/subscription/mysub/rg/my rg/<type>/"

op myOp(@path({skipEncoding: true}) scope: string, @path name: string): void;

/foo/"foo bar"

- investigate how this impacts autoroute
- separate skipEncoding setting?
- scenarios

**Comment by markcowl** [comment]
@mikekistler Yes, in OpenAPI path segments must not contain unencoded path separators.

However, in Azure APIs, there is a common pattern, originating in ARM but also used in data planes of entities that 'extend' other entities.  This results in paths of variable length for the same operation, like:

`/{extended-entity-identifier}/{extending-entity-type}/{extending-entity-name}`

Since `{extended-entity-identifier}` is unknown, could contain any number of segments, and does not actually change the operations over the extending resource, it makes sense to describe these as operations under a single path, rather than enumerating all of the possible paths and repeating the operations.

Personally I am favoring something like a `UriPath` type.  This would allow clients to decide whether to accept an 'already encoded' path variable, or to accept an array of path segments or the like.  Languages with Uri types might decide to use those Uri types. This also means we can maintain the current mechanisms we use to represent these operations in OpenAPI.We should propose how to represent them in OpenAPI3 as well.

**Comment by markcowl** [comment]
## Revised Proposal
- Add a `@urlPath` decorator and `isurlPath(Type): boolean` accessor to cadl/http
- Add a 'urlPath' type in cadl/http (or core)

```cadl
@urlPath
model UrlPath is string;
```
- This would be used for parameters that represent path segments that may contain a '/' and should not be url encoded.
- Sample usage: extension resources

```cadl
// extensionUri is a multi-segment path to the resource the extension applies to
// 'name' is the name of the FooExtension resource
@route("{extensionUri}/fooextension/{name}")
op getFooExtension(@path extensionUri: urlPath, @path name: string): Foo | Error;
```

### Representation in cadl-autorest

While it is technically invalid, this pattern is common in autorest-inflected swagger.  A urlPath parameter should eb marked with the 'x-ms-skip-url-encoding' extension:

```json
"paths": {
  "{extensionUri}/fooextension/{name}": {
    "get": {
      "parameters":[
        {
          "x-ms-skip-url-encoding": true,
          "name": "extensionUri",
          "in": "path",
          "required": true
           
        },
      ]
    }
  }
}
```

### Respresentation in OpenAPI3
- It seems that we should add this extension to OpenAPI3, as in cases ike this, there are no real alternatives.  We might consider a more descriptive extension name, like `x-ms-multi-segment-path` or `x-ms-url-path`

### Alternative implementation
- We could represent this type in cadl-azure-core and use the OpenAPI extension to add the extension:
```cadl
@extension("x-ms-skip-url-encoding", true)
model urlPath is string;
```

### Representation in OpenApi3
## Questions
- Are there other situations in which we do not want to urlEncode a parameter (pre-encoded path segments?)
- Should we generalize this type to `urlComponent`? this way it could represent any portion of an url that should not be url encoded (for example, authority)
- We could simply use the 'uri' type in this case, but it seems incorrect/confusing, as a uri must be a full uri, starting with schema

**Comment by markcowl** [comment]
## Notes from Design Meeting
- Consensus was that a type was preferrable to decorator parameters
- Consider augmenting Uri type to include different kinds of Uris, or whether types for Uri  parts are necessary
- In the context of a type-based solution, consider necessary mechanisms for overriding default encoding behavior

**Comment by markcowl** [comment]
## Revised Proposal

- Per [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-4.1) model a type similar to *relative-reference* that represents fully-encoded url paths in cadl/http.

``` cadl
@format("uri")
model urlPath is string;
```

### Relative and absolute paths
- The spec describes 3 types of relativee-references:
  - Absolute pahts, starting with '/'
  - Relative paths, not starting with '/'
  - Network paths (disused), starting with '//'

The proposal is to use a single type to represent the common absolute and relative paths, as this provides all necessary information about encoding.  An alternate ide might be to provide individual types for relative and absolute paths, but this would largely be for documentary purposes, as we would expect any processor to correctly handle leading and trailing slashes.

This would represent relative and absolute url paths, consistent with the *relative-reference* concept, producing the following default behavior

| Case                                                 | Code                                           | Behavior                          |
| ---------------------------------------------------- | ---------------------------------------------- | --------------------------------- |
| 1. string in path                               | `op simple(@path foo: string)`                 | Encode foo                        |
| 2. urlPath in path                                        | `op simple(@path foo: urlPath)`                    | Don't encode reserved characters                        |
| 3. uri in path           | `op simple(@path foo: uri)` | encode reserved characters              |
| 4. string in query  | `op simple(@path foo: string)`                 | Encode foo                        |
| 5. urlPath in query  | `op simple(@path foo: urlPath)`                    | Don't encode reserved characters                        |
| 6. uri in query  | `op simple(@path foo: uri)` | Don't encode reserved characters*              |
| 7. Path Param is an array of string                       | `op simple(@path foos: string[])`              | Encode each foo and join with `/`.

* for backward compatibility with older processors, it may be desirable to encode '/' and '?' in query parameters

Note that here, we are discounting use of the 'network-path' option for relative-path (paths starting with `//`), as the spec indicates that this is a disused pattern, and we have never seen it.  However, we could add a networkPath type in the future, if needed.

**Comment by markcowl** [comment]
proposal:

verify no discrepancies with the new spec
- uri -> url
- pathUrl -> relativeUrl
