### ISSUE TITLE
getAllRoutes doesn't work with projetions if there is no service namespaces

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#855]
It should go lookup for the current projector. This isn't an issue for versioning as using versioning requires you to have a service namespace but for other projection like `projectedName` this is confusing.

**Comment by markcowl** [comment]
- makes sense to check for other decorators that might run into this issue

**Comment by markcowl** [comment]
est: 1, pri: (same as projectedName)

**Comment by timotheeguerin** [comment]
This was resolved in #861, where decorators don't need to be aware of this

**Comment by timotheeguerin** [comment]
Doesn't seem to be an issue due to how the accessor are called now but still is a problem that could occur. Cleanup in #950 all uses.
