### ISSUE TITLE
Feature Request: Make doc strings a different color

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#856]
At the most recent ARB review, there was a request to make the doc strings a different color from regular strings. The rationale is that most IDEs style docstrings differently so as to be more visually identifiable, and Cadl does not.

**Comment by markcowl** [comment]
pri: 2, est: 5

**Comment by tjprescott** [comment]
@markcowl if this has a pri and est, does it still need triage?

**Comment by markcowl** [comment]
@tjprescott we leave that label on until it is added to the project.

**Comment by nguerrera** [comment]
We should discuss the proposal linked on #927 before we do this IMHO.

**Comment by nguerrera** [comment]
We are going to move forward with the direction in the proposal on #927 so there is no need to do this. Doc comment style will be supported and provide the nice separation and coloring that's wanted here.
