### ISSUE TITLE
versionedDependency decorator is confusing

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#857]
Feedback from the most recent ARB review was that the `@versionedDependency` decorator was confusing. 

```cadl
@versionedDependency([[Versions.A, Azure.Core.Versions.v1_0_Preview_1]])
```

This was interpreted as the spec depending on itself. Additionally, what if a spec depends on specific versions of other libraries? Does it need to look like this?

```cadl
@versionedDependency([[Version.A, Azure.Core.Versions.v1_0_Preview_1], [Version.A, Azure.Foo.Versions.v1_0_Preview_1]])```
```

A possible alternative would be to use a dictionary with the key as the spec version and an array of dependencies. 
```cadl
@versionedDependency({
  Version.A: [
    Azure.Core.Versions.v1_0_Preview_1,
    Azure.Foo.Versions.v_1_0_Preview_1
  ],
  ...
})
```

**Comment by markcowl** [comment]
The design is that, if there were multiple library dependencies, there would be multiple decorators.  I think the proposal is logical, though.

**Comment by tjprescott** [comment]
I think folks were confused by the tuple which looks like an array so they assumed it was an array that happened to have two things in it. Dictionary was suggested because it's a little clearer at a glance that the spec version as a key is special and separate from everything else, which are the actual dependencies. With a tuple, it looks like both things are the same (dependencies)

**Comment by timotheeguerin** [comment]
yeah the tuple was the only way we could do with enums for versions. I originally was thinking of something similar to what you have but we can't have enum member as model keys.(at least for now)

**Comment by markcowl** [comment]
pri: 2

**Comment by timotheeguerin** [comment]
Alternate syntax we could do right now: Make the version mapping to be in a nested tuple instead of flattened with the key.

```
@versionedDependency([
  [Version.A, [
      Azure.Core.Versions.v1_0_Preview_1,
      Azure.Foo.Versions.v_1_0_Preview_1
    ],
  ],
  [Version.B, [
      Azure.Core.Versions.v1_0_Preview_1,
      Azure.Foo.Versions.v_1_0_Preview_1
    ],
  ],
])
```

**Comment by tjprescott** [comment]
I almost feel like a nested tuple would be worse... is the enum as key limitation Cadl or TS?

**Comment by timotheeguerin** [comment]
Cadl, object can only have string keys(well `identifier` or `StringLiteral`)

**Comment by timotheeguerin** [comment]
In TS you can do that this way, it would probably look similar if we allowed it 
![image](https://user-images.githubusercontent.com/1031227/184986371-a29f8bfe-082f-4c2c-85f0-6ccaaefea9a7.png)

**Comment by tjprescott** [comment]
I'm curious why `Foo.a` would need to be in brackets?  Why not just:
```
const a = {
   Foo.a: [Foo.a, Foo.a],
};
```

**Comment by timotheeguerin** [comment]
meaning that you want to get a reference here and exactly `Foo.a` is not the key.

```
alias MyStr = "my-key";

model Foo {
  MyStr: int32;   // Here that means the property is actually `"MyStr"`
  [MyStr]: int32; // Here means the property will be `"my-key"`
}
```

same concept in TS.

**Comment by tjprescott** [comment]
Weird, but okay :)

**Comment by markcowl** [comment]
would https://github.com/microsoft/cadl/issues/898 allow us to use a model type in `@versionedDependency` with quoted values as property keys for the versions?

**Comment by timotheeguerin** [comment]
This would need something seperate from #898. It would need:
- A way to define a key from a value
- Deciding that we are fine having `EnumMember` as a potential key for all model types.

**Comment by markcowl** [comment]
What would prevent us from using a syntax ike this:

``` cadl
enum Versions { `2022-01-01-preview`, `2022-05-01`}
@version(Versions)
@versionedDependency({
    `2022-01-02-preview`: [Azure.Core.Versions.V1, Azure.Foo.Versions.V2];
    `2022-05-01`: [Azure.Core.Versions.v1, Azure.Foo.Versions.V3]
})
```

This would require the decorator to special case matching  the keys in this type with the enum values in the version for the namespace.

**Comment by markcowl** [comment]
## Proposal 1
Allow the `VersionedDependency` decorator to take either the current tuples, or a model.  The model would have keys corresponding to the version property names of the version enumeration.

```cadl
@versionedDependency(
  {
    `2022-01-01-preview`: [Dependency1.Versions.v1, Dependency2.Versions.v2];
    `2022-05-01-preview`: [Dependency1.Versions.v1, Dependency2.Versions.v2];
    `2022-09-01`: [Dependency1.v2, Dependency2.v3];
  }
)
@versioned(MyService.Versions)
namespace MyService;
model Versions { `2022-02-01-preview`, `2022-05-01-preview`, `2022-09-01`}
```
-  Pros: 
  - Potentially Non-breaking
  - Intuitive to write and review
  - Simple implementation
- Cons: 
  - Only works if the enum is a string enum, or uses key/value pairs (we can handle exception cases with the current tuple)
  - Might be difficult tooling experience, with no intellisense over the dependency model keys

## Proposal 2

Change the `versionedDependency` decorator to apply to enum members, so that dependencies decorate the version enumeration.

``` cadl
@versioned(MyService.Versions)
namespace MyService;
enum Versions {
  @versionedDependency([Dependency1.Versions.v1, Dependency2.Versions.v2])
  `2022-02-01-preview`, 
  @versionedDependency([Dependency1.Versions.v1, Dependency2.Versions.v2])
  `2022-05-01-preview`, 
  @versionedDependency([Dependency1.Versions.v2, Dependency2.Versions.v3])
  `2022-09-01`
}
```

- Pros:
  - Intuitive, but requiring more decorators
  - Implement without major language changes
- Cons:
  - Wordy
  - Big breaking change

## Proposal 3
Add a Version template to the versioning library that includes version dependencies and string value, Represent Versions as a tuple of versions

```cadl
namespace Cadl.Versioning

@version
model Version<TValue extends string | float32 , TDependencyVersions extends Array<ModelProperty> = []> {
  value: TValue;
  dependencies: TDependencyVersions;
}



@versioned(MyService.Versions)
namespace MyService;
model Versions { 
  `2022-02-01-preview`: Version<"2022-02-01-preview">;
, `2022-05-01-preview`: Version<"2022-05-01-preview", [Dependency1.Versions.v1, Dependency2.Versions.v2]>, 
  `2022-09-01`: Version<"2022-09-01", [Dependency1.Versions.v1, Dependency2.Versions.v2]>
}
```
- Pros: 
  - Good  tooling experience
  - Much validation done by type checking
- Cons
  - Big Breaking Change
  - Wordy

## Proposal 4

Add a new mechanism to use a model property reference as the key to a model property (for example, square brackets).

```cadl
@versionedDependency(
  {
    [Versions.`2022-01-01-preview`]: [Dependency1.Versions.v1, Dependency2.Versions.v2];
    [Versions.`2022-05-01-preview`]: [Dependency1.Versions.v1, Dependency2.Versions.v2];
    [Versions.`2022-09-01`]: [Dependency1.v2, Dependency2.v3];
  }
)
@versioned(MyService.Versions)
namespace MyService;
model Versions { `2022-02-01-preview`, `2022-05-01-preview`, `2022-09-01`}
```

Pros
- Intuitive
- Good intellisense tooling
- Potentially non-breaking (versioned dependency could accept a tuple or model)
Cons
- Big language change: Allow enum reference as model property key

**Comment by timotheeguerin** [comment]
Like option 2 with a few changes:
1. Rename decorator to `useDependency` or `useDependencies`
2. Don't take an array of version but rest parms(remove the need for `[ ]`. `@useDependency(Dependency1.Versions.v1, Dependency2.Versions.v2)` instead of `@useDependency([Dependency1.Versions.v1, Dependency2.Versions.v2])`

```cadl
@versioned(MyService.Versions)
namespace MyService;
enum Versions {
  @useDependency(Dependency1.Versions.v1, Dependency2.Versions.v2)
  `2022-02-01-preview`, 
  @useDependency(Dependency1.Versions.v1, Dependency2.Versions.v2)
  `2022-05-01-preview`, 
  @useDependency(Dependency1.Versions.v2, Dependency2.Versions.v3)
  `2022-09-01`
}
```

**Comment by markcowl** [comment]
@timotheeguerin I think number 2 in your comments refers to proposal 3, and #3 refers to proposal 4, is that correct?

**Comment by timotheeguerin** [comment]
ah yes, auto formatting reordered the numbers :)

**Comment by tjprescott** [comment]
It seems a little weird to me that useDependency (singular) takes a list. Why not `@useDependencies`?

**Comment by timotheeguerin** [comment]
It doesn't necessary take a list you could have `@useDependency(Azure.Core.Version.v1)` or  `@useDependency(Azure.Core.Versions.v1, Azure.Arm.Versions.v1)` but yeah suggested either as option

**Comment by tjprescott** [comment]
> It doesn't necessary take a list you could have @useDependency(Azure.Core.Version.v1) or @useDependency(Azure.Core.Versions.v1, Azure.Arm.Versions.v1) but yeah suggested either as option

I mean, we could always make it take a list. What I wouldn't want to see is this:

```
@useDependency(foo)
@useDependency(bar)
@useDependency(baz)
`2022-09-09`
```

**Comment by markcowl** [comment]
Implementation issue #1356
