### ISSUE TITLE
Docs request: Cadl -> OpenAPI

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#858]
At the most recent ARB review, there was discussion about the desire to see what CADL concepts "translate to" in OpenAPI. We have some documentation on how to translate OpenAPI to Cadl, but there's nothing (to my knowledge) that generally describes how the emitters translate Cadl concepts.

Maybe this is something we plan on doing anyhow, but it seems like `cadl compile . --watch` may be sufficient here since you can set up whatever you want the default emitter to be.

For small things and learning though, it might be nice to simply add the emitters to aka.ms/trycadl on top of the existing OpenAPI and SwaggerUI options.

**Comment by markcowl** [comment]
est: 8, pri: 1

**Comment by markcowl** [comment]
- use this for tracking automated updates for the existing doc
- high-level explanatory doc

**Comment by mikekistler** [comment]
I think we should use the outline proposed in azure/cadl-azure#992 to build out the documentation for the cadl-autorest emitter. We can probably reuse some content from the website doc of the openapi3 emitter.

**Comment by mikekistler** [comment]
Completed by microsoft/cadl#978, microsoft/cadl#1352, microsoft/cadl#1365
