### ISSUE TITLE
Outline view does not reflect namespaces correctly

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#865]
Here's an example of the outline view for the dataplane/language/authoring cadl spec:

![image](https://user-images.githubusercontent.com/5723682/184681494-0c8f3abd-61b7-4b89-aed0-78c2dde8af97.png)

It looks like:
```
Authoring
  |-> Endpoint
Azure
Langauge
Endpoint
Project
ProjectKindValues
...
```

What I would expect is something like:
```
Azure
 |-> Language
   |-> Authoring 
     |-> Endpoint
     |-> Project
     |-> ProjectKindValues
     ...
```

**Comment by timotheeguerin** [comment]
I think we should also try to collapse the namespace if they are empty like csharp does

![image](https://user-images.githubusercontent.com/1031227/184684760-c263e116-53fd-4239-b891-9e67d0925bc2.png)

**Comment by markcowl** [comment]
pri: 0, est: 5
