### ISSUE TITLE
Allow syntax to allow reserved keywords as operation names

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#869]
From the Language AnalyzeText Authoring Cadl:

```cadl
  // NOTE: `import` is a reserved keyword
  @doc("Triggers a job to export a project's data.")
  importx is ResourceAction<
    Project,
    ExportedProject,
    Cadl.Http.AcceptedResponse & Foundations.LongRunningStatusLocation
  >;
```

In Swift, you can create symbol names using reserved keywords by quoting them with backtick. Consider allowing this:

```
`import` is ResourceAction<Project, ExportedProject, AcceptedResponse & LongRunningStatusLocation
```

Alternatively, if one could apply the `@friendlyName` decorator to an operation, that may be a simpler solution to the problem (though currently the decorator cannot be used on operations).

**Comment by timotheeguerin** [comment]
I think we talked at some point of just allowing 
```
op "namespace"(): void;
```

**Comment by daviwil** [comment]
Yep, using string literals as names to avoid reserved keywords is a good solution.

**Comment by timotheeguerin** [comment]
though that now also introduce the high chance that the name is not valid in other languages.

**Comment by daviwil** [comment]
Good point.

**Comment by markcowl** [comment]
pri: 1

**Comment by tjprescott** [comment]
Also, it seems simply changing `import` to `Import` is accepted.

**Comment by markcowl** [comment]
ready to discuss

**Comment by timotheeguerin** [comment]
@nguerrera would `distinct syntax for escaping identifiers` mean that we would only allow escaping keywords

```ts
// Example escape with `
op `namespace();

// That doesn't work
op `foo-bar();
```

We already have that for model properties too so have to be careful for consistency

```
model Foo {
  "foo-bar": string;
}
```

**Comment by nguerrera** [comment]
No, it doesn't have to be just keywords.

It could be:

```
op `this is actually identifier`(): void;
```

I would want to remove the `""` option from model properties in that case, but we could keep it for backcompat. I personally find the handling annoying of model properties and don't want that annoyance to spread all over the place.

**Comment by timotheeguerin** [comment]
make sense

**Comment by timotheeguerin** [comment]
Summary of options:

## Option 1: Allow string literals everywhere identifier are allowed
```cadl
op "foo-bar"(): void;
interface "Foo-Bar" {}
```

Pros: 
- Feels quite intuitive
- Similar to TS

Cons:
- Handling of identifier means always having to handle `Identifier | StringLiteral` in the syntax tree.

## Option 2: New escape syntax for identifier `` ` ``
```cadl
op `foo-bar`(): void;
interface `Foo-Bar` {}
```

Pros: 
-  Identifier stays their own syntax node. No need to handle string literal + identifier

Cons:
- Feels maybe a bit confusing on when to use vs `"` 
- Differ from typescript

## Option 3: Use double quote syntax but the parser automatically convert to identifier

```cadl
op "foo-bar"(): void;
interface "Foo-Bar" {}
```

Pros: 
- Identifier stays their own syntax node. No need to handle string literal + identifier
- TS like

Cons:
- Could maybe give a worse error recovery?

**Comment by tjprescott** [comment]
I don't think Option 2 makes sense. I suggested the backtick because that's what is familiar to me from Swift. It should really be Option 1 or 3 and of the two, Option 1 makes the most sense to me.

**Comment by nguerrera** [comment]
I wouldn't say option 2 doesn't make sense. It's a perfectly reasonable option to have a unique syntax for escaped identifier and string literal. IMHO, it is the cleanest option and I think Swift got this right. We borrowed `"""..."""` from Swift so maybe we can borrow ` `...` ` too?

There are other examples of this pattern. Common Lisp uses `|...|`:

```
[1]> (defun |add two numbers| (a b) (+ a b))
|add two numbers|

[2]> (|add two numbers| 4 5)
9

[3]> (defun "add two numbers" (a b) (+ a b))
*** - DEFUN: the name of a function must be a symbol, not "add two numbers"
```

But if we insist on using string literal syntax, then I prefer option 3 to option 1. But option 3 isn't as clean as option 1 in my opinion.

**Comment by nguerrera** [comment]
If I could make a breaking change here, I'd go with backticks for escaped identifier and not allow string literals as model property names.

**Comment by nguerrera** [comment]
It's cleaner because you can handle it entirely during scanning.

**Comment by tjprescott** [comment]
I have a selfish reason to dislike Option 3. Right now it's very easy for me to know how to render an identifier for APIView. If everything just showed up as Identifier due to some internal magic, I would need to check if the identifier was a reserved keyword to know whether to quote it. It would also result in issues where, say someone used a string identifier for giggled (i.e. not a reserved keyword) then APIView would not quote it. 

If you do the magic of Option 3, perhaps just a flag on Identifier to indicate it is a literal? I dunno. I would also be fine with the Swift backticks if you are fine with the non-TS-ness of it :D

**Comment by nguerrera** [comment]
We could give you a helper to print the identifier. I think it would be fine if printing removed `` if they are unnecessary. This is what I would expect the formatter to do too.

**Comment by timotheeguerin** [comment]
We already have that logic in the formatter for the model properties to remove quotes if not needed. We can definitely expose it

**Comment by markcowl** [comment]
surround by pipes |identifier|
start with ':'  :identifier
- for option 3, will need an indicator for quoted identifier in syntax representation
- references?

"foo bar".baz
- `foo bar`.baz
:foo bar.baz

other solution

- @friendlyName("import")
op importx(): Foo;

- totally punt

import
model
interface


enum Versions {
  `2022-01-01`,
  `2022-01-01`,
}
Versions.`2022-01-01`


- Conclusion: use backticks

**Comment by timotheeguerin** [comment]
^ Use backtick conditional on string interpolation solution not conflicting #932

**Comment by markcowl** [comment]
Implementation issue here: https://github.com/microsoft/cadl/issues/1221
