### ISSUE TITLE
Outline view does not work on VSCode for Mac

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#872]
Steps I took:
1. uninstalled existing VSCode extension
2. `cadl code install` to get 0.15.2 
3. set the cadl-server location to match my global compiler installation
4. Opened a cadl file that works fine on Windows
5. Outline view says "No Symbols Found"

**Comment by tjprescott** [comment]
Here's what worked for me to solve this:
1. pull the latest from `main`
2. `rush update`
3. `rush dogfood`
4. Restart CADL server

Thanks @timotheeguerin for the assistance! Closing.

**Comment by timotheeguerin** [comment]
The problem was just that the outline hasn't been released yet so can't be consumed via `cadl code install` yet.
