### ISSUE TITLE
September release notes

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#874]
Starting issue to track September release notes.

**Comment by nguerrera** [comment]
# `Type` suffix removed from most `Type`s

The following types have been renamed in the compiler API:

* `ModelType` -> `Model`
* `ModelTypeProperty` -> `ModelProperty`
* `InterfaceType` -> `Interface`
* `EnumType` -> `Enum`
* `EnumMemberType` -> `EnumMember`
* `TemplateParameterType` -> `TemplateParameter`
* `NamespaceType` -> `Namespace`
* `OperationType` -> `Operation`
* `StringLiteralType` -> `StringLiteral`
* `NumericLiteralType` -> `NumericLiteral`
* `BooleanLiteralType` -> `BooleanLiteral`
* `TupleType` -> `Tuple`
* `UnionType` -> `Union`
* `UnionTypeVariant` -> `UnionVariant`
* `ProjectionType` -> `Projection`

Update uses of the type names on the left with the type names on the right. The old names can still be used but they are deprecated and may be removed from a future release.

**Comment by timotheeguerin** [comment]
# Rename `Page` to `CollectionWithNextLink`

In library `@cadl-lang/rest` in `Cadl.Rest.Resources` namespace the `Page` model was renamed to `CollectionWithNextLink`.

Before
```cadl
op test(): Page<MyResource>;
```

**Comment by timotheeguerin** [comment]
## [Cadl] [Api] **Deprecation**: `@consumes` `@produces` 

The following are deprecated and will be removed in next release.
- `@consumes`
- `@produces` 
- `getConsumes`
- `getProduces`

**Comment by nguerrera** [comment]
Probably worth noting that consumes and produces already did nothing in any standard emitter.
