### ISSUE TITLE
Deprecate the `@serviceVersion` decorator

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#879]
At today's review (8/16) Ted pointed out the difference between a versioned spec and non-versioned spec could be confusing to newcomers and suggested unifying the experience or at least naming the decorators such that they appear next to eachother in intellisense.

**Non-versioned Spec**
```
@serviceTitle("Microsoft Cognitive Language Service - Analyze Text Authoring")
@serviceVersion("2022-05-15-preview")
@versionedDependency(Azure.Core.Versions.v1_0_Preview_1)
namespace Azure.Language.Authoring;
```

**Versioned Spec**
```
@serviceTitle("Microsoft Cognitive Language Text Analytics")
@versioned(Versions)
@versionedDependency([[Versions.v2022_05_15_preview, Azure.Core.Versions.v1_0_Preview_1]])
namespace Azure.Language.TextAnalytics;
```

**Comment by daviwil** [comment]
The `serviceVersion` decorator needs to go away now that we have `versioned`.

**Comment by nguerrera** [comment]
We discussed replacing `@serviceXxx(yyy)` with service({Xxx: yyy})`.

**Comment by nguerrera** [comment]
But if this going away altogether we can do that independently.

**Comment by nguerrera** [comment]
Does it make sense to need to import the versioning library just to have a single version in your output?

**Comment by bterlson** [comment]
I'm not convinced about this. Versioning is an advanced scenario, we shouldn't make that the default experience IMO. Version is a field that exists in openapi so I also think we need something to directly set that even if it lives in the openapi package rather than core.

**Comment by timotheeguerin** [comment]
That was my point and why we should have a design meeting about this. 

It is definitely confusing right now that you have both. Maybe the solution is to disallow using `@serviceVersion` if you are using `@versioned`. And maybe the projection on the namespace would run `@serviceVersion` using the projected version

**Comment by nguerrera** [comment]
Nice, I like that proposal.

**Comment by timotheeguerin** [comment]
Will close this issue in favor of design https://github.com/microsoft/cadl/issues/982
