### ISSUE TITLE
Add linting rule in azure-core to prevent `@format` decorator

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#881]
During the review on 8/16, the architects expressed a desire to see the `@format` decorator go away. Their rationale was that types should be standardized into first-class types (or user defined ones) such that it is not necessary. If we need to keep it, the ask was to use every tool in our arsenal to dissuade service teams from using it (linter rule, deeper namespace, etc.)

**Comment by timotheeguerin** [comment]
I totally agree that you shouldn't use `@format` if there is already a built-in type doing that for you. But I think the idea (like openapi format) was it was open ended wich means that there could be some formats that we don't provide but another library could make use of.
I think the better solution is to indeed have a linter for azure service to now use format.

**Comment by daviwil** [comment]
Yep, we need this decorator but we can definitely add a linting rule in places where it should not normally be used.

**Comment by markcowl** [comment]
pri: 1
est: 3
