### ISSUE TITLE
intersection syntax (&) is confusing to non-TS developers

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#882]
During the review on 8/16, the non-TS architects expressed dissatisfaction with some of the syntax inherited from TS:

```
  @doc("Triggers a job to export a project's data.")
  export is ResourceAction<
    Cadl.Http.AcceptedResponse & Foundations.LongRunningStatusLocation
  >;
```

There is this brief section in the documentation on intersections (https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#intersections)

One suggestion some though might be more intuitive to non-TS developers would be `+`

```
  @doc("Triggers a job to export a project's data.")
  export is ResourceAction<
    Cadl.Http.AcceptedResponse + Foundations.LongRunningStatusLocation
  >;
```

**Comment by daviwil** [comment]
Ampersand implies "and" more than "+" does, IMO.  I understand that some people don't get the syntax when they first look at it, but this is to be expected when learning any language.  I think the Intersections section of the tutorial could be worded better to make things more clear.

**Comment by timotheeguerin** [comment]
Yeah I think also with the fact that we have `|` for union feels way more intuitive.
- `|`   -> or
- `&` -> and

**Comment by nguerrera** [comment]
We try not to deviate from TypeScript too much when we have parallel concepts and this would be a big breaking change for limited value.
