### ISSUE TITLE
Visual Studio extension various problems

### ISSUE THREAD

**Issue by sebastianrex** [microsoft/cadl#889]
I've found a few issues with the VS extension. Two of them are easy fixes I think, but I've never done VS extension development and I'm not sure what testing is required, so I'm hesitant to contribute a PR, and am hoping someone already set up can just make them quickly.

First, the README.md is wrong. At https://github.com/microsoft/cadl/blob/b162c3ca5b32e984d358fadf01cc8f63b2ab4a78/packages/cadl-vs/README.md, it says to use the configuration:

```json
{
  "cadl.cadl-server-path": "./mynestedproject/node_modules/@cadl-lang/compiler"
}
```

But that's wrong, it's `cadl.cadl-server.path`, not `-path`

Second, there's an issue here: https://github.com/microsoft/cadl/blob/main/packages/cadl-vs/src/VSExtension.cs#L87

If you hit this line (which happens if you hit https://github.com/microsoft/cadl/blob/main/packages/cadl-vs/src/VSExtension.cs#L225), then it fails:

```
Task Failed - Activating language client Cadl: Failed to activate Cadl language server!
File issue at https://github.com/microsoft/cadl

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Cadl.VisualStudio.LanguageClient.<ActivateAsync>d__20.MoveNext() in D:\a\1\s\packages\cadl-vs\src\VSExtension.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<TrackTaskAsync>d__118.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__127.MoveNext()
```

I'm pretty sure the fix is just to make that line:

```
info.Environment[entry.Key] = entry.Value;
```

because `entry` is already an entry in `env`.

Third, it doesn't seem to work with relative paths. When I tried:

```json
{
  "cadl.cadl-server.path": ".\\src\\cadl\\cadl\\node_modules\\.bin\\cadl-server.cmd"
}
```

I hit the above error (suggesting it hadn't found the file, per https://github.com/microsoft/cadl/blob/main/packages/cadl-vs/src/VSExtension.cs#L214-L218), but when I replaced it with:

```json
{
  "cadl.cadl-server.path": "C:\\<path-to-my-repo>\\src\\cadl\\cadl\\node_modules\\.bin\\cadl-server.cmd"
}
```
It worked.

Note that the 2nd issue here (the bug in the env processing) means I had to specify the `.cmd` file explicitly, because if I tried to just follow the README.md and specify `node_modules/@cadl-lang/compiler`, then I hit this branch: https://github.com/microsoft/cadl/blob/main/packages/cadl-vs/src/VSExtension.cs#L221, which makes me hit https://github.com/microsoft/cadl/blob/main/packages/cadl-vs/src/VSExtension.cs#L225, which in turn makes me hit https://github.com/microsoft/cadl/blob/main/packages/cadl-vs/src/VSExtension.cs#L87, which is where the bug is

**Comment by timotheeguerin** [comment]
@sebastianrex thanks for detailed reporting!
1. & 2. Good catch, will fix those.

For 3. Intresting, is it that the CWD of visual studio is not the workspace? TBH I think using relative path always leads to issue. I think we might want to support something similar to vscode where it interpolate `${workspaceRoot}`. Not sure if visual studio also has a similar convention or we should just do it.

**Comment by sebastianrex** [comment]
> For 3. Intresting, is it that the CWD of visual studio is not the workspace? 

Possibly?. To be honest, today is the first time I've attempted to use Visual Studio in anger (I'm following a template that used a VS project, so I just went with it).

But I'm afraid I don't know whether VS has a convention like `${workspaceRoot}`. I also saw that https://github.com/microsoft/cadl/issues/660 is open, and it sounds from the comments there that the current "workspace setting" way of setting up the cadl server path isn't the best long-term.

So, I think I'd be happy with a position where (1) and (2) get fixed up, and then (3) is deferred until the resolution of https://github.com/microsoft/cadl/issues/660

**Comment by timotheeguerin** [comment]
Problem with #660 is really a problem with visual studio not having a good story for extensions settings... This is the documented way to do it for extension but as that issue show it has a lot of problem. I don't think it will go away unless Visual studio decide to change their approach. What might happen is we might support an alternate way that work in the broken scenarios.
