### ISSUE TITLE
Add syntax for referencing operation parameters, operation return types, anonymous models

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#890]
For applications of augment ('@@') decorators, need to be able to address the parameters of an operation by name and the return values of an operation.

## Parameters - Option 1

`namespaceName.[interfaceName.]operationName.parameters.parameterName`

for example:

```cadl
model FooParam {
  value: string;
}

op FooOp(foo: string[]): void;

...

@@query(FooOp::parameters.foo, {format: "csv"});
```

## Parameters - Option 2
or
`namespaceName.[interfaceName.]operationName::parameterName`

for example: 
```cadl
model FooParam {
  value: string;
}

op FooOp(foo: string[]): void;

...

@@query(FooOp::foo, {format: "csv"});
```

## Return values -option 1

`namespaceName.[interfaceName.]operationName.returnValue[variant-number]`

```cadl
model FooParam {
  value: string;
}

op FooOp(foo: string[]): {bar: string} ;

...

@@header(FooOp::returnType.bar, "contentType", "text/json");
```

## Return values -Option 2 

`namespaceName.[interfaceName.]operationName>returnValue[variant-number]`

```cadl
model FooParam {
  value: string;
}

op FooOp(foo: string[]): string;

...

@@header(FooOp>returnValue[0], "contentType", "text/json");
```

## Union types

```
op FooOp(foo: string[]): {bar: string} | {baz: int};

@@header(FooOp::returnType::variants.get(0).bar, "contentType", "text/json");
```

- better for named variants

**Comment by timotheeguerin** [comment]
I think there is a general lack of support for anonymous models
- [Reference nested prop](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwptb2RlbCBGb28gewogIG5lc3RlZFByb3A6xRAgIGJhcjogc3RyaW5nOwogIH07Cn0KCmFsaWFzIEEgPcQ5Lso1LmJhcjsK)
```cadl
import "@cadl-lang/rest";
model Foo {
  nestedProp: {
    bar: string;
  };
}

alias A = Foo.nestedProp.bar;
```

- Referencing operation return type if its not a named model

**Comment by markcowl** [comment]
model Foo {
  bar: string
}

@error
model Bar {
  baz: string
}

op FooOp(): Foo | Bar;

**Comment by markcowl** [comment]
awkwardness when switching between metatype and object type

```fooOp::returnType::properties.get("x")```

```fooOp::returnType.x```

**Comment by johanste** [comment]
I've also come across the need to decorate uninstantiated templates. I'd also like to be able to access template parameters (to pass as decorator parameters; something that is common in reusable operation templates - e.g. `@createsResource(TResource)` or `@doc("Does stuff to {name}", T)`.

**Comment by markcowl** [comment]
I don't think there would be any difference between a model template and a model for decoration purposes.

For template arguments, can we actually decorate template arguments now?

Are you looking to reference a template argument in an augment decorator that targets the template?

For example

```cadl
@doc("Using name {name}", TNameProperty)
model MyTemplate<TNameProperty> {
  ...TNameProperty;
}
```

I think the default syntax for this would be
```cadl
@@doc(MyTemplate, "Using name {name}", MyTemplate::TemplateArguments[0])
```

**Comment by markcowl** [comment]
@johanste Closing this design issue, please ensure that any scenarios you want to see covered are in the implementation issue #1092
