### ISSUE TITLE
Cadl Tutorial for API Developers 

### ISSUE THREAD

**Issue by markweitzel** [microsoft/cadl#895]
This is the complete guide for developers wanting to define an API using Cadl. The start of this is the [tuturial.md](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md) that we've begun writing out. 

the Cadl tutorial is similar to what Jeffrey did for REST, which is to explain how HTTP works, then how REST works. Only then do we layer in what we do with Azure. This seems like a nice layering of concepts.

**Comment by mikekistler** [comment]
I think this will be a secondary resource for Azure Service teams because their primary reference will be the Cadl Azure Core tutorial/user guide.

I think this item should probably move to the external adoption workstream.

**Comment by allenjzhang** [comment]
We have detailed Getting Started tutorial steps for each of the packages ARM, Azure-Core, RPaas. @markweitzel I consider this item done unless you are specific data gaps you want to fill.

**Comment by mikekistler** [comment]
I agree that this is basically done. There is always room for more/better docs, but what we have is the foundation I think this epic was asking for.
