### ISSUE TITLE
Allow quotes to reference model properties, enum members, union variants, etc.

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#898]
Cannot reference enum with member name that are not identifier(Same for model properties)

```
enum Versions {
  "2022-01-01"
}

model MyModel {
  "my-property": string;
}


model MyUnion {
  "my-variant": Dog;
}

```

## Proposal 

Allow a new syntax with square bracket to pass a string `[]`

```
// Enum member
alias A = Versions["2022-01-01"];

// Model property
alias B = MyModel["my-property"];

// Union variant
alias C = MyNamedUnion["my-variant"];
```

This would be consistent with TypeScript syntax which lets you do the same thing

**Comment by annelo-msft** [comment]
Related to https://github.com/Azure/cadl-azure/issues/1916

**Comment by nguerrera** [comment]
Also model properties, union variants. And there's a general design issue to allow quoting all identifiers, so the solution should generalize.

**Comment by timotheeguerin** [comment]
## Pending identifier escaping proposal 

If we endup using `` ` `` for escaping identifier, this should just work
```
foo.`2021-01-01`
```
