### ISSUE TITLE
@armNamespace deprecated for @armProviderNamespace in 'playground' only

### ISSUE THREAD

**Issue by gwenbu-ms** [microsoft/cadl#912]
The playground sample contains a new `@armProviderNamespace` decorator that isn't supported in the available libraries, and it claims the `@armNamespace` decorator is deprecated.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmfMIGF6dXJlLXRvb2xzL8UscHJvdmlkZXJodWLdKMYRY29yZd8nxBFyZXNvdXJjZS1tYW5hZ2VyIjsKCkBhcm1Qx21OYW1lc3BhY2UKQHNlcnZpY2VUaXRsZSgiQ29udG9zb8goSHViQ2xpZW50IinJKlbmANgoIjIwMjEtMTAtMDEtcHJldmlld8QmZG9jyUcgUucAiCDIUSDmAJFtZW50IEFQSS7EMucBKWVkRGVwZW5kZW5jeShB5ADHLsg%2FTcU1ci7He3MudjFfMF9QxnVfMSkKbugA0CBNaWNyb3NvZnQu8gDLOwoKdXNpbmcgQ2FkbC5IdHRwO8wRUmVzdM0Rx29pbmfIF%2BYAl0NvcmXOEu8AqeQBbuUBCEEg8gCGIOgBnSIpCm1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWTIUTzIHFByb3BlcnRpZXM%2BIHsKICDGYOQByCBvZiBlxyYiKcQbZm9ybWF0KCJeW2EtekEtWjAtOS1dezMsMjR9JMYia2V5KCLINcRFxhdwYXRoxAhzZWfkAaLKI3PFIOQBZjogc3Ry5QESfegA5ekAv3DpAKTxANvqAL%2FrAL5BZ%2FIAvWFnZT86IGludDMyOwrJKkNpdHnRK2NpdHk%2F6gCQyS1Qcm9maWzSW%2BkBGGJhc2U2NFVybMUXcMYvPzogYnl0ZXPGSXZpc2liaWxpdHkoInJlYWTGQcVfVGhlIHN0YXR1c8RidGhlIGxhc3Qg5ADgYXRpb27kAtTFVsRE5QI%2BU3RhdMRg5QIFzBTmAUVhcm3oAe9PyEVzCmludGVyZuQC0%2BgBRHMgZXh0ZW5kc%2BkDV8ov6QIoLPMBcz4ge8Roa25vd25WYWx1ZXMo8QCLS1boAbPRG%2BQCl%2BkBZUBscm%2FEFnVzCmVudW3SLktW5QHiLi7pAxXTIywKIM06xBBVcGRhdMcMRGVsZcgMQWNjZXB0ZWQsCn0K)

**Comment by timotheeguerin** [comment]
Playground is always up to date with the latest changes from the `main` branch. However we only publish to npm on the `latest` tag every month. You can use `@next` tag to get the dev package from npm.
