### ISSUE TITLE
Converting existing project or swagger specification to CADL

### ISSUE THREAD

**Issue by shschwar** [microsoft/cadl#913]
Hello,

I have an existing large project written in C# of Azure ARM of [Azure Sentinel Data Connectors ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2022-08-01/DataConnectors.json)

The project has a few a few controllers and many model object. It also has multiple dependencies on other NuGets.

Is there an easy way to convert the project or existing specification and examples to CADL automatically?
Is there an easy way to import C# models into CADL to keep the existing classes and modules.

By the way, is there a timeline for GA version (or stable version 1+) for CADL?

Thanks
Shay

**Comment by nguerrera** [comment]
cc @joheredi

**Comment by nguerrera** [comment]
Related: https://github.com/Azure/cadl-azure/issues/1623

**Comment by nguerrera** [comment]
> Is there an easy way to convert the project or existing specification and examples to CADL automatically?

https://github.com/Azure/cadl-azure/issues/1623 tracks tooling for swagger -> CADL.

> Is there an easy way to import C# models into CADL to keep the existing classes and modules.

We do not have this or any plans for it. Would swagger -> CADL be enough for your purposes?

**Comment by nguerrera** [comment]
Closing against https://github.com/Azure/cadl-azure/issues/1623

**Comment by shschwar** [comment]
@nguerrera  - I'm believe that "Swagger --> CADL" will keep my current models in the right folder structure, so it when the models will be re-created from the CADL it will require adjuasments.
.

**Comment by shschwar** [comment]
@nguerrera  - I believe that "Swagger --> CADL" will keep my current models in the right folder structure, so it when the models will be re-created from the CADL it will require adjustments.

In advance: the link  https://github.com/Azure/cadl-azure/issues/1623 returns 404 (not found).
Any idea why?

**Comment by nguerrera** [comment]
It's an internal repo. You should have access now.
