### ISSUE TITLE
Duplicate compile/createProgram functions

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#914]
We have an exported function `compile` that is a purely redundant wrapper around `createProgam`. Should we remove it and just use `createProgram` everywhere? Or do we prefer the `compile` name? It feels like we shouldn't be exporting both as it's confusing and I was wondering if there was a difference when noticing that both are used in different places.

https://github.com/microsoft/cadl/blob/c78697eb2502a5f52139c0b6911e146def449e25/packages/compiler/core/program.ts#L965-L971

**Comment by bterlson** [comment]
`compile` is a verb you would likely look for if using Cadl as a library so I would say I like it better. I think at some point there was some work happening in compile but it went away.

**Comment by markcowl** [comment]
- Make the single method for compilation 'compile'
- deprecate 'createProgram' for 1 release
