### ISSUE TITLE
Move `@discriminator` to core

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#917]
It's strange that it presently lives in Rest. I think discriminated unions are a general enough feature for the functionality to live in core. I think the "discriminator on base type" thing is a little strange so perhaps the core discriminator only works on unions and it is extended to support base types in OA somehow?

**Comment by allenjzhang** [comment]
Passed. Moving to work item.

**Comment by markcowl** [comment]
need to also normalize the representation of extension based discriminators
@discriminator("type")
model Foo {
 type: string;
}
model Bar extends Foo
{
type: "Bar"
}

**Comment by markcowl** [comment]
design issue is to decide how to support both scenarios if discriminator for unions is in core

**Comment by markcowl** [comment]
- [ ] Move `@discriminator` and associated accessors supporting both extension and unions into core
- [ ] Update microsft/cadl and Azure/cadl-azure libraries and emitters to use the accessors
- [ ] Update samples in open source and Azure directories as needed
