### ISSUE TITLE
Projection typed argument

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#928]
Now that type relation is built into cadl. We should be able to define the expected type of argument of projection 
```cadl
projection interface#wire {
  to(version: string) {
   
  }

  from(version: string) {
   
  }
}
```

This however has a problem that if you have multiple projection for `wire` then you have to define the type of the parameter multiple times and this leave inconsistency issues

## Projection declaration proposal 

Proposal would be to have a projection declaration  where you would define the projection and the arguments. Then separately you would define the projection implementation. Advantage of this:
- Would have a single point where we define the argument of a projection
- Would treat projection name as a symbol. Wouldn't be a generic string that could be conflicting across libraries.

```cadl
namespace Foo;

// Define projection
projection target(targetName: string);

// Implement projection 

project model#target {
  to(targetName) { ... }
  from(targetName) { ... }
}

// Use projection name fully qualified name
project namespace#Foo.target {
  to(targetName) { ... }
  from(targetName) { ... }
}
```

**Comment by markcowl** [comment]
What would this look like for language-specific projections?  (toLang)

**Comment by timotheeguerin** [comment]
Well so what ended up doing was `target` projection in the project names. I don't think we need additional `to$Lang` projection (means emitters would need to run both)

```cadl
// Define projection
projection target(targetName: string);

// Implement projection 

project model#target {
  to(targetName) { ... }
  from(targetName) { ... }
}

// Use projection name fully qualified name
project namespace#Foo.target {
  to(targetName) { ... }
  from(targetName) { ... }
}
```

**Comment by timotheeguerin** [comment]
## Option 1: Declare symbol only, let projection define the arguments

```cadl
projection target;

project model#target {
  to(targetName: StringLiteral) {
  }

  from(targetName: string) {
  }
}

// Issue with different project
project namespace#target {
  to(targetId: int32) {
  }

  from(targetId: int32) {
  }
}
```

## Option 2: Declare as a fn declaration

```cadl
projection target(targetName: StringLiteral);

project model#target {
  to(targetName) {
  }

  from(targetName) {
  }
}

project namespace#target {
  // Different name but still inferred as string
  to(targetId) {
  }

  from(targetId) {
  }
}
```


## Option 3: Declare as symbol only, let projection define the arguments

```cadl
projection target {
  to(targetName: StringLiteral);
  from(targetName: StringLiteral, otherId: StringLiteral);
}

project model#target {
  to(targetName) {
  }

  from(targetName, otherId) {
  }
}

project namespace#target {
  to(targetId) {
  }

  from(targetId, otherId) {
  }
}
```

**Comment by allenjzhang** [comment]
Points raised in the proposal:
1. change projection target from a simple string to a strongly typed symbol/declaration
2. If so, what's the syntax and how it handles different arguments for to/from directions?

Discussion points:
1. Only support same signatures for to/from for now. 
----
projection wire(targetName: string);
project model#wire(targetName: string) 
{ 
   to { } 
   from {} 
}
---
2.

**Comment by timotheeguerin** [comment]
Moving to https://github.com/microsoft/cadl/issues/1131
