### ISSUE TITLE
Support string interpolation in docs

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/cadl#932]
Right now docs only support literal strings (as far as I know). It would be nice to be able to do string interpolation for docs. The specific use case I'm running into is in template interfaces, so your template docs can be updated when extended.

**Comment by bterlson** [comment]
Are we talking substituting in strings that are passed as template parameters, or something more complex? I know @petermarcu would like to see parameter docs moved up to the operation using interpolation but in that case it's not a string per se: https://github.com/microsoft/cadl/issues/927 (last code snippet).

**Comment by timotheeguerin** [comment]
Think talking about being able to do something like

```cadl
model Foo<T extends object> {

   @myDec("This is a property for {T::name}")
   foo: string;
}
```

**Comment by allenjzhang** [comment]
#927

**Comment by timotheeguerin** [comment]
Can we retriage this? This would a breaking change for all string using this pattern to do their own interpolation. Like what we have for `@doc`. See also limitation of current system #1376

**Comment by timotheeguerin** [comment]
# Proposal 

Allow `{}` to interpolate in string with `\{` to escape

```cadl
alias Bar = "bar";
alias Foo = "foo {Bar}"; // => "foo bar"
```

## How does this affect the TS api:

If we want to be able to say that a template string can be assigned to any place that is expecting a string this means we need to resolve the template completely at the compiler level and just pass the string to the decorator. This is however problematic if the goal is to actually get the template as it is.

Option 1: Helper

Have an helper in the decorator context to get the original template of a string argument if used.

```ts
export function $doc(context: DecoratorContext, target: Type, value: string) {
   const valueTemplate = getArgumentASTemplateString(0);
   if(valueTempalate) {
     // value arg is a template so we can do stuff on it.
  }
}
```

Option 2: Auto casting with signature
- Have an helper in the decorator context to get the original template of a string argument if used.
```cadl
extern dec pattern(target: unknown, value: string); // Here we are saying its a string so the implementaiton would receive the value as a string


extern dec doc(target: unknown, Cadl.Reflection.TemplateString); // Here we are saying we expect  a template string so we'd get that and not the resolved string.

extern dec doc(target: unknown, string | Cadl.Reflection.TemplateString); // Alternative always require `| string` when using `TemplateString` to say you can also accept a raw string.
```

**Comment by timotheeguerin** [comment]
Notes:

- Ok with breaking change
- Pick option 2 with the following rules:
- if type is `unknown` or `TemplatedString` always pass a `TemplatedString` even if its a string
- if type is `string` convert to a string if possible or fail
- if type is `string | TemplatedString` error saying to pick one

```cadl
model MyModel {}
alias Text = "Abc"

dec explicitString(target: unknown, value: string);

@doc("foo {MyModel}") // Complain saying this is not a string: "foo {MyModel}"
@doc("foo {Text}")    // Ok, gets "foo Abc"

dec explicitAccept(target: unknown, value: TempatedString);

@explicitAccept("foo")           // Ok, receive a TemplatedString
@explicitAccept("foo {MyModel}") // Ok, receive a TempatedString
@explicitAccept("foo {Text}")    // Ok, receive a TempatedString


// error?
dec either(target: unknown, value: string | TemplatedString);

@either("foo")           // bad, pick one
@either("foo {MyModel}") // bad, pick one
@either("foo {Text}")    // bad, pick one


// With this or without this signature
// dec noSig(target: unknown, value: unknown);
// Always a templated string

@noSig("foo")           // Ok, receive a TemplatedString
@noSig("foo {MyModel}") // Ok, receive a TemplatedString
@noSig("foo {Text}")    // Ok, receive a TemplatedString
```

```ts
function getAsString(
  templatedString: TemplatedStringLiteral
): [string | undefined, Diagnostics[]];
```

```cadl
@doc("foo {name}", MyName) 
// To
@doc("foo {MyName::name}")  
```

**Comment by markcowl** [comment]
- discuss proposal in next design meeting (briefly)

**Comment by timotheeguerin** [comment]
Things to decide for design meeting:

Syntax:
1.  Use `{}` to interpolate. `"foo {Text}"`
     - Breaking change
     - Writing JSON in there is harder, have to always escape "
2. CShap style:  `$"foo {Text}"`
    - If we support multiple `$$` to say how many `{` needed for interpolation, lets user write JSON easily
3. Swift style:  `"foo \(Text)"` and add `#""` to make a string literal
    -  Solve the JSON issue and the breaking change

**Comment by markcowl** [comment]
(1) "foo ${Text}"  also """ foo ${Text}"""
(2) deprecate @doc interpolation "{property}"
(3) Also allow interpolation in doc comments?
/*
 @param x ${x}  {@link link}
*/

scope= commented item?   use namespace to differentiate conflicts   invesutigate

alias FooConstant = "some text";
Model Foo {
  @projectedName("json", "mp")
  myProp: "${myprop::name}";
}

**Comment by markcowl** [comment]
Closing in favor of implementation issue
