### ISSUE TITLE
Allow using template parameter in default values

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#959]
Right now you can't pass in a default value as a parameter to a template.

This cadl
```cadl
model ModelWithDefaultTemplate<TProperty, TDefault> {
  @doc("Property with a default value.")
  propertyWithDefault?: TProperty = TDefault;
}
```
raises error `"Default must be have a value type but has type 'TemplateParameter'."`

Ask: add support for passing in default values as a template parameter

Copied from https://github.com/Azure/cadl-azure/issues/1969

**Comment by timotheeguerin** [comment]
To be done correctly depends on being able to demand a value type #888.

We could ignore default in template declaration to unblock but then adding #888  would be a breaking change.

**Comment by markcowl** [comment]
pri: 1

**Comment by markcowl** [comment]
@timotheeguerin So I think we can close this for now, as the most common scenario for this can use the `*literal` keywords to specify a specific literal (e.g. 'stringLiteral')

**Comment by viktorhanssonminut** [comment]
> @timotheeguerin So I think we can close this for now, as the most common scenario for this can use the `*literal` keywords to specify a specific literal (e.g. 'stringLiteral')

I'm only just starting out with Typespec so can you please elaborate on this answer, since I don't really understand what it means or how it solves the issue? What I'm trying to achieve is this:
```
model PagingParams<default = 10, max = 100> {
  @minValue(0)
  @maxValue(max) // <-- Argument 'max' is not assignable to parameter of type 'valueof numeric'
  @query
  limit?: integer = default; // <-- Default must be have a value type but has type 'TemplateParameter'

  @query
  offset?: integer;
}
```
In order to have re-usable pagination parameters for all my endpoints, but the defaults and max differ for each endpoint.
