### ISSUE TITLE
Allow `compile` cli options to be specified in `cadl-project.yaml`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#968]
| Cli options     | Config name    | Added |
| --------------- | -------------- | --------------- |
| `--emit`        | `emitters`     | ✅              |
| `--option`      | via `emitters` | ✅              |
| `--import`      | `imports`      |
| `--output-path` | `output-path`  |
| `--trace`       | `trace`        |
| `--watch`       | ❌             |
| `--pretty`      | ❌             |

**Comment by markcowl** [comment]
pri: 1
est: 3
