### ISSUE TITLE
cadl-rest should issue diagnostic for optional path parameter

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#973]
The OpenAPI v3 specification requires path parameters to be `required: true`. [link to spec](https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#contactObject:~:text=this%20property%20is%20REQUIRED%20and%20its%20value%20MUST%20be%20true).

The openapi3 emitter does not check for this and thus can produce an OpenAPI 3 definition that does not conform to the spec.

The openapi3 emitter should issue a diagnostic for a path parameter that is not required.

**Comment by timotheeguerin** [comment]
Are you testing this with the latest changes, 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/1031227/188474683-6a9ed8e8-07b6-4916-923c-3bb7e96f142e.png">
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKQHJvdXRlKCJ3aWRnZXRzL3tpZH0iKSAKb3AgcmVhZChAcGF0aCBpZD86IHN0cmluZynICTsK) 

Fix in https://github.com/microsoft/cadl/issues/672

**Comment by mikekistler** [comment]
A path parameter cannot be optional even if you specify a default value.  The above error goes away by adding a default value but that leaves the path parameter optional, which is not allowed by the OpenAPI spec.

![image](https://user-images.githubusercontent.com/85643503/188515419-d901e544-63b1-4600-9f9f-ffa3d3dc2a57.png)
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGm9wZW5hcGkiOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCkByb3V0ZSgiL8QwKQpAdGFnKCJGb28iKQpuYW1lc3BhY2UgRGVtb8czOwoKdXNpbmcgQ2FkbC5IdHRwO8cRT3BlbkFQSTsKCm1vZGVsIMdrewogIEBrZXkgaWQ6IHN0cmluZzsKICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSI7Cn0KCkBlcnJvcsdWRcQMxVVjb2Rly0BtZXNzYWdlymTEOugA3XflAIxz6QDh5gCcxBBpbnRlcmbkAOXGFOcA58ViyT97aWR9IikgQOQA0HJlYWQoQHBhdGggaWQ%2FyG8gPSAiZuQBNjrHSCB85gCr5ACI)

**Comment by timotheeguerin** [comment]
I guess iam not sure if then we should allow optional with default value in rest lib as well. Default being a server default it doesn’t make much sense for building the path?

**Comment by markcowl** [comment]
At the very least, this should be enforced by openapi3 and cadl-autorest emitters.  I think the likely intention here is to make the path parameter optional for generated clients, which the client-side defaults issue should take care of, the underlying property should still be required.

We may want to add this as a linting rule to the cadl-rest
