### ISSUE TITLE
The openapi3 emitter should set deprecated on an operation with the `@deprecated` decorator

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#979]
Cadl has a [{built-in) `@deprecated` decorator](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#deprecated) which can be applied to any language element. When applied to an operation, the openapi3 emitter should add [`deprecated: true`][openapi-deprecated] to the operation in the generated openapi. 

[openapi-deprecated]: https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#:~:text=the%20expected%20responses.-,deprecated,-boolean

**Comment by markcowl** [comment]
We should do this for cadl-autorest as well, the 'deprectated' operation property is supported in OpenAPI2 as well.
