### ISSUE TITLE
Design: @service({version: }) and @versioned coordination

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#982]
It is weird that to define a service we should use `@serviceTitle` or `@serviceVersion`. from https://github.com/microsoft/cadl/issues/679. We agreed there that we should rename to a new `@service` decorator

Change that will already happen:
- Deprecate `@serviceTitle` and then remove
- Deprecate `@serviceVersion` and then remove
- New decorator `@service`, which would take an object with optional properties:
  - `title`: Service title
  - `version`: Service version. 

```ts
export interface ServiceData {
  title?: string;
  version?: string | EnumMember;
}
export function $service(context: DecoratorContext, target: NamespaceType, data: ServiceData) {
}
```
Implemenation issue #1003

Proposing a solution to making the @serviceVersion not be confused with the versioning library #879 

### Service version when not using versioning

When not using versioning, we can just pass the version as it is.
```
@service({version: "1.0.0"});
namespace MyService;
```

### Service version when using versioning

When using versioning, the service version should reference the latest version in the versioned decorator.
```cadl
enum Versions{v1, v2, v3}

// Good
@versioned(Versions)
@service({version: Versions.v3});
namespace MyService;

// Ok, version not explicitly provided
@versioned(Versions)
@service
namespace MyService;

// Bad: version not defined in versioned list
@versioned(Versions)
@service({version: "1.0.0"});
namespace MyService;

// Bad: not the latest versin
@versioned(Versions)
@service({version: Versions.v1});
namespace MyService;
```

**Comment by markcowl** [comment]
Going with explicit version property for single version services, and no version property for services using versioning.

**Comment by markcowl** [comment]
needs implementation issue.

**Comment by timotheeguerin** [comment]
Implementation: https://github.com/microsoft/cadl/issues/1010
