### ISSUE TITLE
Investigate using spell check tool that can be enforced in the CI

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#983]
As part of https://github.com/microsoft/cadl/pull/978 @mikekistler added some `cspell` ignore coment, think it would be valuable to use a common tool (`cspell` or another) to validate spelling across the codebase

**Comment by nguerrera** [comment]
Looks like azure-sdk-for-js has this so maybe we can borrow some code:

https://github.com/Azure/azure-sdk-for-js/blob/f5de1196170c647e9dc9bef0833640b7bb5572e7/eng/common/pipelines/templates/steps/check-spelling.yml

**Comment by markcowl** [comment]
There is also a standard tool used for spell check in the rest-api-specs repository which we might be able to adapt, and certainly need to ensure we have at least the same level of functionality / dictionary

**Comment by timotheeguerin** [comment]
Forgot to link the issue ended up adding cspell and fixing all the issues 
- core: https://github.com/microsoft/cadl/pull/1000
- azure: https://github.com/Azure/cadl-azure/pull/2003

**Comment by timotheeguerin** [comment]
Seems to be the tool used by the specs repo anyway https://github.com/Azure/azure-rest-api-specs/blob/main/cSpell.json
