### ISSUE TITLE
Remove validation logic for duplicate route paths in `rest` library

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#984]
When you have two operations in a Cadl file which result in the same route path, the `rest` library raises a `duplicate-operation` diagnostic ([Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKb3AgZm9vT25lKCk6IHsgYWdlOiBpbnQzMiB9O8odUHJpbccibmFtZTogc3RyaW5nOyB9Ow%3D%3D)):

```
import "@cadl-lang/rest";

op fooOne(): { age: int32 };
op fooOnePrime(): { name: string; };
```

@johanste correctly pointed out to me that in the case of a route path which might have multiple request/response pairs (an overloaded operation), this diagnostic is undesired.  It seems we should depend on the emitters to decide whether they support duplicate route paths and raise their own diagnostics in that case.

It is possible for us to update the `openapi3` and `autorest` emitters to support this, so we should consider removing the restriction and adding emitter support for operation overloads like this.

**Comment by timotheeguerin** [comment]
is this true? I thought that overload was going to be explicit, so with the overload PR this diagnostic will need to be updated but will still need to be present.

**Comment by johanste** [comment]
Yes. Overloads is but one instance where things may be routed to the same endpoint. We really should let emitters decide if they can or cannot make sense out of the routes as defined.

**Comment by timotheeguerin** [comment]
The problem with having validation in emitters is that if multiple emitters will have the same requirement and are enabled at the same time you end up with duplicate diagnostic which is bad experience.

**Comment by markcowl** [comment]
est: 5
pri: 1

**Comment by markcowl** [comment]
@timotheeguerin @johanste I believe that the pattern we were talkin about is:

```cadl
import "@cadl-lang/rest";

op foo(): {age: int32} | {name: string};
@overloads(foo)
op fooOne(): { age: int32 };
@overloads(foo)
op fooOnePrime(): { name: string; };
```

Is there a pattern where we don't want to have the union representation we would emit in OpenAPI?

**Comment by johanste** [comment]
> Is there a pattern where we don't want to have the union representation we would emit in OpenAPI?
I'm assuming you are not talking about the non-deterministic:ness (from the client's perspective) in the example above that would make this somewhat problematic (i.e. there is no way for the service to distinguish between the two calls and thus there is not enough information in the signature to determine what the actual return value type would/should be.

In the general case, OpenApi 3.x would emit the union representation. Autorest-Swagger would use x-ms-paths. Client code emitters would do something language dependent. Python or TS would likely return a union. C# most likely would not do the overloads and use the distinct names.

**Comment by markcowl** [comment]
@johanste Unless I am missing something, the non-determinism is inherent in the initial example.  If inputs are not different for these output types, then there is no way for the client to determine what the output would be.

The current POR is to use the overload example above, and have emitters determine whether or not to use the overloads.  AFAIK this covers the proposed scenario.  Is there some scenario we want to support that is not covered by this?

**Comment by timotheeguerin** [comment]
## Design solution 

Be explicit when to bypass this error `@route` takes a new parameter `shared`, defaulting to `false` that would bypass `verb+route` validation.
```cadl
@route("/uploadImage", { shared: true })
op uploadImageBytes(@body body: bytes, @header contentType: "image/png"): void

@route("/uploadImage", { shared: true })
op uploadImageJson(@body body: {imageBase64: bytes}, @header contentType: "application/json"): void

// error: not shared route
@route("/uploadImage")
op uploadImageJson(@body body: {imageBase64: bytes}, @header contentType: "application/json"): void
```

Resulting python 
```py
def upload_image_bytes(body: stream):
  request("/uploadImage", body)
def upload_image_json(body: object):
  request("/uploadImage", body)
```

**Comment by timotheeguerin** [comment]
Implementation in #1133
