### ISSUE TITLE
`extern` decorators

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#994]
Implementation of `extern` decorators

## Decorator accessor syntax

New keyword for defining decorators and accessor:
- `dec`: Declare a decorator
- `fn`: Declare a function 
- `extern`: Mark decorator as implemented in TS

```
extern dec doc(target: entity, value: string, data?: Record<string, string>);
extern fn getDoc(target: entity): string; 
```

## Add new reflection namespace

To be able to support decorator signature in Cadl we need a way to specify a cadl `Type` as a type in cadl(`Enum`, `Interface`, etc.).

Create a new `reflection.cadl` containing a model for each one of the Cadl `Type`

```
namespace Cadl.Reflection;

model Entity {};
model Model {}
model Interface {}
```

| TS Interface Name   | Cadl reference  |
| ------------------- | --------------- |
| `Type`              | `Type`        |
| `Model`             | `Model`         |
| `ModelProperty`     | `ModelProperty`     |
| `Interface`         | `Interface`     |
| `Enum`              | `Enum`          |
| `EnumMember`        | `EnumMember`    |
| `Namespace`         | `Namespace`     |
| `Operation`         | `Operation`            |
| `StringLiteral`     | `StringLiteral`  |
| `NumericLiteral`    | `NumericLiteral` |
| `BooleanLiteral`    | `Boolean` |
| `Tuple`             | `Tuple`         |
| `Union`             | `Union`         |
| `UnionVariant`      | `UnionVariant`  |
| `IntrinsicType`     | N/A             |
| `FunctionType`      | N/A             |
| `ObjectType`        | N/A             |
| `TemplateParameter` | N/A             |
| `Projection`        | N/A             |

**Comment by markcowl** [comment]
pri: 1
est: 13

**Comment by kevinswiber** [comment]
This is interesting.  Is the `extern` syntax primarily for feeding symbols and signatures to tooling such as the language server?  Could this be implemented as a JavaScript-side API instead?  What advantages are offered by having an explicit `extern` declaration in Cadl?

**Comment by timotheeguerin** [comment]
The `extern` decorator is part of the bigger decorator in cadl picture described in this design issue #996. It is a way to declare the decorator definition for a decorator written in JS/TS and get type checking and IDE support(signature help, autocomplete, etc.)

This would be inline with having decorators defined in pure Cadl as described in the issue above. The other advantage is that JS files in cadl just gets imported, not parsed, so we don't have any information on where decorators are defined which makes diagnostic reporting or going to definition a little tricky. There is of course ways we could overcome this this particular js import problem but as we see having the ability to define some decorators in pure Cadl in the future this is a step towards it.

I however did think it would still be valuable to have a way to define that decorator in pure JS, it would just not be very clean looking. Something maybe like this:

```js
setSignature($doc, target: "Any", [{name: "doc", kind: "String"}]);
export function $doc(context, target, doc) {

}
```

**Comment by kevinswiber** [comment]
@timotheeguerin Yes, this is exactly what I was thinking.

With the current state, the compiler (and therefore the language server) has a hard dependency on JavaScript, as JS files can be imported into Cadl.  Using `extern` could offer a way out of that hard dependency (a future breaking change), but it seems like that should be part of a separate strategy not directly related to improving decorator support.

To that point, I think `extern` could be advantageous in scenarios where the source Cadl files have _no a priori knowledge_ of the implementations providing the symbols, instead having those libraries passed in compiler flags (essentially, a linking phase).
